### ISSUE TITLE
Incorrect identification: line too long

### ISSUE THREAD

**Issue by samir0282** [hierynomus/sshj#118]
Hi,
I am getting following exception while trying to open ssh connection.

Caused by: net.schmizz.sshj.transport.TransportException: Incorrect identification: line too long
at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:164)
at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:671)
at net.schmizz.sshj.SocketClient.connect(SocketClient.java:71)
at net.schmizz.sshj.SocketClient.connect(SocketClient.java:77)
at net.schmizz.sshj.SocketClient.connect(SocketClient.java:103)
at com.omneon.dam.util.bitspeed.BitSpeedUtil.openConnection(BitSpeedUtil.java:370)
at com.omneon.dam.util.bitspeed.BitSpeedUtil.exists(BitSpeedUtil.java:303)
... 19 more

The application has multiple threads. And each thread is opening its connection separately.
SSH version: OpenSSH_4.5p1, OpenSSL 0.9.8b 04 May 2006

In net.schmizz.sshj.transport.TransportImpl::readIdentification() getting buffer size more than 256 bytes.

**Comment by hierynomus** [comment]
@bk1te No, the both the client and server _MUST_ send the identification according to the RFC. That means that neither should necessarily wait for the other. 

Also the length of the buffer is enough according to the specification (i.e. [RFC 4253 section 4.2](https://tools.ietf.org/html/rfc4253#section-4.2)), where it specifies the max length of the identification string is 255 characters including the line terminators.

**Comment by bk1te** [comment]
Some server implementations send crypto info after they receive client id string and in some cases server receives client id before client receives servers one.  So when client start reading data it already has server id and crypto info and boom there is an error

**Comment by hierynomus** [comment]
I would consider that an error on the server side, as it then clearly does
not adhere to the protocol. Which ssh servers are we taking about? Do you
have any examples?

**Comment by bk1te** [comment]
It was on some openssh versions i really don`t remember which one

**Comment by bk1te** [comment]
btw locally i fix this issue that way and doesn`t have this error anymore..

**Comment by hierynomus** [comment]
It would be good to make a switch for this behaviour I think, instead of always waiting for the server ident string before sending our own. If we would encounter a server which also waits for the client ident string then we'd be screwed. A switch would be better in this case.

**Comment by hierynomus** [comment]
Thanks @bluekeyes For the PR to at least better identify that this happens.
