### ISSUE TITLE
Reader Thread does not close in 0.8.1 and 0.9

### ISSUE THREAD

**Issue by HiggsBugson** [hierynomus/sshj#127]
Hi Shikhar,

i encounter IllegalThreadeState Exceptions after trying 
Connect => Disconnect => Reconnect.

I Traced the Error down to trans.init. To be exact the point where it starts the reader.thread.
This causes an IllegalThreadStateException: Thread already started.

TransportI*(9251): Sending SSH_MSG_DISCONNECT: reason=[BY_APPLICATION], msg=[]
Reader(9251): Stopping

but after calling sshClient.connect(...) again:

Caused by: java.lang.IllegalThreadStateException: Thread already started
at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:167)

Failing operation is: reader.start();

**Comment by nartamonov** [comment]
I'm another person encountered with non-informative exception IllegalThreadState. More meaningful exception would be very helpful, something like `java.lang.IllegalStateException` with message `"Client was disconnected. Your should create new instance for another connection"`.

**Comment by madiaz1894** [comment]
> you can't reuse `SSHClient` and connect a second time with the same instance

Thank you so much!!!
