### ISSUE TITLE
SFTP transfer "fails" on freeFTPd

### ISSUE THREAD

**Issue by incendium** [hierynomus/sshj#15]
SSHJ is reporting an TransportException (Broken transport; encountered EOF) when closing a remote connection to this server.

<pre>
5 [main] INFO net.schmizz.sshj.common.SecurityUtils - BouncyCastle not registered, using the default JCE provider
794 [main] WARN net.schmizz.sshj.DefaultConfig - Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
842 [main] INFO net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0_3
1001 [main] INFO net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-WeOnlyDo-wodFTPD 2.3.6.165
1015 [main] INFO net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_KEXINIT
1018 [reader] INFO net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
1107 [reader] INFO net.schmizz.sshj.transport.kex.DHG1 - Sending SSH_MSG_KEXDH_INIT
1175 [reader] INFO net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
1175 [reader] INFO net.schmizz.sshj.transport.kex.DHG1 - Received SSH_MSG_KEXDH_REPLY
1198 [reader] INFO net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_NEWKEYS
1223 [reader] INFO net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_NEWKEYS
1228 [main] INFO net.schmizz.sshj.SSHClient - Key exchange took 0.214 seconds
1266 [main] INFO net.schmizz.sshj.transport.TransportImpl - Setting active service to ssh-userauth
1266 [main] INFO net.schmizz.sshj.userauth.UserAuthImpl - Trying `password` auth...
1266 [main] INFO net.schmizz.sshj.userauth.method.AuthPassword - Requesting password for [AccountResource] test@127.0.0.1
1345 [reader] INFO net.schmizz.sshj.transport.TransportImpl - Setting active service to ssh-connection
1345 [main] INFO net.schmizz.sshj.userauth.UserAuthImpl - `password` auth successful
1363 [main] INFO net.schmizz.sshj.connection.ConnectionImpl - Attaching `session` channel (#0)
1410 [reader] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Initialized - < session channel: id=0, recipient=1000, localWin=[winSize=2097152], remoteWin=[winSize=131072] >
1410 [main] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
1410 [main] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Sending channel request for `subsystem`
1441 [reader] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Received window adjustment for 0 bytes
1496 [main] INFO net.schmizz.sshj.sftp.SFTPEngine - Server version 3
1510 [main] INFO net.schmizz.sshj.connection.channel.direct.SessionChannel - Sending close
1574 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
1576 [reader] INFO net.schmizz.sshj.connection.ConnectionImpl - Forgetting `session` channel (#0)
1576 [main] ERROR net.schmizz.concurrent.Event - <<chan#0 / close>> woke to: net.schmizz.sshj.connection.ConnectionException: Broken transport; encountered EOF
1576 [reader] INFO net.schmizz.sshj.transport.TransportImpl - Setting active service to null-service
Exception in thread "main" net.schmizz.sshj.connection.ConnectionException: Broken transport; encountered EOF
        at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)
        at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)
        at net.schmizz.concurrent.Future.error(Future.java:95)
        at net.schmizz.concurrent.FutureUtils.alertAll(FutureUtils.java:24)
        at net.schmizz.sshj.connection.channel.AbstractChannel.notifyError(AbstractChannel.java:239)
        at net.schmizz.sshj.common.ErrorNotifiable$Util.alertAll(ErrorNotifiable.java:34)
        at net.schmizz.sshj.connection.ConnectionImpl.notifyError(ConnectionImpl.java:152)
        at net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:545)
        at net.schmizz.sshj.transport.Reader.run(Reader.java:79)
Caused by: net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
        at net.schmizz.sshj.transport.Reader.run(Reader.java:70)
</pre>

Steps to reproduce:

<ol>
<li>Install [freeFTPd](http://www.freesshd.com/?ctt=download) (use default configuration, be sure to add an FTP user).</li>
<li>Modify the following class to connect to the SSH server you configured:<pre>
import net.schmizz.sshj.SSHClient;
import net.schmizz.sshj.sftp.SFTPEngine;
import net.schmizz.sshj.sftp.SFTPClient;
import net.schmizz.sshj.transport.verification.PromiscuousVerifier;

public class SSHTest {
    public static void main(String[] args) throws Exception {
        SSHClient ssh = new SSHClient();
        ssh.addHostKeyVerifier(new PromiscuousVerifier());
        ssh.connect("127.0.0.1", 22);
        ssh.authPassword("test", "test");

        SFTPClient sftp = ssh.newSFTPClient();
        sftp.close();

        ssh.disconnect();
    }
}
</pre></li>
<li>Compile and run the class.</li>
</ol>

**Comment by tripexito** [comment]
I've been using **SSHJ v0.20.0** to connect using sftp to **freeFTPd** and I'm getting the same Exception. I've realized that it doesn't work if try to upload any file to FTP server (reading files works fine). Even if I comment the close/disconnect instruction. Please give anyone can give me some approach how to solve this. Thanks in advance.
