### ISSUE TITLE
scp rate limiting

### ISSUE THREAD

**Issue by pradeepg26** [hierynomus/sshj#155]
Adding rate limits to the bandwidth used by the scp client is a nice feature to have. Scp already supports this using the "-l" flag.

**Comment by hierynomus** [comment]
I would welcome a Pull Request.

**Comment by dkocher** [comment]
You can achieve this by wrapping the streams yourself. I think this is out of scope for sshj.

**Comment by hierynomus** [comment]
True, that is probably the nicest way to solve that. Also no response anymore on this ticket, so going to close this.
