### ISSUE TITLE
Remote file modified and accessed time is wrong.

### ISSUE THREAD

**Issue by MadasamySankarapandian** [hierynomus/sshj#158]
We have using v0.9.0 in our application.  We have using [SFTPClient](https://github.com/hierynomus/sshj/blob/master/src/main/java/net/schmizz/sshj/sftp/SFTPClient.java) to list a files. From the result get the modified time using RemoteResourceInfo#FileAttributes#getMtime.  It always return the wrong last modified datetime in millis (**1416280051**). This is equivalent to **17-jan-1970 16:54:39** But actual modified time of respective file is **13-Nov  2014, 9:24:21 AM**. The FileAttributes#getAtime also give wrong value.

**Comment by hierynomus** [comment]
Thanks for this issue. Unfortunately I think the error is not in SSHJ. When I insert the datetime in millis (1416280051) in the [Epoch converter](www.epochconverter.com), I actually get the correct timestamp (GMT: Tue, 18 Nov 2014 03:07:31 GMT).

So I think you should check your own calculation code.

**Comment by swotge** [comment]
Thanks Hierynomus. I will check my code.

**Comment by Kitsune2222** [comment]
sshj count time in seconds! Not millis! Value need multiply by 1000, you can check it here https://currentmillis.com/
