### ISSUE TITLE
Add key exchange algorithm diffie-hellman-group-exchange-sha256

### ISSUE THREAD

**Issue by dkocher** [hierynomus/sshj#167]
Currently only `diffie-hellman-group14-sha1` and `diffie-hellman-group1-sha1` is implemented.

**Comment by dkocher** [comment]
[Diffie-Hellman Group Exchange for the Secure Shell (SSH) Transport Layer Protocol](https://tools.ietf.org/html/rfc4419)

**Comment by dkocher** [comment]
Refer also to [Specifications implemented by OpenSSH](http://www.openssh.com/specs.html).

**Comment by grkvlt** [comment]
Any progress on this? It is becoming an issue due to many SSH servers deprecating support for the SHA-1 algorithm, so we cannot connect to them. How much work would be involved adding this support?

**Comment by hierynomus** [comment]
No progress on this yet. From what I read the flow for this exhange
algorithm seems different from the current ones. This might mean it's a
"big" refactoring.

2015-05-09 0:24 GMT+02:00 Andrew Donald Kennedy <notifications@github.com>:

**Comment by MichalStaruch** [comment]
This issue blocks secure sshd configuration on every server that needs to be accessible via sshj. It's 2015 now and SHA-1 shouldn't be used for crypto, anymore - it's too easy to generate collisions on it. And RFC4419 where diffie-hellman-group-exchange-sha256 was defined is 9 years old already...

**Comment by paulschreiber** [comment]
+1

**Comment by dkocher** [comment]
:clap:
