### ISSUE TITLE
net.schmizz.sshj.sftp.SFTPException: Handle not Found when Attempting to Upload a File

### ISSUE THREAD

**Issue by MusikPolice** [hierynomus/sshj#168]

**Comment by hierynomus** [comment]
Hi MusikPolice,

Which SSH server are you connecting to? Can you try building the latest snapshot and using that one?

**Comment by MusikPolice** [comment]
Hi Jeroen,

I tried cloning the repository and building the latest version, but got test failures in PuTTYKeyFileTest.testCorrectPassphraseDsa and PuTTYKeyFileTest.testCorrectPassphraseRsa. Both say "IO Illegal key size"

Unfortunately, my SFTP server is not public, so I can't share much information about it. 
---
Jonathan Fritz
On the web: http://www.jonathanfritz.ca

**Comment by hierynomus** [comment]
Hi Jonathan,

Please download the JCE (Java Cryptography Extensions) from the Oracle site. Those tests need strong encryption to be enabled.

I meant to ask the type of ssh server (i.e. winsshd, openssh, etc), and the version :smile:. No need for access to your box.

**Comment by hierynomus** [comment]
Closing this one in favour of  #169
