### ISSUE TITLE
Library in Maven repository compiled with jdk 1.7

### ISSUE THREAD

**Issue by jerosch** [hierynomus/sshj#179]
Hi,

it seems like there is a mismatch between the minimum Java version in the readme and the bytecode version in the jar in the maven repository.

At least I get an *java.lang.UnsupportedClassVersionError: net/schmizz/sshj/SSHClient : Unsupported major.minor version 51.0* error when trying to instantiate the SSHClient class.

Can't say whether this is a mistake in the documentation or in the deployed jar.

**Comment by hierynomus** [comment]
For which version of SSHJ?

**Comment by jerosch** [comment]
Sorry - 0.11.0
