### ISSUE TITLE
Question: Non-22 port supported?

### ISSUE THREAD

**Issue by carolinux** [hierynomus/sshj#191]
Hello,
I can't find a way to start an ssh client on localhost, port 5000. Is it possible? I looked at the SSHClient code and it always uses the default value with no way to override.  If it's definitely not possible, I could contribute this change.

relevant code:

https://github.com/hierynomus/sshj/blob/master/src/main/java/net/schmizz/sshj/SSHClient.java

**Comment by carolinux** [comment]
ok, my bad, I discovered that the connect function inherited from SocketClient has the functionality I want.

**Comment by smartsheetcloudtools** [comment]
For anyone else that finds this - you can just call connect ("HOSTNAME",<Port number>)

**Comment by delmartechdude** [comment]
For anyone else that finds this - you can just call connect ("HOSTNAME", Port Number )
https://github.com/hierynomus/sshj/blob/master/src/main/java/net/schmizz/sshj/SocketClient.java#L120
