### ISSUE TITLE
Any way to get a download InputStream?

### ISSUE THREAD

**Issue by mntgoat** [hierynomus/sshj#192]
This isn't really an issue, more of a question. I am trying to use the SFTP download but there doesn't seem to be a way to get an InputStream, seems like it always wants to download into a file. Is this an option somewhere that I'm just not finding?

Thanks.

**Comment by hierynomus** [comment]
No, you're not finding it because it indeed does not exist. You can take a
look at how SftpFileTransfer (
https://github.com/hierynomus/sshj/blob/master/src/main/java/net/schmizz/sshj/sftp/SFTPFileTransfer.java)
works.

2015-05-12 20:59 GMT+02:00 mntgoat <notifications@github.com>:

**Comment by dkocher** [comment]
It does exist although somewhat buried in an inner class. 

````
final RemoteFile handle = session.sftp().open(file.getAbsolute(),
        EnumSet.of(OpenMode.READ));
final InputStream in = handle.new RemoteFileInputStream() {
    @Override
    public void close() throws IOException {
        try {
            super.close();
        }
        finally {
            handle.close();
        }
    }
};
````
There is also an optimised version for better performance using read ahead named `ReadAheadRemoteFileInputStream`. Make sure to manually close the handle after closing the stream.

**Comment by mntgoat** [comment]
Thanks, I'll take a look at that.

**Comment by mntgoat** [comment]
That appears to work and does what I need. Thank you. The `ReadAheadRemoteFileInputStream` class doesn't seem to be available on 0.9 so I'll have to wait for the Android issues to be fixed on the newer versions before trying it. 

Thanks.

**Comment by mntgoat** [comment]
One more question, I didn't see a way to open the file at an specific position, for resuming, is that possible with this library? Thanks.

**Comment by dkocher** [comment]
Refer to the `offset` parameter.

**Comment by mntgoat** [comment]
Sweet, thank you.

**Comment by AlexandrSokolov** [comment]
It is a pity, that as it is said in a lot of sources, "new api for sftp" does not provide a way to work directly with `InputStream`
Is it possible to request such functionality? It exists, for instance in `JSch`.

**Comment by hierynomus** [comment]
You are free to submit either a PR, or a feature request for improvement.
