### ISSUE TITLE
Support SSH_MSG_USERAUTH_PASSWD_CHANGEREQ

### ISSUE THREAD

**Issue by dkocher** [hierynomus/sshj#193]
Currently password change requests are not handled in `AuthPassword`. We should implement a callback option to let the user provide updated credentials and retry authentication.

**Comment by dkocher** [comment]
See [8.  Password Authentication Method: "password"](http://tools.ietf.org/html/rfc4252#page-10) in RFC 4252.

**Comment by hierynomus** [comment]
Hi @dkocher,

Have a look at the attached commit. If needed we can further tune the API before releasing.

**Comment by hierynomus** [comment]
@dkocher Could hou have a look at the change for this and see whether it makes sense. I'd like to release a new version pretty soon, given the fixed race conditions :wink:

**Comment by dkocher** [comment]
@hierynomus Will do just now.

**Comment by dkocher** [comment]
Is it ok to return `null` for `provideNewPassword`  when the user cancels the prompt?

**Comment by hierynomus** [comment]
`putSensitiveString` is null-safe. So yes, it should be ok!

**Comment by dkocher** [comment]
@hierynomus Looks good to me then.
