### ISSUE TITLE
Executing background jobs using session.exec()

### ISSUE THREAD

**Issue by greenjoe** [hierynomus/sshj#194]
Hello! 

I am not an expert when it comes to linux or ssh and I have no idea if it is a bug or not, but after two days of trying to execute headless firefox in the background using ```session.exec()``` I am really wondering if the behavior is intended or maybe I am doing something wrong :-) 

When I am executing any "background" command (ending with "&") using ```session.exec()``` it just doesn't work. Finally I have found a workaround which writes commands to shell's output stream instead of using ```session.exec()``` and it looks like it's working. 

The code snippet below contains two methods - ```usingExec()``` and ```usingShell()```. Both are trying to execute ```mkdir directoryName &``` which itself doesn't make any sense (why would someone create a directory in the background?) but it is simple and shows the problem. When calling ```usingExec()``` the directory is not on the remote machine created, but when calling ```usingShell()``` it is.

Is it intended? Am I missing something in ```usingExec()``` that would make it work? :-) 

```java
	private final static String ADDRESS = "...";
	private final static String KEY_LOCATION = "...";

	public static void usingExec() throws IOException {
		SSHClient sshClient = getSshClient();
		Session session = getSession(sshClient);
		Command command = session.exec("mkdir usingExec &");
		command.join();
		sshClient.close();
	}

	public static void usingShell() throws IOException {
		SSHClient sshClient = getSshClient();
		Session session = getSession(sshClient);
		Shell shell = session.startShell();
		OutputStream outputStream = shell.getOutputStream();
		outputStream.write(Strings.toUTF8ByteArray("mkdir usingShell &\n"));
		outputStream.flush();
		outputStream.write(Strings.toUTF8ByteArray("exit\n"));
		outputStream.flush();
		shell.join();
		sshClient.close();
	}

	private static SSHClient getSshClient() throws IOException {
		SSHClient sshClient = new SSHClient();
		sshClient.getTransport().addHostKeyVerifier(new PromiscuousVerifier());
		sshClient.connect(ADDRESS);
		sshClient.getConnection().getKeepAlive().setKeepAliveInterval(5);
		sshClient.auth("ubuntu", new AuthPublickey(getKeyFile()));
		return sshClient;
	}

	private static Session getSession(SSHClient client)
			throws ConnectionException, TransportException {
		Session session = client.startSession();
		session.allocateDefaultPTY();
		return session;
	}

	private static PKCS8KeyFile getKeyFile() {
		PKCS8KeyFile keyFile = new PKCS8KeyFile();
		keyFile.init(new File(KEY_LOCATION));
		return keyFile;
	}
```

**Comment by hierynomus** [comment]
I think the correct invocation would be `nohup <command> >>nohup.out 2&>1 &`

This will start using nohup (no hangup), redirect all output to
`nohup.out`, redirect stderr to stdout, and start in the background.

It's pretty elaborate, but far as I remember the only correct way of
starting it in the background and not being killed by the disconnect.


2015-05-17 19:31 GMT+02:00 Paweł Chorążyk <notifications@github.com>:

**Comment by greenjoe** [comment]
During those two days when I was experimenting with running a background command using ```session.exec()``` I think I have tried all combinations of nohup, stream redirects and so on and I believe it is just not possible (but works perfectly when using the shell API). You can try changing the command in the code snippet provided by me to execute with nohup and stream redirects and the behavior is still the same. 

```		Command command = session
				.exec("nohup mkdir usingExec >/dev/null 2>&1 </dev/null  &");```

I'd also like to mention that intuitively I expected  ```session.exec("cmd")``` to behave in the same way as executing ```ssh user@$SERVER_ADDRESS "cmd"``` manually but it is not. Running background jobs with ssh command works without problems, for example
```ssh user@$SERVER_ADDRESS "mkdir testdir &"``` creates directory on the target server, but as my code snippet shows - it doesn't work with ```session.exec``` (and of course the same difference will occur if you add nohup and stream redirects). I would also like to emphasize that mkdir here is just a "toy" example but I had problems with running a normal long-term process you may want actually to run in background after disconnecting (firefox in my case).

**Comment by hierynomus** [comment]
I've added a testcase using Apache MINA that seems to work. Can you have a look at that?

**Comment by greenjoe** [comment]
I have played with the test case you provided and couldn't make it fail. Then I thought I could use localhost ssh connection instead of the fixture and see if it fails. Step by step I was converting the test case into the code I have pasted in this issue and I think I have found why it doesn't work for me.

At some point of my playing with sshj I have added the line to the session initializing method:

        session.allocateDefaultPTY();


If I remember correctly firefox didn't want to start without allocating PTY. It looks like background mkdir command works fine only when that line is deleted. The version of the test case that fails: 
````
package com.hierynomus.sshj.connection.channel.direct;

import com.hierynomus.sshj.test.SshFixture;
import net.schmizz.sshj.SSHClient;
import net.schmizz.sshj.connection.channel.direct.Session;
import net.schmizz.sshj.connection.channel.direct.Session.Command;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import net.schmizz.sshj.transport.verification.PromiscuousVerifier;
import  net.schmizz.sshj.transport.TransportException;
import net.schmizz.sshj.connection.ConnectionException;

import java.io.File;
import java.io.IOException;

import static org.hamcrest.MatcherAssert.assertThat;

public class CommandTest {

    private final static String LOCAL_USER = "...";
    private final static String LOCAL_PASSWORD = "...";


    @Rule
    public TemporaryFolder temp = new TemporaryFolder();



    @Test
    public void shouldExecuteBackgroundCommand() throws IOException {
        SSHClient sshClient =  new SSHClient();
        sshClient.getTransport().addHostKeyVerifier(new PromiscuousVerifier());
        sshClient.connect("localhost");
        sshClient.authPassword(LOCAL_USER, LOCAL_PASSWORD);
        File file = new File(temp.getRoot(), "testdir");
        assertThat("File should not exist", !file.exists());
        Session session = sshClient.startSession();
        session.allocateDefaultPTY();
        Session.Command exec = session.exec("mkdir " + file.getPath() + " &");
        exec.join();
        sshClient.close();
        assertThat("File should exist", file.exists());
        assertThat("File should be directory", file.isDirectory());
    }
    
}
````
It only fails with real connection, so credentials to localhost ssh have to be provided. I have no idea if the fact that allocating default PTY changes the behavior is bug or not, I'm not familiar with ssh/shell inner workings enough to grasp it. 

Thank you for taking your time to take a look at this issue and create a test case :-)

**Comment by toff** [comment]
This is a normal ssh behaviour.
When you allocate a PTY and you disconnect any child process of the session will be killed with the HUP signal.
For example this will successfully create the /tmp/foobar directory :
```Shell
$ ssh localhost "mkdir /tmp/foobar &" 
```
But if you allocate a PTY (-t) it will not :
```Shell
$ ssh -t localhost "mkdir /tmp/foobar &"
```

If you want to use a PTY allocation then you need to make you process immune to the HUP signal.
nohup seems to be a good choice but it seems it can get killed even before doing it's job. So a reliable way is to use the following command :
```Shell
ssh -t localhost "nohup sh -c 'mkdir /tmp/foobar &' &>/dev/null"
```

**Comment by hierynomus** [comment]
Thanks @toff, closing this issue in this case. The problem was the PTY allocation :).

**Comment by golimarrrr** [comment]
I have the exact opposite problem. When closing the local Java application while the remote command is still running, it gets disconnected but processes like this remain open at the server:

`user1     13892     1  0 10:48 ?        00:00:00 sh -c mycommand ....`

Even though I'm not using `nohup` and I'm using `session.allocateDefaultPTY()`
