### ISSUE TITLE
Is it safe to share an instance of DefaultConfig for multiple SSHClient instances & threads? 

### ISSUE THREAD

**Issue by andreisavu** [hierynomus/sshj#197]
That would make SSHJ require less entropy and create a smaller number of Java objects.

**Comment by andreisavu** [comment]
If this is not safe in a multi-threaded context, would  it be safe as a ThreadLocal?

**Comment by hierynomus** [comment]
It should be safe, as it provides only configured factories. So I would venture to say that it is safe (unless you of course implement a non-threadsafe factory)

**Comment by hierynomus** [comment]
If this answered your question can you respond please?

**Comment by andreisavu** [comment]
Yes. Sharing this works as expected. We also added an immutable wrapper for additional safety.
