### ISSUE TITLE
ssh stream hangs if files exceeds 2.5M

### ISSUE THREAD

**Issue by replyxf** [hierynomus/sshj#205]
I opened a ssh shell, and run " cat a.log" , use cmd.join to wait, 
1 can be generated by:dd if=/dev/zero of=a.log bs=1024 count=2500.

no response comes back.

if file size is less than 2M, it is fine. 

any suggestion?

**Comment by replyxf** [comment]
not a problem. I used command.join too soon. I moved the command.join to later part of the code. it is fine

**Comment by hierynomus** [comment]
Marked as closed as it was fixed.
