### ISSUE TITLE
SLF4J - error message

### ISSUE THREAD

**Issue by magg** [hierynomus/sshj#213]
Hi 

I'm using sshj to make an command line tool that connects to several hosts, one thread per host and executes several commands. The app uses command line arguments and all those things. 

One thing to note, when I use more than one thread this output shows on screen. How can I prevent sshj from throwing this message?

SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: net.schmizz.sshj.common.SecurityUtils
SLF4J: net.schmizz.sshj.DefaultConfig

**Comment by magg** [comment]
probably related to #135, but here I'm making a new application from scratch... not using another

**Comment by hierynomus** [comment]
How are you initializing the logging system? Do you have a `logback.xml` on the classpath, or are you doing it programmatically?

One way to prevent this message from happening is initializing the logging in your main thread first, and only then spin up the worker threads. Initializing logging could be as simple as defining a `private static final Logger log = LoggerFactory.getLogger(...)` in your main app.

Also the warning is not harmful if you read the documentation. The loggers created work fine once the framework is fully initialized.

**Comment by magg** [comment]
I have log4j.properties in src/main/resources

this is the content:
log4j.logger.net.schmizz.concurrent.Promise	=	OFF
log4j.logger.net.schmizz.sshj.common.IOUtils	=	OFF
log4j.logger.net.schmizz.sshj.common.StreamCopier	=	OFF
log4j.logger.net.schmizz.sshj.transport.TransportImpl	=	OFF
log4j.logger.net.schmizz.sshj.common.SecurityUtils =	OFF
log4j.logger.net.schmizz.sshj.transport.KeyExchanger = OFF
log4j.logger.net.schmizz.sshj.DefaultConfig = OFF
log4j.logger.net.schmizz.sshj	=	OFF
log4j.rootLogger=OFF

**Comment by magg** [comment]
I put `private static final Logger log = LoggerFactory.getLogger(...)` in my main app.

Seems to stop the message, thanks mate!
