### ISSUE TITLE
Main page link to web site leads to 404

### ISSUE THREAD

**Issue by gkohen** [hierynomus/sshj#214]
On the main readme.md of the project the link to http://schmizz.net/sshj leads to a 404.

**Comment by hierynomus** [comment]
The README.md has not been in master for some time I think. Where do you see it? The current README far as I can see also has no link to schmizz.net/sshj...

**Comment by gkohen** [comment]
Have a look at the link to http://schmizz.net/sshj  on top of the project github page and you'll get a 404.

**Comment by hierynomus** [comment]
Found it, that's not in the README :) That is in the project settings... Now fixed, thanks!
