### ISSUE TITLE
SCPException should contain field of remote error message

### ISSUE THREAD

**Issue by juddgaddie** [hierynomus/sshj#215]
Create SCPRemoteException extends SCPException

ScpDownloadClient.java line 126
 ```java
  case (char) 2:
                throw new SCPException("Remote SCP command returned error: " + msg.substring(1));
```

Could be 
 ```java
  case (char) 2:
                throw new SCPRemoteExeption("Remote SCP command returned error: ", msg.substring(1));
```

Then one could
 ```java 
try {
         ssh.newSCPFileTransfer().download("*_test", "/tmp");
    } catch (SCPRemoteException e){
     if (e.getRemoteMessage().contains("File not Found on this server"))
     {
         //do something special.
     }
}
```

The reasoning behind this is SshJ can not handle all the possible arbitrary messages sent back from the remote ssh server, but it would be nice to make it easier for the user to handle.

**Comment by hierynomus** [comment]
A PR is welcome :)

2015-09-23 0:16 GMT+02:00 Judd Gaddie <notifications@github.com>:

**Comment by juddgaddie** [comment]
I am pretty sure this doesn't cover all cases of a remote server returning an error but it does cover my SCP use case.
See: 10f8645ecd59348e6df041c200e9bd98fadea68b

**Comment by hierynomus** [comment]
Could you make a PR for that one?

**Comment by hierynomus** [comment]
merged pr :)
