### ISSUE TITLE
Example for Retrieving Status for Scp transfer in progress? 

### ISSUE THREAD

**Issue by leebs778** [hierynomus/sshj#221]
Hoping for a code example using TranferListener in order to retrieve transfer status. Seems unclear from the outset about how to do this.

**Comment by cvswarrior** [comment]
Check out the class: net/schmizz/sshj/xfer/LoggingTransferListener for an implementation of TransferListener.

Usage example:
`SCPFileTransfer scpupload = ssh.newSCPFileTransfer();`
`scpupload.setTransferListener(new LoggingTransferListener());`
`scpupload.upload(new FileSystemFile((filetocopy.getAbsoluteFile())), destfolder);`

**Comment by hierynomus** [comment]
@leebs778 Can this be closed?

**Comment by hierynomus** [comment]
Closing this issue due to no response.
