### ISSUE TITLE
pom entries

### ISSUE THREAD

**Issue by puntogil** [hierynomus/sshj#228]
hi
sshj-0.13.0/build/poms/pom-default.xml ```<artifactId>sshj-0.13.0</artifactId>```
It is wanted? It should not be ```<artifactId>sshj</artifactId>```
thanks in advance
regards

**Comment by hierynomus** [comment]
You might want to help me out here.

1. What are you doing
2. What are you seeing
3. What is wrong according to you?

I cannot makes heads or tails of this issue without some additional context.

**Comment by puntogil** [comment]
hi
seem the problem occurs only in my build system
using gradle 2.5, OpenJDK 1.8
regards

**Comment by puntogil** [comment]
Hi,
The porblem is commented here:
https://discuss.gradle.org/t/rootproject-name-in-settings-gradle-vs-projectname-in-build-gradle/5704/2
I used for fix: echo 'rootProject.name="sshj"' >> settings.gradle
Regards

**Comment by hierynomus** [comment]
Added a `settings.gradle` file.

2015-12-11 14:34 GMT+01:00 puntogil <notifications@github.com>:
