### ISSUE TITLE
Output truncation

### ISSUE THREAD

**Issue by iKarthik** [hierynomus/sshj#229]
First, many thanks for this library. Your api is easy to use and intuitive. 

Am following your sample code to execute a command that will get me file stats in a particular folder. When I execute the same command on the shell, everything seems to be ok, but I when I use your library to do the same, my results seem to get abruptly truncated. And this only happens if there about 100 odd files in the directory. If works fine if the directory has fewer files (works fine with 10 files) This leads me to believe somewhere am over running my buffer. I tried to set buffer size but in vain. Please find my SSH Client attached. And the command that am trying to execute is this

find /folder1/something/ -printf '%p\t%s\t%Tc\n'

Please advice

Thanks
Kay

[SshService.zip](https://github.com/hierynomus/sshj/files/81763/SshService.zip)

**Comment by hierynomus** [comment]
Hi ikarthik,

I have no direct clue what may be going wrong. Do you have some (debug) logging that would allow us to see what is happening, and why the output is truncated by accident?

**Comment by iKarthik** [comment]
Hierynomus

I used your library bare bones without using ExpectIt (copied your code from Exec.java), I was able to get un-truncated output. Looks like ExcpectIt framework might be causing the buffer issue.

I had to use ExpectIt, because I have a series of commands that I want to issue, starting a session every time seems to take too long and each command produces a lot of output. Spiltting into separate commands helps with output size. Hence the dependency on ExpectIt. 

Do you have any other suggestions, if I have a series of commands to issue

**Comment by hierynomus** [comment]
If I understand you correctly, you could have a look at using https://github.com/xebialabs/overthere.git. This is built on top of SSHJ. We use that ourselves (I'm a XebiaLabs employee) to issue multiple commands against machines.

**Comment by hierynomus** [comment]
@iKarthik Is there anything I can help you with still? Else I'm inclined to close this question as answered :)

**Comment by iKarthik** [comment]
Sorry about not closing this promptly, yes you can close this. I switched over to overthere.git. Thanks for the suggestion

**Comment by hierynomus** [comment]
Closing :)
