### ISSUE TITLE
How to put a file to sftp using private key

### ISSUE THREAD

**Issue by raghunandy** [hierynomus/sshj#23]
hi 

I'm trying to upload a file to a sftp server using private key authentication. please provide one example for this. I searched for so long , I could't be able to find any help;

thanks
raghu

**Comment by jgoldverg** [comment]
Hello I have been trying to use a private RSA key to authenticate the SSHClient class for an SFTP file transfer but have been unable to find the proper authentication method. I currently have my private key stored as a key. Any suggestion would be great.
