### ISSUE TITLE
Can't work with stdin of an executed command

### ISSUE THREAD

**Issue by mateuyabar** [hierynomus/sshj#233]
Let's say I have the following script that I want to execute trough sshj
```bash
read -p "Say y or n" yn
    case $yn in
        [Yy]* ) echo "YES";;
        [Nn]* ) echo "No";;
        * ) echo "Please answer yes or no.";;
esac
```
I use the follwoing
```java
Session.Command cmd = session.exec("./temp/input.sh");
InputStream instream = new ByteArrayInputStream("y".getBytes(StandardCharsets.UTF_8));
IOUtils.copy(instream, session.getOutputStream());
cmd.join(10, TimeUnit.SECONDS);
```
I allways get a:
Exception in thread "main" net.schmizz.sshj.connection.ConnectionException: Timeout expired
As if the "y" was not beeing send.
What is the problem?

Thanks

**Comment by hierynomus** [comment]
Does it work when you add a line terminator to the `y\n`?

**Comment by mateuyabar** [comment]
No, same problem.

**Comment by hierynomus** [comment]
And did you flush the outputstream?

**Comment by mateuyabar** [comment]
That did it:
\n + flush.
I had tried both of them but separatelly.
Thanks!
