### ISSUE TITLE
sshj can't run with java 6

### ISSUE THREAD

**Issue by sblond** [hierynomus/sshj#234]
Hi,

I get `java.lang.UnsupportedClassVersionError: net/i2p/crypto/eddsa/spec/EdDSAParameterSpec : Unsupported major.minor version 51.0` when using sshj 0.15.0 with java 6. Usually this error means that a class has been compiled with java 7 compatibility but run with an older java.

This may be related to the fix of #171 that adds a new dependency to net.vrallev.ecc:ecc-25519-java:1.0.1. This dependency seems to require the use of java 7 https://github.com/vRallev/ECC-25519/blob/master/ECC-25519-Java/build.gradle.

Does it mean that java 6 compatibility is dropped?

**Comment by hierynomus** [comment]
Hi Stephane,

Thanks for pointing that out. Hadn't actually noticed that!
I am somewhat inclined to then maybe indeed drop java6 support for new versions. Or to make ecc-25519 an optional dependency, and checking in the code whether it can be added or not.
What would be the preference?

**Comment by dkocher** [comment]
+1 to drop Java 6 support.

**Comment by sblond** [comment]
I have to deal with java 6, so
+1 to keep java 6 support

**Comment by hierynomus** [comment]
I cannot easily make ecc-25519 optional, as it is used directly in the `KeyType` enum, so I cannot optionally load it. So I am dropping java6 support, sorry.

**Comment by hierynomus** [comment]
@sblond We've been able to add Java6 support back to the mix.

**Comment by sblond** [comment]
Hi,
I upgraded to 0.18.0 and it worked fine.
Thanks!
