### ISSUE TITLE
Exhausted available authentication methods occurs while connecting to an ec2 instance

### ISSUE THREAD

**Issue by berrytchaks** [hierynomus/sshj#245]
Hi everybody,

I'm trying to use sshj to connect an ec2 instance. Here what I want to do connect to my ec2 instance without using the key pair. So I had done the following configurations.
I have a user X that can do a ssh ubuntu@publicIpEc2 not ssh -i myKeyPair.pem ubuntu@publicIpEc2.
ssh ubuntu@publicIpEc2  is possible without the key pair because I have added the rsa key of the user issuing the command "ssh ubuntu@publicIpEc2" in the authorized_keys of the user ubuntu of my ec2 instance.
So with the same configuration still in place, I now want to ssh my ec2 instance with sshj. 

I wrote the following code 

      public class SSHCommandExecutor {
       public static void main(String[] args) throws IOException {
    	
         final SSHClient ssh = new SSHClient();
         ssh.addHostKeyVerifier(new NullHostKeyVerifier());
          ssh.connect("publicIpEc2");
          ssh.authPassword("ubuntu","");
            net.schmizz.sshj.connection.channel.direct.Session session;
				session = ssh.startSession();
            try {
                final Command cmd = session
                        .exec("ls -al");
                System.out.println(IOUtils.readFully(cmd.getInputStream())
                        .toString());
                cmd.join(5, TimeUnit.SECONDS);
                System.out.println("\n** exit status: " + cmd.getExitStatus());
            } finally {
                session.close();
            }
      }

       public class NullHostKeyVerifier implements HostKeyVerifier  {
	        @Override
	         public boolean verify(String arg0, int arg1, PublicKey arg2) {
	                  return true;
	          }   
           }

Knowing that the user running the above is the same that could do a ssh ubuntu@publicIpEc2 and connect to the ec2 instance without any problem, I thought that this would have also works as well.
But I have the following exception stack trace . 
Exception in thread "main" net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:217)
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:193)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:278)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:248)
	at net.schmizz.sshj.SSHClient.authPassword(SSHClient.java:232)
	at testflink.deploy.SSHCommandExecutor.main(SSHCommandExecutor.java:35)
122008 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - {}
net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
	at net.schmizz.sshj.transport.Reader.run(Reader.java:70) ~[sshj-0.9.0.jar:na]
122008 [reader] INFO  net.schmizz.sshj.transport.TransportImpl - Disconnected - UNKNOWN

NB : On ubuntu ec2 instance the user ubuntu is the default user and has no password that is while I set the password as an empty string ("")
Please what I'm missing?
Thanks.

**Comment by hierynomus** [comment]
Hi,

Instead of ssh.authPassword, you should be using ssh.authPublicKey. You've
added you rsa key to the authorized_keys, which means you're still doing
public key auth, and not password auth.

Hope that helps!

Regards, Jeroen

Op za 16 apr. 2016 23:55 schreef berrytchaks <notifications@github.com>:

**Comment by hierynomus** [comment]
Hi @berrytchaks, did my previous comment solve your issue? If not could you please comment and post the entire debug log?

**Comment by hierynomus** [comment]
@berrytchaks Any update on this?

**Comment by berrytchaks** [comment]
Hi @hierynomus sorry for the delay, but I was really very busy. I was able to get it work by using.

     ssh.authPassword("ubuntu",USER_HOME_PATH +"/"+user+"/.ssh/id_rsa");

where USER_HOME_PATH +"/"+user+"/.ssh/id_rsa" is the path of the id_rsa file of the user who is running the script.

Help this helps

**Comment by hierynomus** [comment]
I think you mean `authPublicKey` instead of `authPassword`, unless your password actually is the location of the id_rsa file :)

**Comment by JMVM** [comment]
If using authPublicKey, ensure remote machine has your key as **authorized_keys**
