### ISSUE TITLE
Allow mocking of SCPUploadClient and SCPDownloadClient

### ISSUE THREAD

**Issue by joprsal** [hierynomus/sshj#247]
Currently, there is no way of mocking the two final classes using Mockito (because [Mockito cannot mock final classes](https://github.com/mockito/mockito/wiki/FAQ#what-are-the-limitations-of-mockito)).

One solution would be to extract and use interfaces rather than final classes.

**Comment by hierynomus** [comment]
This is fixed with PR #250
