### ISSUE TITLE
net.schmizz.sshj.sftp.FileAttributes.toString mistake in writing

### ISSUE THREAD

**Issue by guoxp11** [hierynomus/sshj#258]
if (has(Flag.UIDGID))
            sb.append("uid=").append(**size**).append(",gid=").append(gid).append(";");

should be changed to:

if (has(Flag.UIDGID))
            sb.append("uid=").append(**uid**).append(",gid=").append(gid).append(";");

**Comment by hierynomus** [comment]
Yes, that makes more sense indeed. Thanks!

Op 31 jul. 2016 6:16 a.m. schreef "guoxp11" <notifications@github.com>:
