### ISSUE TITLE
Support diffie-hellman?

### ISSUE THREAD

**Issue by luo201227** [hierynomus/sshj#259]
key exchange Support diffie-hellman?

**Comment by hierynomus** [comment]
Can you give me a pointer to the rfc? I thought I had all the kex protocols
implemented.

Op 5 aug. 2016 11:40 schreef "Joyce.Luo" <notifications@github.com>:

**Comment by luo201227** [comment]
@hierynomus
 Reference address [http://www.faqs.org/rfcs/rfc2631.html](url)

**Comment by hierynomus** [comment]
Are you sure this one isn't already implemented? What is the exact kex
protocol name that the ssh server is negotiating that is not supported
currently?

Op 5 aug. 2016 2:14 p.m. schreef "Joyce.Luo" <notifications@github.com>:

**Comment by luo201227** [comment]
SSH connection switch has been resolved! Thank you for your efforts and resources sharing
@hierynomus
