### ISSUE TITLE
Example for authPassword?

### ISSUE THREAD

**Issue by leolux** [hierynomus/sshj#260]
Hi!
I am new to this API and I am looking for a starting point example that shows how to authenticatice by username and password and how to execute 2 commands in a sequence. But  I couldn't find any example for this. So I like to ask where to read on?

The only example using the authPassword() method is KeepAlive. Did I miss other places of examples?

**Comment by hierynomus** [comment]
You haven't, but authPassword is no different from authPublicKey. So the
Exec.java example is all you should need where you can replace the call to
authPublicKey with authPassword.

Op 7 aug. 2016 6:35 p.m. schreef "leolux" <notifications@github.com>:

**Comment by leolux** [comment]
Ok, thanks!
