### ISSUE TITLE
Multiple command execution

### ISSUE THREAD

**Issue by luo201227** [hierynomus/sshj#261]
How to execute two or more commands in a connection?
[https://github.com/hierynomus/sshj/issues/204](url)

**Comment by hierynomus** [comment]
Can you describe why the suggestions in #204 do not help you? You can either concatenate the commands (using the shell's `&&` or `;`), or use the interactive Shell that allows you to execute multiple commands one after the other like you were using a regular shell on the system.

**Comment by luo201227** [comment]
Thanks for reply!
The problem has been solved successfully!
@hierynomus
