### ISSUE TITLE
Support new OpenSSH private key format (Used by default with Ed25519 keys)

### ISSUE THREAD

**Issue by dkocher** [hierynomus/sshj#276]

**Comment by hierynomus** [comment]
@dkocher I think we already do: https://github.com/hierynomus/sshj/blob/master/src/main/java/com/hierynomus/sshj/signature/Ed25519PublicKey.java

**Comment by hierynomus** [comment]
and https://github.com/hierynomus/sshj/blob/master/src/main/java/net/schmizz/sshj/common/KeyType.java#L179

**Comment by dkocher** [comment]
When I create a key with OpenSSH running `ssh-keygen -t ed25519` the file header is 
`-----BEGIN OPENSSH PRIVATE KEY-----` which is no where handled in any of the `FileKeyProvider`.

**Comment by hierynomus** [comment]
Ok, I'll have a look next week :)

2016-10-14 13:04 GMT+02:00 David Kocher <notifications@github.com>:

**Comment by dkocher** [comment]
>      -o      Causes ssh-keygen to save private keys using the new OpenSSH format rather than the more compatible PEM format.  The new format has increased resistance to brute-force pass-
             word cracking but is not supported by versions of OpenSSH prior to 6.5.  Ed25519 keys always use the new private key format.

**Comment by hierynomus** [comment]
Thanks, though we can read files with that header, see: https://github.com/hierynomus/sshj/blob/master/src/test/java/net/schmizz/sshj/keyprovider/OpenSSHKeyFileTest.java#L144

And I do remember testing with a host with only an ed25519 key. I'll need to re-verify

**Comment by dkocher** [comment]
Calling `#getPrivate()` on the key file will result in `unrecognised object: OPENSSH PRIVATE KEY`.

**Comment by hierynomus** [comment]
Ok, will fix :)

2016-10-14 13:47 GMT+02:00 David Kocher <notifications@github.com>:

**Comment by dkocher** [comment]
@hierynomus Do you already have an ETA for this?

**Comment by hierynomus** [comment]
Will try to get it done this week...

**Comment by dkocher** [comment]
@hierynomus Awesome.

**Comment by hierynomus** [comment]
Just had a quick look into this... We typically rely on BouncyCastle to read the keys, and guess what, it does not support this format (yet)...

**Comment by dkocher** [comment]
@hierynomus Have you found any spec on the file format?

**Comment by hierynomus** [comment]
I think I can work it out using these links:

The commit responsible for the new change is http://marc.info/?l=openbsd-cvs&m=138633690918227&w=2.
PROTOCOL description https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.key.
General information http://www.tedunangst.com/flak/post/new-openssh-key-format-and-bcrypt-pbkdf

If you find more info, feel free to add!

**Comment by hierynomus** [comment]
Started work on https://github.com/hierynomus/sshj/tree/issue-276

**Comment by dkocher** [comment]
I would like to have this issue reopend. Reading SSH keys of type RSA in the new format does not work.

The failure is a message like `Bad item length: -1512035316` which is caused from reading the key in [OpenSSHKeyV1KeyFile](https://github.com/hierynomus/sshj/blob/master/src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyV1KeyFile.java#L193).

This is as of [OpenSSH 7.8](https://www.openssh.com/releasenotes.html) the default.

> * ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format. The OpenSSH format,
   supported in OpenSSH releases since 2014 and described in the
   PROTOCOL.key file in the source distribution, offers substantially
   better protection against offline password guessing and supports
   key comments in private keys. If necessary, it is possible to write
   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
   when generating or updating a key.

Workaround is to use `ssh-keygen -m PEM`.

**Comment by hierynomus** [comment]
Reopened... Let's fix that :)
