### ISSUE TITLE
Instantiating SSHClient getting pretty slow (minutes!) under race condition

### ISSUE THREAD

**Issue by bence-takacs** [hierynomus/sshj#278]
Using SSHJ concurrently causes a race condition:

> 		final long in = System.currentTimeMillis();
> 		final SSHClient ssh = new SSHClient();
> 		LOG.debug(String.format("-- INSTANTIATE CLIENT (in %s)", DateTimeUtils.timeDiffToString(System.currentTimeMillis()-in)) );

Output:

> 2016-10-24 16:38:40,886 DEBUG [serverStatusCheck1       ] c.s.m.s.c.RemoteSshRunner: -- INSTANTIATE CLIENT (in 0 00:04:07.101)
Yes: 4 minutes :-)

And then everything else is done in 3-4 seconds: 
> ssh.loadKnownHosts();
> ssh.connect(remotehost);
> ssh.authPublickey(remoteUserName, ...);
> ssh.setTimeout(TIMEOUT);
> final Session session = ssh.startSession();
> ...

Server: CentOS 6
Scenario: multiple connections to the same machine. Actually multiple scheduled jobs (on 5 executor threads) running SSH commands against a single machine.

**Comment by hierynomus** [comment]
I suspect your system is low on entropy (randomness). Are you running on a virtual machine?
There is no race condition code in the constructor that I'm aware of, but we _do_ create a new SecureRandom instance, which will need a bit of entropy from your system.

**Comment by bence-takacs** [comment]
Yes: Virtual Machine
And I get an error message about low entrophy also 😊 

So how could I solve that?
Under those circumstances: VMware VM, Centos 6, Java 8
Is there a direct way or what about reusing/ pooling SshClient instances?

**Comment by hierynomus** [comment]
You can re-use an SshClient, but you could also more simply instantiate it with a singleton Configuration object. i.e.

```
Config c = new DefaultConfig();
while (true) {
  SSHClient ssh = new SSHClient(c);
}
```

**Comment by bence-takacs** [comment]
So re-using the DefaultConfiguration itself :-)
Simple and nice

and working:

> -- INSTANTIATE CLIENT (in 0 00:00:00.000)


By the way: isn't it a java problem? Under specific circumstances it takes **minutes** to generate a random number? And it blocks the calling thread up to this time.

**Comment by hierynomus** [comment]
Actually it is not really a Java problem, but a linux device issue. The Java PRNG tries to read `/dev/random`, which is a blocking operation is the system does not have enough entropy gathered. VMs are very notorious in this, as they typically do not have much 'user interaction', which is one of the things that acquires randomness for the system.

**Comment by hierynomus** [comment]
A trick which also works is: `ln -s -f /dev/urandom /dev/random`, but be aware of the consequences of this (google is your friend)

**Comment by bence-takacs** [comment]
Thanks!

**Comment by hierynomus** [comment]
I think your system is low on entropy. Are you running on a virtual
machine?

Op 24 okt. 2016 4:56 p.m. schreef "bence-takacs" <notifications@github.com>:

**Comment by bence-takacs** [comment]
Yes: Virtual Machine
And I get an error message about low entrophy also 😊

So how could I solve that?
Under those circumstances
Reusing/ pooling SshClient instances?


Jeroen van Erp <notifications@github.com> ezt írta (2016. október 25.,
kedd):
