### ISSUE TITLE
Release for the OpenSSH key format commit?

### ISSUE THREAD

**Issue by godenji** [hierynomus/sshj#282]
Hi, thanks for sshj.

In [this commit](https://github.com/hierynomus/sshj/commit/bf34072c3aa94911288e09f7159a04f16fb0dca0) support for the new openssh key format was introduced. Unfortunately 0.18.0, released end of September, does not include it.

Recently upgraded keys and now sshj blows up with `UserAuthException: Problem getting private key from PKCS8KeyFile`. Am able to ssh just fine into target servers with new openssh based keys.

**Comment by hierynomus** [comment]
I will make that release this week. Keep in mind that currently the new key
format only works with ed25519 keys. I need to split the format from the
key type still.

Op 23 nov. 2016 07:20 schreef "N.S. Cutler" <notifications@github.com>:

**Comment by godenji** [comment]
Perfect, using ed25519 here.

Thanks

**Comment by hierynomus** [comment]
Was released last Friday :)

**Comment by godenji** [comment]
Great, will give it a shot, thanks @hierynomus
