### ISSUE TITLE
An Exception may cause SSHPacket's wpos & rpos problem

### ISSUE THREAD

**Issue by gatesking** [hierynomus/sshj#286]
HI,
I don't know if this is a bug:
In ChannelOutputStream.flush,
```
                if (leftOverBytes > 0) {
                    leftOvers.putRawBytes(packet.array(), packet.wpos(), leftOverBytes);
                }

                trans.write(packet);
                win.consume(writeNow);

                packet.rpos(headerOffset);
                packet.wpos(dataOffset);
```
When trans.write(packet) throws an exception, packet.rpos&wpos will not be set to the right point. If more data write to the SSHPakcet, they will all failed by java.lang.ArrayIndexOutOfBoundsException in Buffer.putRawBytes() because the wpos is not right. I've no idea if it is a bug? Or you just want to close the ssh session when trans.write has an exception and not to use it any more.
Could you give me any suggustion? Thanks!

**Comment by hierynomus** [comment]
Hi @gatesking,

Have you seen this in production? Or Is this just a question?

**Comment by gatesking** [comment]
Hi,@hierynomus
Seen it in production. 
The problem comes from an ip conflict, after I fixed the ip conflict problem(Close one of linux server who has the same ip), the keepalive thread still doesn't detect the ip conflict and worked OK, but flush operation failed because of it, so the application I wrote doesn't rebuild the ssh connection and still use it (My application will try to rebuild the connection when disconnect listener notify me a disconnect event.). As a result, the later ssh message all failed in java.lang.ArrayIndexOutOfBoundsException, as I said before, ssh packet's wpos and rpos were not at the right place. 
Maybe I should rebuild the connection when meeting write or flush failed? Or could you give me some more suggustions? 
Thanks!

**Comment by gatesking** [comment]
I am so sorry that I made a mistake in my application, it missed a disconnect event from Reader Thread. And the keepalive thread doesn't work because of Reader Thread is stopped. After I fixed this bug, it works well.
But I still want to know how to deal with an write or flush failed? Do you think that the ssh connection can not be used now and should be rebuilt?
Thanks!

**Comment by hierynomus** [comment]
I would say that a `transport.write(...)` failure is a terminal one, as you have no clue whether this is recoverable or not. So I would definitely say that the connection needs rebuilding.

**Comment by gatesking** [comment]
OK, Thank you very much!
