### ISSUE TITLE
Putty keys with passphrase don't work properly

### ISSUE THREAD

**Issue by notepass** [hierynomus/sshj#287]
When trying to use an putty-key file with a passphrase, the authentification will fail with the execption "net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile@15fc442" (Error from 0.17.2)
Additionaly, when trying to build the current release (0.19.0) some seemingly related tests will fail:

> net.schmizz.sshj.keyprovider.PuTTYKeyFileTest > testCorrectPassphraseDsa FAILED
>   java.io.IOException: Illegal key size
>       at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.decrypt(PuTTYKeyFile.java:296)
>        at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.parseKeyPair(PuTTYKeyFile.java:197)
>        at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.readKeyPair(PuTTYKeyFile.java:102)
>        at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPrivate(BaseFileKeyProvider.java:75)
>        at net.schmizz.sshj.keyprovider.PuTTYKeyFileTest.testCorrectPassphraseDsa(PuTTYKeyFileTest.java:213)
>
>        Caused by:
>        java.security.InvalidKeyException: Illegal key size
>            at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
>            at javax.crypto.Cipher.implInit(Cipher.java:805)
>            at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
>            at javax.crypto.Cipher.init(Cipher.java:1396)
>            at javax.crypto.Cipher.init(Cipher.java:1327)
>            at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.decrypt(PuTTYKeyFile.java:292)
>            ... 4 more
>
> net.schmizz.sshj.keyprovider.PuTTYKeyFileTest > testCorrectPassphraseRsa FAILED
>    java.io.IOException: Illegal key size
>        at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.decrypt(PuTTYKeyFile.java:296)
>        at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.parseKeyPair(PuTTYKeyFile.java:197)
>        at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.readKeyPair(PuTTYKeyFile.java:102)
>        at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPrivate(BaseFileKeyProvider.java:75)
>        at net.schmizz.sshj.keyprovider.PuTTYKeyFileTest.testCorrectPassphraseRsa(PuTTYKeyFileTest.java:174)
>
>        Caused by:
>        java.security.InvalidKeyException: Illegal key size
>            at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
>            at javax.crypto.Cipher.implInit(Cipher.java:805)
>            at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
>            at javax.crypto.Cipher.init(Cipher.java:1396)
>            at javax.crypto.Cipher.init(Cipher.java:1327)
>            at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.decrypt(PuTTYKeyFile.java:292)
>            ... 4 more
> ✘ Test net.schmizz.sshj.keyprovider.PuTTYKeyFileTest; Executed: 6/4/2

**Comment by dkocher** [comment]
The test failures are because you don't have the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files installed.

**Comment by notepass** [comment]
Well, you learn something new everyday :D
Thanks for the info. It works now.
