### ISSUE TITLE
LocalPortForwarder - how to detect errors with target server/socket

### ISSUE THREAD

**Issue by dazed19** [hierynomus/sshj#297]
Hi

I'd like to be able to detect if the the server:port fronted by a LocalPortForwarder is still contactable by using a heartbeat mechanism before a client app uses the port and hits an error.

I don't see a way to get access to the socket "connected" to the target from the LocalPortForwarder interface - is there an approved way of doing this?

Thanks
Dave

**Comment by hierynomus** [comment]
Hi Dave,
No there is currently no way to ensure that.

**Comment by dazed19** [comment]
Hi
Thanks - having thought about it I'm not entirely sure I need access to the PortForwarders socket - it's the health of underlying client session (overwhich the portforwarder operates) that I'm really interested in - so not a problem for me.
