### ISSUE TITLE
Question: What does cmd.join actually do?

### ISSUE THREAD

**Issue by forresthopkinsa** [hierynomus/sshj#298]
It's in the Exec example, but neither the example nor the Javadoc offer any explanation as to what it's actually doing. Can anyone elaborate? Thanks.

**Comment by hierynomus** [comment]
It ensures that your code waits for the `Command` to finish, before continuing, without actually closing the command yourself. This is similar to how `Thread.join()` works. It created a so-called _join-point_ for your code and the asynchronously executing code.

Hope that helps.

**Comment by forresthopkinsa** [comment]
got it. thanks
