### ISSUE TITLE
Accessing a file after put

### ISSUE THREAD

**Issue by NickPapagiorgio** [hierynomus/sshj#299]
i am sending files to another server using SFTPClient and put(). The server runs a script which looks for new files and moves them to another directory as soon as the file is not in use anymore. every now and then I receive the folloeing exception:

> 2017-02-01 13:42:06,805 DEBUG net.schmizz.sshj.common.StreamCopier.copy():141    126,858.4 KiB transferred in 30.7 seconds (4,132.06 KiB/s)
> 2017-02-01 13:42:06,805 DEBUG net.schmizz.sshj.sftp.RemoteResource.close():53    Closing `RemoteResource{/aaa/in5qsa/INCOMING/QSBigfile/BISCCM_DatenCCM3_22738312359669_0020289663_809001200_200_0000001445_20150526_030024.zip_suffixregresst}`
> 2017-02-01 13:42:06,805 DEBUG net.schmizz.sshj.sftp.SFTPEngine.request():127     Sending Request{3972;CLOSE}
> 2017-02-01 13:42:06,805 TRACE net.schmizz.sshj.transport.Encoder.encode():79     Encoding packet #4268: 5e 00 00 00 00 00 00 00 11 00 00 00 0d 04 00 00 0f 84 00 00 00 04 00 00 00 00
> 2017-02-01 13:42:06,806 DEBUG chmizz.sshj.connection.channel.Window.consume():61 Consuming by 17 down to 2004142
> 2017-02-01 13:42:06,806 DEBUG net.schmizz.concurrent.Promise.tryRetrieve():165   Awaiting <<sftp / 3972>>
> 2017-02-01 13:42:06,806 TRACE net.schmizz.sshj.transport.Decoder.decode():102    Received packet #5320: 5e 00 00 00 04 00 00 00 1c 00 00 00 18 65 00 00 0f 84 00 00 00 00 00 00 00 07 53 75 63 63 65 73 73 00 00 00 00
> 2017-02-01 13:42:06,806 TRACE .schmizz.sshj.transport.TransportImpl.handle():487 Received packet CHANNEL_DATA
> 2017-02-01 13:42:06,806 TRACE nnection.channel.AbstractChannel.receiveInto():354 IN #4: 00 00 00 18 65 00 00 0f 84 00 00 00 00 00 00 00 07 53 75 63 63 65 73 73 00 00 00 00
> 2017-02-01 13:42:06,806 DEBUG chmizz.sshj.connection.channel.Window.consume():61 Consuming by 28 down to 1985783
> 2017-02-01 13:42:06,806 DEBUG net.schmizz.sshj.sftp.PacketReader.handle():100    Received STATUS packet
> 2017-02-01 13:42:06,806 DEBUG net.schmizz.concurrent.Promise.deliver():79        Setting <<sftp / 3972>> to `Buffer [rpos=5, wpos=24, size=24]`
> 2017-02-01 13:42:06,807 DEBUG net.schmizz.sshj.sftp.SFTPEngine.request():127     Sending Request{3973;SETSTAT}
> 2017-02-01 13:42:06,807 TRACE net.schmizz.sshj.transport.Encoder.encode():79     Encoding packet #4269: 5e 00 00 00 00 00 00 00 a2 00 00 00 9e 09 00 00 0f 85 00 00 00 85 2f 61 61 61 2f 69 6e 35 71 73 61 2f 49 4e 43 4f 4d 49 4e 47 2f 51 53 42 69 67 66 69 6c 65 2f 42 49 53 43 43 4d 5f 44 61 74 65 6e 43 43 4d 33 5f 32 32 37 33 38 33 31 32 33 35 39 36 36 39 5f 30 30 32 30 32 38 39 36 36 33 5f 38 30 39 30 30 31 32 30 30 5f 32 30 30 5f 30 30 30 30 30 30 31 34 34 35 5f 32 30 31 35 30 35 32 36 5f 30 33 30 30 32 34 2e 7a 69 70 5f 73 75 66 66 69 78 72 65 67 72 65 73 73 74 00 00 00 0c 00 00 01 a4 58 91 d7 9e 58 91 d7 7f
> 2017-02-01 13:42:06,807 DEBUG chmizz.sshj.connection.channel.Window.consume():61 Consuming by 162 down to 2003980
> 2017-02-01 13:42:06,807 DEBUG net.schmizz.concurrent.Promise.tryRetrieve():165   Awaiting <<sftp / 3973>>
> 2017-02-01 13:42:06,807 TRACE net.schmizz.sshj.transport.Decoder.decode():102    Received packet #5321: 5e 00 00 00 04 00 00 00 21 00 00 00 1d 65 00 00 0f 85 00 00 00 02 00 00 00 0c 4e 6f 20 73 75 63 68 20 66 69 6c 65 00 00 00 00
> 2017-02-01 13:42:06,807 TRACE .schmizz.sshj.transport.TransportImpl.handle():487 Received packet CHANNEL_DATA
> 2017-02-01 13:42:06,807 TRACE nnection.channel.AbstractChannel.receiveInto():354 IN #4: 00 00 00 1d 65 00 00 0f 85 00 00 00 02 00 00 00 0c 4e 6f 20 73 75 63 68 20 66 69 6c 65 00 00 00 00
> 2017-02-01 13:42:06,807 DEBUG chmizz.sshj.connection.channel.Window.consume():61 Consuming by 33 down to 1985750
> 2017-02-01 13:42:06,808 DEBUG net.schmizz.sshj.sftp.PacketReader.handle():100    Received STATUS packet
> 2017-02-01 13:42:06,808 DEBUG net.schmizz.concurrent.Promise.deliver():79        Setting <<sftp / 3973>> to `Buffer [rpos=5, wpos=29, size=29]`
> 2017-02-01 13:42:06,808 DEBUG connection.channel.AbstractChannel.sendClose():275 Sending close
> 2017-02-01 13:42:06,808 TRACE net.schmizz.sshj.transport.Encoder.encode():79     Encoding packet #4270: 61 00 00 00 00
> 2017-02-01 13:42:06,808 DEBUG net.schmizz.concurrent.Promise.tryRetrieve():165   Awaiting <<chan#4 / close>>
> 2017-02-01 13:42:06,809 TRACE net.schmizz.sshj.transport.Decoder.decode():102    Received packet #5322: 62 00 00 00 04 00 00 00 0b 65 78 69 74 2d 73 74 61 74 75 73 00 00 00 00 00
> 2017-02-01 13:42:06,809 TRACE .schmizz.sshj.transport.TransportImpl.handle():487 Received packet CHANNEL_REQUEST
> 2017-02-01 13:42:06,809 DEBUG on.channel.AbstractChannel.gotChannelRequest():303 Got chan request for `exit-status`
> 2017-02-01 13:42:06,809 TRACE net.schmizz.sshj.transport.Decoder.decode():102    Received packet #5323: 61 00 00 00 04
> 2017-02-01 13:42:06,809 TRACE .schmizz.sshj.transport.TransportImpl.handle():487 Received packet CHANNEL_CLOSE
> 2017-02-01 13:42:06,809 DEBUG .connection.channel.AbstractChannel.gotClose():208 Got close
> 2017-02-01 13:42:06,810 DEBUG schmizz.sshj.connection.ConnectionImpl.forget():89 Forgetting `session` channel (#4)
> 2017-02-01 13:42:06,810 DEBUG net.schmizz.concurrent.Promise.deliver():79        Setting <<chan#4 / close>> to `SOME`
> 2017-02-01 13:42:06,811  INFO shj.transport.TransportImpl.notifyDisconnect():182 Disconnected - BY_APPLICATION
> 2017-02-01 13:42:06,811 DEBUG net.schmizz.sshj.AbstractService.notifyError():57  Notified of net.schmizz.sshj.transport.TransportException: [BY_APPLICATION] Disconnected
> 2017-02-01 13:42:06,813 DEBUG .sshj.transport.TransportImpl.sendDisconnect():456 Sending SSH_MSG_DISCONNECT: reason=[BY_APPLICATION], msg=[]
> 2017-02-01 13:42:06,813 TRACE net.schmizz.sshj.transport.Encoder.encode():79     Encoding packet #4271: 01 00 00 00 0b 00 00 00 00 00 00 00 00
> 2017-02-01 13:42:06,814 DEBUG net.schmizz.concurrent.Promise.deliver():79        Setting <<transport close>> to `SOME`
> 2017-02-01 13:42:06,814 DEBUG net.schmizz.sshj.transport.Reader.run():72         Stopping
> net.schmizz.sshj.sftp.SFTPException: No such file
> 	at net.schmizz.sshj.sftp.Response.error(Response.java:136)
> 	at net.schmizz.sshj.sftp.Response.ensureStatusIs(Response.java:129)
> 	at net.schmizz.sshj.sftp.Response.ensureStatusPacketIsOK(Response.java:122)
> 	at net.schmizz.sshj.sftp.SFTPEngine.setAttributes(SFTPEngine.java:167)
> 	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.setAttributes(SFTPFileTransfer.java:213)
> 	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.upload(SFTPFileTransfer.java:190)
> 	at net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.access$100(SFTPFileTransfer.java:169)
> 	at net.schmizz.sshj.sftp.SFTPFileTransfer.upload(SFTPFileTransfer.java:65)
> 	at net.schmizz.sshj.sftp.SFTPClient.put(SFTPClient.java:245)

It looks like sshj has copied the file completely, the scripts moves the file and sshj wants to set the attributes. 
Would it be possible for sshj to keep the file open after sending it so the script sees that it cannot yet move the file?
As a workaround I have called setPreserveAttributes(false).

**Comment by hierynomus** [comment]
Hi Nick,

I don't think so, the OS won't like the file being in use and calling setAttributes(). 
What I would suggest is (if you want `preserveAttributes`) is:

first put the file as `<file>.donotmove`, and then do an `sftpClient.rename(<file>.donotmove, <file>)`. And make your script not touch files that are called `.donotmove`

**Comment by NickPapagiorgio** [comment]
Ok, I will try that
