### ISSUE TITLE
TransportException: Unable to reach a settlement: [diffie-hellman-group1-sha1, diffie-hellman-group-exchange-sha1] and [curve25519-sha256@libssh.org, diffie-hellman-group-exchange-sha256]

### ISSUE THREAD

**Issue by MarcelBeining** [hierynomus/sshj#303]
Hi there,
I am trying to connect to our server which uses the diffie-hellman-group-exchange-sha256 method, but I get the error, shown below. I have the very latest version of sshj so the dh-gex-sha256 method is within the build, however it does not seem to be found for the matching. Any ideas what's wrong?

Best
Marcel

> net.schmizz.sshj.transport.TransportException: Unable to reach a settlement: [diffie-hellman-group1-sha1, diffie-hellman-group-exchange-sha1] and [curve25519-sha256@libssh.org, diffie-hellman-group-exchange-sha256]
> 
> 	at net.schmizz.sshj.transport.Proposal.firstMatch(Proposal.java:145)
> 
> 	at net.schmizz.sshj.transport.Proposal.negotiate(Proposal.java:128)
> 
> 	at net.schmizz.sshj.transport.KeyExchanger.gotKexInit(KeyExchanger.java:218)
> 
> 	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:350)
> 
> 	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
> 
> 	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
> 
> 	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
> 
> 	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

**Comment by hierynomus** [comment]
Hi Marcel,

There are 2 possibilities:

1. Have you loaded the unlimited strength java cryptography extensions? If not, then you cannot use anything higher than sha1 encryption. However given the specific combination of KEX algorithms I don't think that is the current problem
2. Do you have BouncyCastle on the classpath? This specific combination of KEX algorithms is loaded as fallback when BC is not available.

**Comment by MarcelBeining** [comment]
Thank you! Yes it was actually the missing BouncyCastle! Works now =)
