### ISSUE TITLE
...Window.Remote.awaitExpansion Deadlock

### ISSUE THREAD

**Issue by lukelast** [hierynomus/sshj#313]
Version: 0.20.0
OS: amazon linux 2016.09
Remote client: CentOS7

I've run into a deadlock a few times while SCPing a large file when the network connection fails. Looking at the code below there is no way to return from `awaitExpansion` unless a message is received from the remote end to increase the window size. If the remote end never sends `Message.CHANNEL_WINDOW_ADJUST` for whatever reason then it will be stuck forever.

https://github.com/hierynomus/sshj/blob/master/src/main/java/net/schmizz/sshj/connection/channel/Window.java#L80

Also trying to close the connection doesn't help because `net.schmizz.sshj.connection.channel.ChannelOutputStream.close()` calls flush which blocks on `awaitExpansion`

**Comment by hierynomus** [comment]
@lukelast Do you have some reproduction scenario. I think it is solvable, but I need to have a careful look at this.

**Comment by lukelast** [comment]
@hierynomus I put together a snippet of code that reproduces the issue for me. Something interesting I noticed while testing this is that if I do NOT enable the `useCompression()` option then I can't reproduce the deadlock. That is good news for me because I can disable compression in production and hopefully hit this issue less or not at all.

The steps to reproduce are to run the below code and while it is uploading disconnect the network connection. I was able to reproduce by pulling out my ethernet cable or disabling my network adapter in the OS. It only has to be disconnected for a few seconds.

Also make sure your network connection is slow enough or the data buffer is large enough that the upload takes long enough to give you a chance to pull the plug.

```java
SSHClient ssh = new SSHClient();
ssh.addHostKeyVerifier( new PromiscuousVerifier() );
ssh.useCompression(); // IMPORTANT!
ssh.connect( SSH_HOST );
auth( ssh );

final byte[] data = new byte[1024 * 1024 * 128];
ssh.newSCPFileTransfer().newSCPUploadClient().copy( 
    new InMemorySourceFile() {

         @Override
         public String getName() {
            return "test.dat";
         }

         @Override
         public long getLength() {
            return data.length;
         }

         @Override
         public InputStream getInputStream() throws IOException {
            System.out.println( "Starting to copy data" );
            return new ByteArrayInputStream( data );
         }
}, "/tmp/test.dat", EscapeMode.Space );
```

Many thanks for looking into the issue!

**Comment by hierynomus** [comment]
Thanks for that reproduction scenario! Will definitely look into this.
