### ISSUE TITLE
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by storytime** [hierynomus/sshj#335]
Versions: the latest form maven central.

Case:
1. I have lib that contains sshj.
2. This lib includes to spring-boot app.
3. When I try to run runnable jar I see this error: 

====
tests_1     | Error: A JNI error has occurred, please check your installation and try again
tests_1     | Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
tests_1     |   at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
tests_1     |   at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
tests_1     |   at java.util.jar.JarVerifier.processEntry(JarVerifier.java:273)
tests_1     |   at java.util.jar.JarVerifier.update(JarVerifier.java:228)
tests_1     |   at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
tests_1     |   at java.util.jar.JarFile.getInputStream(JarFile.java:450)
tests_1     |   at sun.misc.JarIndex.getJarIndex(JarIndex.java:137)
tests_1     |   at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:839)
tests_1     |   at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:831)
tests_1     |   at java.security.AccessController.doPrivileged(Native Method)
tests_1     |   at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:830)
tests_1     |   at sun.misc.URLClassPath$JarLoader.<init>(URLClassPath.java:803)
tests_1     |   at sun.misc.URLClassPath$3.run(URLClassPath.java:530)
tests_1     |   at sun.misc.URLClassPath$3.run(URLClassPath.java:520)
tests_1     |   at java.security.AccessController.doPrivileged(Native Method)
tests_1     |   at sun.misc.URLClassPath.getLoader(URLClassPath.java:519)
tests_1     |   at sun.misc.URLClassPath.getLoader(URLClassPath.java:492)
tests_1     |   at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:457)
tests_1     |   at sun.misc.URLClassPath.getResource(URLClassPath.java:211)
tests_1     |   at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
tests_1     |   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
tests_1     |   at java.security.AccessController.doPrivileged(Native Method)
tests_1     |   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
tests_1     |   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
tests_1     |   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
tests_1     |   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by hierynomus** [comment]
This comes most probably from BouncyCastle, whcih is a signed jar, and can thus not be bundled
