### ISSUE TITLE
Opening 'directed-tcpip' channel failed

### ISSUE THREAD

**Issue by Jay-P** [hierynomus/sshj#340]
Hi,

I'm trying to set up an SSH tunnel with port forwarding, but i'm encountering this error :

Opening `direct-tcpip` channel failed: Connection refused
	at net.schmizz.sshj.connection.channel.direct.AbstractDirectChannel.gotOpenFailure(AbstractDirectChannel.java:74)
	at net.schmizz.sshj.connection.channel.direct.AbstractDirectChannel.gotUnknown(AbstractDirectChannel.java:99)
	at net.schmizz.sshj.connection.channel.AbstractChannel.handle(AbstractChannel.java:203)
	at net.schmizz.sshj.connection.ConnectionImpl.handle(ConnectionImpl.java:130)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:500)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

my code is the following : 
public class LocalPF {

    public static void main(String... args)
            throws IOException {
        SSHClient ssh = new SSHClient();

        ssh.addHostKeyVerifier(new PromiscuousVerifier());

        ssh.connect("192.168.1.1");
        try {

          File privateKey = new File("key_file.ppk");
          KeyProvider keys = ssh.loadKeys(privateKey.getPath());
          ssh.authPublickey("User",keys);

            /*
            * _We_ listen on localhost:8080 and forward all connections on to server, which then forwards it to
            * google.com:80
            */
            final LocalPortForwarder.Parameters params
                    = new LocalPortForwarder.Parameters("localhost", 8080, "192.168.1.1", 80);
            final ServerSocket ss = new ServerSocket();
            ss.setReuseAddress(true);
            ss.bind(new InetSocketAddress(params.getLocalHost(), params.getLocalPort()));
            try {
                ssh.newLocalPortForwarder(params, ss).listen();
            } finally {
                ss.close();
            }

        } finally {
            ssh.disconnect();
        }
    }

}

I have no problem downloading files through sftp from this server and the port forwarding works with putty so I don't understand what could be wrong. The error pop up when i load http://localhost:8080 on my browser.

Thanks in advance

**Comment by Jay-P** [comment]
I fixed my issue.

**Comment by hierynomus** [comment]
Hi @Jay-P, could you elaborate what you did wrong and how you fixed it. Could be great documentation for somebody who runs into the same trap...

**Comment by manx98** [comment]
This error is caused by the absence of the configuration "AllowTcpForwarding yes" in the server's /etc/sshd_config file.
