### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by shargon** [hierynomus/sshj#341]
This library have a hight security problem, exposed in this spanish blog "https://www.fwhibbit.es/0day-senor-tiname-el-sobrero-rfi-por-ssh"

SCP accept any name, and could produce a RFI in scenario like this

https://youtu.be/gKnDuLy4bwk 

There is no check of the file name at "https://github.com/hierynomus/sshj/blob/master/src/main/java/net/schmizz/sshj/xfer/scp/SCPDownloadClient.java#L156" and "https://github.com/hierynomus/sshj/blob/c9775ca2c74cc4528505130c0da65bc38de21dea/src/main/java/net/schmizz/sshj/xfer/FileSystemFile.java#L157"

**Comment by hierynomus** [comment]
Thanks for notifying me. I'll patch and release it as soon as possible. Shouldn't be too hard. 

Do you know whether there is a good English translation available of the security leak?

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hierynomus** [comment]
Hi @shargon I've made a PR for this, can you check whether this fixes the problem?

Thanks!

**Comment by shargon** [comment]
Thanks for the quickly fix of the bug, the problem for test it, its that im not good Java programmer (only in android) and i found this bug via HackerOne at Ubiquiti.

But i can see your test, and aparently are ok, if the method receibe the download of a file 'foo' can't get 'bar' or similar, only the 'foo' file must be right

Sorry for my english
