### ISSUE TITLE
How can I execute a series of command over the same channel with same session?

### ISSUE THREAD

**Issue by prasanta-biswas** [hierynomus/sshj#345]

**Comment by fenik17** [comment]
You can not. See [Session's javadoc](
https://github.com/hierynomus/sshj/blob/master/src/main/java/net/schmizz/sshj/connection/channel/direct/Session.java#L30): 
> It is not legal to reuse a session channel for more than one of command, shell, or subsystem.

**Comment by hierynomus** [comment]
Indeed see the JavaDoc, you should use a Shell if you want to execute more commands (or upload a script that contains all your commands and then execute it as a single command.
