### ISSUE TITLE
can i authenticate to the server which require both password and key?

### ISSUE THREAD

**Issue by NotAGitHub** [hierynomus/sshj#346]

**Comment by hierynomus** [comment]
What kind of server is that? What is the auth method it sends then? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NotAGitHub** [comment]
Sftp server I guess.
This is a telnet result:

Escape character is '^]'.
SSH-2.0-VShell_3_9_1_494 VShell

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hierynomus** [comment]
What error do you get when you connect and authenticate to the server? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NotAGitHub** [comment]
I did not try to connect yet due to network problem. But I didn't found any method to do that. Do you have any suggestion?

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hierynomus** [comment]
The question really is how is it normally authenticating. There is no
(default) auth-method in SSH that I know of that does both things in one go.

So the question is what is the authentication flow?

2017-08-08 12:36 GMT+02:00 NotAGitHub <notifications@github.com>:

**Comment by NotAGitHub** [comment]
Im trying to migrate from JSCH. And I have work well code below.

JSch jsch = new JSch();
				jsch.addIdentity(sshPath);
				log.info("Certificate: " + sshPath+" is correct.");
				Session session;
				session = jsch.getSession(destUser, destHost, destPort);
				
				if(destPassword!=null && !destPassword.equals("")){
					UserInfo ui = new MyUserInfo(destPassword);
					session.setUserInfo(ui);
				}
				session.connect();

So I think it validate key first then check password.
Is this enough? Or I need to find out more detail?

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hierynomus** [comment]
Ahh now I understand. It does not use both. It just sets it up so it support multiple auth-methods.

In SSHJ you could do this with:

```
SSHClient sshClient = new SSHClient();
List<AuthMethod> authMethods = new ArrayList<>();
authMethods.add(new AuthPublicKey(sshClient.loadKeys(sshPath)));
if (destPassword != null && !destPassword.equals("")) {
    PasswordFinder pf = new PasswordFinder() {
        @Override
        public char[] reqPassword(Resource<?> resource) {
            return destPassword.toCharArray();
        }

        @Override
        public boolean shouldRetry(Resource<?> resource) {
            return false;
        }
    };
    authMethods.add(new AuthPassword(pf));
    authMethods.add(new AuthKeyboardInteractive(new PasswordResponseProvider(pf)));
}
sshClient.connect(destHost, destPort);
sshClient.auth(destUser, authMethods);
Session session = sshClient.startSession();
```

**Comment by NotAGitHub** [comment]
It's work! Thank you for your help!!

I fixed your code a little bit. ill post it for someone who need it.

      List<AuthMethod> authMethods = new ArrayList<AuthMethod>();
			
			if(sshPath != null && !sshPath.equals(""))
			authMethods.add(new AuthPublickey(ssh.loadKeys(sshPath)));
			
			if (pass != null && !pass.equals("")) {
			    PasswordFinder pf = new PasswordFinder() {
			        @Override
			        public char[] reqPassword(Resource<?> resource) {
			            return pass.toCharArray();
			        }

			        @Override
			        public boolean shouldRetry(Resource<?> resource) {
			            return false;
			        }
			    };
			    authMethods.add(new AuthPassword(pf));
			    authMethods.add(new AuthKeyboardInteractive(new PasswordResponseProvider(pf)));
			}
			ssh.connect(host, 22);
			ssh.auth(user, authMethods);
			Session session = ssh.startSession();

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hierynomus** [comment]
Thanks and good luck!
