### ISSUE TITLE
Exhausted available authentication methods

### ISSUE THREAD

**Issue by ojoyo** [hierynomus/sshj#351]
Please help to resolve the issue, i am trying to perform ssh to remote machine, with pasword and username Code works fine but with authPublickey the following error is displayed - 

> Exception in thread "main" net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods

```
import net.schmizz.sshj.SSHClient;
import net.schmizz.sshj.connection.channel.direct.Session;
import java.io.IOException;

public class Connection {
    private String ipAddress = "192.168.200.45";

    protected Session session;
    protected SSHClient sshClient;

    public void makeConnection() throws IOException {
        sshClient = new SSHClient();
        sshClient.loadKnownHosts();

        sshClient.connect(ipAddress);
        sshClient.authPublickey(System.getProperty("user.name"));

        session = sshClient.startSession();

        if (session != null) {
            System.out.println("You are connected to remote system");
        }
        else
            System.out.println("Connection not done");
    }
}
```

Maven Dependency used is as follows - 
 ```
 <dependency>
            <groupId>com.hierynomus</groupId>
            <artifactId>sshj</artifactId>
            <version>RELEASE</version>
        </dependency>
```

**Comment by hierynomus** [comment]
What is the debug log for a connection attempt?

Op 23 aug. 2017 7:48 a.m. schreef "Jalmeen Kaur Sethi" <
notifications@github.com>:

**Comment by Jalmeen** [comment]
Attached logs

```
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:345)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:394)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:324)
	at Connection.makeConnection(Connection.java:19)
	at Main.main(Main.java:7)

```

**Comment by hierynomus** [comment]
Please run with a logging backend enabled, such as logback. From this logs
nothing can be determined.

Options are:
- The key is not accepted
- High-strength crypto is not loaded so it could not load any of your keys


2017-08-23 8:51 GMT+02:00 Jalmeen Kaur Sethi <notifications@github.com>:

**Comment by godenji** [comment]
May not be related but I get the same error with public key auth.

log reveals little:
DEBUG c.h.s.u.k.OpenSSHKeyV1KeyFile [OpenSSHKeyV1KeyFile.java:100] Reading unencrypted keypair

Running openjdk latest (1.8.0_144). Strange thing is that the same application works fine with sshj on the staging server, but not production.

> High-strength crypto is not loaded so it could not load any of your keys

I'm wondering if the staging server pulls in a missing piece (like bouncycastle) that's not present in production. I see that sshj itself pulls in `bcpkix-jdk15on-1.56` and `bcprov-jdk15on-1.56`. Are any other BouncyCastle deps required?

**Comment by hierynomus** [comment]
@godenji that message means you have not loaded the unlimited strength crypto extensions. See whether that helps

**Comment by godenji** [comment]
@hierynomus thanks, JCE unlimited is apparently built-in on 1.8.0_144
```
/usr/bin/jrunscript -e 'print (javax.crypto.Cipher.getMaxAllowedKeyLength("RC5") >= 256);'
true
/usr/bin/jrunscript -e 'print (javax.crypto.Cipher.getMaxAllowedKeyLength("AES") >= 256);'
true
```
there must be something else going on, totally baffled as to why staging server running identical openjdk and corresponding java application works fine with sshj, while production fails.

**Comment by godenji** [comment]
@hierynomus yeah, so openjdk ships with JCE unlimited, that's not the issue, it's support for openssh private keys. Staging server jvm user's private key (RSA) was setup before rolling out to openssh private keys on new servers, thus the reason for staging working and production failing.

Looks like I'm hitting a variation of #358, albeit without the `PromiscuousVerifier` restriction. Does sshj support openssh private keys, or is this perhaps lack of support in the (open)jdk?

**Comment by hierynomus** [comment]
@godenji Try with building a snapshot from #396, I've made some fixes in that PR that hopefully fixes the problems people were running into with ecdh-sha2-nistp256 keys.

**Comment by MazenAtaya** [comment]
Getting the same error:
`[info] n.s.s.t.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.23.0
[info] n.s.s.t.TransportImpl - Server identity string: SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
[debug] n.s.c.Promise - Setting <<kex done>> to `null`
[debug] n.s.s.t.KeyExchanger - Sending SSH_MSG_KEXINIT
[debug] n.s.c.Promise - Setting <<kexinit sent>> to `SOME`
[debug] n.s.c.Promise - Awaiting <<kex done>>
[debug] n.s.s.t.KeyExchanger - Received SSH_MSG_KEXINIT
[debug] n.s.s.t.KeyExchanger - Negotiated algorithms: [ kex=curve25519-sha256@libssh.org; sig=ssh-rsa; c2sCipher=aes128-cbc; s2cCipher=aes128-cbc; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
[debug] n.s.s.t.k.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
[debug] n.s.s.t.KeyExchanger - Received kex followup data
[debug] n.s.s.t.k.Curve25519SHA256 - Received SSH_MSG_KEXDH_REPLY
[debug] n.s.s.t.KeyExchanger - Trying to verify host key with net.schmizz.sshj.transport.verification.PromiscuousVerifier@939c550
[debug] n.s.s.t.KeyExchanger - Sending SSH_MSG_NEWKEYS
[debug] n.s.s.t.KeyExchanger - Received SSH_MSG_NEWKEYS
[debug] n.s.c.Promise - Setting <<kexinit sent>> to `null`
[debug] n.s.c.Promise - Setting <<kex done>> to `SOME`
[debug] n.s.s.SSHClient - Key exchange took 0.128 seconds
[debug] n.s.c.Promise - Setting <<service accept>> to `null`
[debug] n.s.s.t.TransportImpl - Sending SSH_MSG_SERVICE_REQUEST for ssh-userauth
[debug] n.s.c.Promise - Awaiting <<service accept>>
[debug] n.s.c.Promise - Setting <<service accept>> to `SOME`
[debug] n.s.s.t.TransportImpl - Setting active service to ssh-userauth
[debug] n.s.c.Promise - Setting <<authenticated>> to `null`
[debug] n.s.s.u.UserAuthImpl - Trying `publickey` auth...
[debug] n.s.s.u.m.AuthPublickey - Attempting authentication using PKCS8KeyFile{resource=[PrivateKeyStringResource]}
[debug] n.s.c.Promise - Awaiting <<authenticated>>
[debug] n.s.c.Promise - Setting <<authenticated>> to `false`
[debug] n.s.s.u.UserAuthImpl - `publickey` auth failed
[error] c.m.s.s.StartOfDayFileWatcherService - Error happened during the sync process
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:231)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:346)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:365)
	at akka.stream.alpakka.ftp.impl.SftpOperations.initKey$1(SftpOperations.scala:127)
	at akka.stream.alpakka.ftp.impl.SftpOperations.setIdentity(SftpOperations.scala:135)
	at akka.stream.alpakka.ftp.impl.SftpOperations.$anonfun$connect$3(SftpOperations.scala:39)
	at akka.stream.alpakka.ftp.impl.SftpOperations.$anonfun$connect$3$adapted(SftpOperations.scala:39)
	at scala.Option.foreach(Option.scala:257)
	at akka.stream.alpakka.ftp.impl.SftpOperations.$anonfun$connect$1(SftpOperations.scala:39)
	at scala.util.Try$.apply(Try.scala:209)`

any help is highly appreciated!!

**Comment by gboie** [comment]
I get the same error, but I am able to connect the first time just fine, the second time I am trying to connect, this is when I get the error. Same function, works the first time, fails the second time.

**Comment by joehitt** [comment]
For future readers - the exact behavior described above can be caused by passing in a char[] array as the password, ssh key, or ssh key password, and the SSH/J API will blank out that char array internally.  Be sure to copy any password char[] array before passing into sshj API before attempting to re-use that same char[] again as you can end up passing in blank credentials, which causes authentication to succeed first time and then fail subsequent attempts.
The API correctly uses mutable char[] array so it can be blanked out for security purposes, however the API takes responsibility for doing this for you - so it can cause some confusion.
