### ISSUE TITLE
Using SHA-1 and SHA-256 SSH fingerprints

### ISSUE THREAD

**Issue by jpstotz** [hierynomus/sshj#364]
Modern Linux installations no longer provide MD5 SSH fingerprints by default. 
Therefore I implemented some code for replacing calls like

`sshClient.addHostKeyVerifier("4b:69:6c:72:6f:79:20:77:61:73:20:68:65:72:65:21");`.

Using the helper class from the following [GIST](https://gist.github.com/jpstotz/c336759aa4d67d9ab60d90a47e586e67) it is possible to write:

`sshClient.addHostKeyVerifier(SSHFingerprintVerifier.getInstance("SHA1:<base64 encoded fingerprint>"));`

`SHA-256` and the old `MD5` (no prefix, just the old hex notation) are supported as well.

**Comment by hierynomus** [comment]
Thanks for the Gist and issue, I've added this in PR #365
