### ISSUE TITLE
Class javax.xml.bind.DatatypeConverter not available on Android, but can be avoided

### ISSUE THREAD

**Issue by tliebeck** [hierynomus/sshj#366]
I'm using (or rather am going to be using) SSHJ in an Android app.  I'm seeing a crash with public keys with passphrases due to a NoClassDefFoundError for javax.xml.bind.DatatypeConverter, which is not available in Android.  

DatatypeConverter is used only by net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile to convert a hex string into a byte array.

I've fixed this problem by removing this dependency and adding my own hex-string-to-byte-array method to PKCS5KeyFile:

    private static byte[] parseHexBinary(String s) 
    throws IllegalArgumentException {
        if (s == null) {
            return new byte[0];
        }
        s = s.trim();
        int length = s.length();
        
        if (length % 2 != 0) {
            throw new IllegalArgumentException("Invalid hex string length.");
        }
        
        byte[] result = new byte[length / 2];
        for (int i = 0; i < length; i += 2) {
            result[i/2] = (byte) Integer.parseInt(s.substring(i, i + 2), 16);
        }
        return result;
    }

My implementation can be made much more efficient (most notably by replacing that substring() call).

**Comment by coudy** [comment]
Removing the dependency on `java.xml` is also necessary for Java 9 SE compatibility.

**Comment by hierynomus** [comment]
@tliebeck @coudy Have a look at the current master, this has already been fixed :) I will release a new version coming week.

**Comment by coudy** [comment]
@hierynomus any news on the release? :) cheers

**Comment by hierynomus** [comment]
@coudy @tliebeck Does the latest release work for you wrt this issue?

**Comment by hierynomus** [comment]
Closing as it is solved in v0.23.0
