### ISSUE TITLE
Umask permissions on SFTP file upload

### ISSUE THREAD

**Issue by BigChief45** [hierynomus/sshj#378]
I am doing some file uploading using SFTP and then setting the file permissions after upload:

```java
sftpClient.chmod(filePath, 660);
```
However, when using SSH to check the assigned permissions of the uploaded file, I get these permissions:

```
--w--w-r-T
```

As you can see, this are not the correct permissions for a `chmod 660` command, which should be:

```
-rw-rw-r--
``` 

This leads me to believe that the user doing the SFTP upload's **umask** is interfering with the permissions I am assigning using the `chmod()` method.

Therefore I want to know if there is a way to specify a umask value before doing the upload using this library? Or how to get around this issue?

**Comment by BigChief45** [comment]
@hierynomus Any ideas?

**Comment by hierynomus** [comment]
There is no way to client-side set the umask as far as I'm aware, also google has not turned up any results. It seems that newer SFTP specifications (later than level 3) have included a detailed specification on how umask should be applied, but as mentioned [here](https://serverfault.com/questions/639042/does-openssh-sftp-server-use-umask-or-preserve-client-side-permissions-after-put) OpenSSH seems to violate that.

**Comment by hierynomus** [comment]
@BigChief45 Does that answer your question?

**Comment by BigChief45** [comment]
Yes, but I could never get it to work, so I had to opt for a different solution. Thanks for the answer though.

Closing.

**Comment by Kairs0** [comment]
Hi,
Even if the issue is closed, it seems that the reply did not address the real problem.
chmod takes file permission in octal format
@BigChief45 had given them in decimal format (660 in decimal equals 1224 in octal)
Setting rights using 0660 (java notation for octal) should work perfectly
