### ISSUE TITLE
ssh connection takes a long time with Bouncy Castle

### ISSUE THREAD

**Issue by magg** [hierynomus/sshj#379]
I have this piece of code to validate a connection to a remote host, I perform more than 10 connections when I run the program and it takes 13 seconds to execute.

I have enabled Bouncy Castle as a security provider and added the corresponding jars to my classpath

Is there any way to avoid taking such a long time?

```
int sshTimeout = 11000;
boolean login = false;
 try {
	        	       ssh.setConnectTimeout(sshTimeout);
	        	       ssh.setTimeout(sshTimeout);
	            	   ssh.connect(host); 
	                   final Session session = ssh.startSession();
	                   try {
	                      login = true;
	                   } finally{
	                	   session.close();
	                   }
	                   ssh.disconnect();
	               } catch (Exception e) {
                              e.printStackTrace();
	                    try {
							ssh.disconnect();
						} catch (IOException e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
	               } 			
```

Is it something wrong with the code? or it's just a network I/O problem?

**Comment by hierynomus** [comment]
10 connection attempts taking in total 13 seconds? That means on average 1.3 secs per attempt. That does not sound unreasonable for the amount of network IO that needs to happen, including opening sockets and potentially resolving domain names...

**Comment by magg** [comment]
@hierynomus Ok but is there something I can do speed up the connection process?

like creating a default config at the beginning and passing it to the sshclient objects,  for example:
```
DefaultConfig sshDefaultConfig = new DefaultConfig();
SSHClient ssh = new SSHClient(sshDefaultConfig);
```

**Comment by hierynomus** [comment]
Creating a single config will definitely speed up the process as each new config initializes a `Random` instance. Initializing that needs entropy, which in quiet systems (such as VMs) will lead to significant slowdowns in the initialization sequence.

**Comment by magg** [comment]
nice, any other tips to speed up?

**Comment by magg** [comment]
using Jprofiler I found that CPU is mostly used by java.security.KeyPairGenerator.generateKeyPair
and javax.crypto.KeyAgreement.doPhase...

I'm using the default config but they still take most of the CPU time

**Comment by hierynomus** [comment]
Which makes sense, they're crypto functions and need to calculate some stuff. That is definitely not cacheable ;)

**Comment by hierynomus** [comment]
@magg Any more help needed?

**Comment by magg** [comment]
no, closing
