### ISSUE TITLE
how to use sudo

### ISSUE THREAD

**Issue by a250152** [hierynomus/sshj#391]
Command cmd = session.exec("su root ; 123456");
no work

**Comment by hierynomus** [comment]
Hi @a250152, That won't work indeed. As a first point, `su != sudo` (i.e. you're asking about `sudo` but the text mentions `su`). Secondly, you need to pass the command you want to execute to `su` (or `sudo`) as: `sudo -u root "123456"`

This only works for passwordless `sudo`. If you need a password prompt, you need to open a shell.

**Comment by a250152** [comment]
@hierynomus I want to 
Command cmd = session.exec("su root");
but how to input password
I dont kon how to do it

**Comment by hierynomus** [comment]
You need to open a shell (`session.startShell`) and then read from the inputStream of the shell and write to the outputStream of the shell. 

Else take a look at https://github.com/xebialabs/overthere, which has support for this out of the box.

**Comment by a250152** [comment]
@hierynomus Thank you so much

**Comment by seinecle** [comment]
The general doc of overthere is very hard to read, sshj is much more targeted (just ssh). I'd love to have a clear example of sudo command with `sshj` with `inputStream `and `outputStream `if possible?
