### ISSUE TITLE
Auto Reading of SSH Key Types from Known Hosts?

### ISSUE THREAD

**Issue by MrAaronOlsen** [hierynomus/sshj#393]
This is not an issue, but a clarifying question.

I've been playing around with various libraries, specifically JSch and Apache's VFS, to make SFTP connections. I rely on password auth right now and bypassing host verification is not an option. In other libraries I sometimes get host key verification errors even with the host present in the known_hosts file. This is due to the key being of a type other than the "preferred" type for client or server, which typically ends up being ssh_rsa. I could have folks making ssh_rsa keys or ecdsa for any number of combinations of Client - Server connections. To ensure I don't get a false rejection of a known host I would have to first look in the known_host file, find the type, and force the loading of the key with the type I found. This seems odd to me and at the very least adds a bit of "chaos" into my code.

SSHJ seems to be the only library that happily loads the know_hosts file and verifies the hosts with out me specifying the expected key type.

Three Questions:
- What do you do to resolve this
- Would future key types be immune
- Are there other issues or problems, from a coding perspective, that make this difficult or hacky to implement? I ask this only because the other libraries have not addressed it yet.

Thank you very much.

**Comment by hierynomus** [comment]
If you look at the spec of the known_hosts format, you see that there are multiple ways in which the key format can be specified. 
- The second (or third in case a marker is used) field is an integer
- The second (or third) field is a key-type (ssh-rsa, ssh-dsa, ecdsa-...., etc)

In case it is an integer, it actually is an `ssh-rsa` key. In all other cases the type is defined by the type given. But also note, a lot of the newer (and more secure) key types such as `ecdsa` and `ed25519` might not always be supported by all libraries.

The code I have for this is not hacky and follows the specifications nicely. If there are new key types, we have to code support for them, as of yet I'm not aware that there is anything crucial that's missing.

Hope that helps!

**Comment by hierynomus** [comment]
@MrAaronOlsen Is this answered?

**Comment by MrAaronOlsen** [comment]
Thank you @hierynomus! Yes this answers my question. This seems like a small thing, but I'm very happy I don't need to worry about checking for key types. Closing issue.
