### ISSUE TITLE
Q: x.509 type supported?

### ISSUE THREAD

**Issue by j0kkeri** [hierynomus/sshj#399]
Hi,

Not an issue but question and the question might even be some ways irrelevant as I don't fully understand all the certificate aspects:

I have a requirement to use public-private keypair which is x.509 standard, does this library support this kind of certificate?

-J0kkeri

**Comment by hierynomus** [comment]
Do you mean a keypair used for authentication? Or is the keypair used for host verification?

**Comment by j0kkeri** [comment]
Sorry, I mean keypair for authentication.

**Comment by hierynomus** [comment]
Just a question back: What have you tried and where did it lead?

**Comment by j0kkeri** [comment]
I haven't tried this yet at all, only mapping out the possible solutions as the need is to use x.509 standard public-private keypair.
Unfortunately it is not yet even possible to test this as the server side is not there yet.

In previous life I have used Java keytool and Puttygen to create key pairs but I don't have understanding what requirements does the x.509 set.

**Comment by j0kkeri** [comment]
Closing... not really an issue.
