### ISSUE TITLE
How to send CTRL+C to SSHServer

### ISSUE THREAD

**Issue by zhongyang0316** [hierynomus/sshj#421]
hello
     now i want to send CTRL+C to SSHServer with SSHJ, i try signal(Signal.KILL) and OutputStream().write(3),but all it do not work,can you have solution?

**Comment by IonoclastBrigham** [comment]
Actually, I believe you want `Signal.INT`, but I never got that working, either. What finally did end up looking like it works is:

```kotlin
outputStream.write("\u0003".toByteArray())
outputStream.flush()
```

But it's _super_ sketchy/unreliable unless I fire that from the same worker thread as I'm reading from `inputStream` on.
