### ISSUE TITLE
SSH authentication fails when using Ed25519 + passphrase

### ISSUE THREAD

**Issue by davidleeuk** [hierynomus/sshj#427]
To replicate: 
1. Generate a key using `ssh-keygen -t ed25519`
2. When prompted, specify a passphrase
3. Call ssh.authPublickey(username, privateKeyFilePath, passphrase)

Throws "exhausted available authentication methods":

> Client identity string: SSH-2.0-SSHJ_0.24.0
> Server identity string: SSH-2.0-OpenSSH_7.5p1 Ubuntu-10ubuntu0.1
> Keypair is encrypted with: aes256-ctr, bcrypt,    ►^ ??KW☻9←?P♦????   ►
> Exhausted available authentication methods

I've checked the same works with Ed25519 keys with no passphrase applied; the combination of Ed25519+passphrase appears to be unsupported. Any advice please?

**Comment by hierynomus** [comment]
Hi @davidleeuk, Can you try to see whether PR #429 works for you?
