### ISSUE TITLE
sshj 0.23.0: Intermittent exception while connect net.schmizz.sshj.transport.TransportException: Server closed connection during identification exchange

### ISSUE THREAD

**Issue by ajit-pawar-sp** [hierynomus/sshj#431]
Hi,

I am using sshj 0.23.0 version with its required dependencies. I am getting following exception intermittently while connect:
sudo code for connect using sshj:-
                 // Using PromiscuousVerifier to avoid fingerprint verification
                // refer https://github.com/hierynomus/sshj/issues/358 for the details
                sshjClient.addHostKeyVerifier(new PromiscuousVerifier());
                sshjClient.setConnectTimeout(sshLoginTimeout);
                sshjClient.connect(sshHostName, sshPortNo);

Exception: net.schmizz.sshj.transport.TransportException: Server closed connection during identification exchange
- Exception Stacktrace: 
- Error:       net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:181)
- Error:       net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:771)
- Error:       net.schmizz.sshj.SocketClient.connect(SocketClient.java:127)

What is causing this issue?

Thanks!!!

**Comment by ltamaster** [comment]
Hi @ajit-pawar-sp 
Did you fix this issue?

**Comment by sMitea** [comment]
Did you fix this issue?

**Comment by YAGAMIL** [comment]
I ran into the same problem

**Comment by MingdaMa** [comment]
Can you elaborate on how you solved this?
