### ISSUE TITLE
Version 0.25.0 is not in maven central repo

### ISSUE THREAD

**Issue by ridvan70** [hierynomus/sshj#434]
`<dependency>
  <groupId>com.hierynomus</groupId>
  <artifactId>sshj</artifactId>
  <version>0.25.0</version>
</dependency>`

does not work

**Comment by AaliMohammed** [comment]
@hierynomus Do we have any timeline when it's gonna update in Maven Central?

**Comment by hierynomus** [comment]
I've just released 0.26.0 to maven central. Should be arriving somewhere in the next 2 hours

**Comment by tancolo** [comment]
@ridvan70  https://search.maven.org/search?q=g:com.hierynomus%20AND%20a:sshj&core=gav
