### ISSUE TITLE
WARN "Illegal key size" and "Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy"

### ISSUE THREAD

**Issue by aasmirnova7** [hierynomus/sshj#438]
Hello.
How can I exclude WARN from net.schmizz.sshj.DefaultConfig and net.sf.commons.ssh.impl.sshj.SSHJShellSession like "Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy", "Illegal key size"?
P.S. I can't use Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files
and solution from https://stackoverflow.com/questions/43346755/how-can-i-modify-net-schmizz-sshj-logging-level isn't  convenient for me

**Comment by hierynomus** [comment]
Well there are 4 options:

1. Use OpenJDK (contrary to Oracle JDK that has high strength encryption enabled by default)
2. Change the `net.schmizz.sshj.DefaultConfig` logger to log only `ERROR`, using a `logback.xml` file on the classpath
3. Install the high-strength crypto extensions.
4. Instantiate an empty `Config` and only add the weak ciphers/macs/etc.
