### ISSUE TITLE
SSHClient blocked while trying to read server identification

### ISSUE THREAD

**Issue by redmoonrising** [hierynomus/sshj#439]
Hi,
Using the latest version of sshj (0.23.0) our client was blocked while reading server identification. This was caused by a flawed (SFTP) server that was temporarily either not responding or giving incorrect responses.
The last method that our client logged was:
```Java
TransportImpl.sendClientIdent: Client identity string: SSH-2.0-SSHJ_0.23.0
```

The expected following log message 
```Java
TransportImpl.init: Server identity string: SSH-2.0-FTP Server
```
did not show up, the client was hanging. This was probably caused by the call of
```Java
int b = connInfo.in.read();
```
in TransportImpl#receiveServerIdent as the read method may block.
See also https://stackoverflow.com/questions/41630341/ssh-server-identification-never-received-handshake-deadlock-sshj#

It seems to be possible to simulate the situation using netcat:
* ok - expected answer "SSH-2.0" prefix:
echo "SSH-2.0-foo" | netcat -l PORTNO

* problematic case - no answer (hangs in read):
netcat -l PORTNO

Thanks in advance and best regards.

**Comment by hierynomus** [comment]
Did you configure a socket timeout?

**Comment by redmoonrising** [comment]
No, sorry we did not. Thanks a lot.
