### ISSUE TITLE
[PROTOCOL_ERROR] Received data for nonexistent channel 1.

### ISSUE THREAD

**Issue by tancolo** [hierynomus/sshj#440]
Thank you for your amazing lib.
sshj version: 0.26.0 (not use source code)
Client: Android

I am facing a strange problem: In the process of using sshj, the SSH tunnel is successfully established, but in the process of passing data, an error occurs:
```
net.schmizz.sshj.transport.TransportException: [PROTOCOL_ERROR] Received data for nonexistent channel 1.
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:548)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:508)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
```
This will cause the SSH connection to be broken.

So, my question is:
-  "[PROTOCOL_ERROR] Received data for nonexistent channel 1"  What is the underlying cause of this error? 

I noticed that someone reported a similar problem in 2016: issue(https://github.com/hierynomus/sshj/issues/274)

**Comment by hierynomus** [comment]
Hi @tancolo,
Can you get me a full trace level log from initial connect up to the exception?

**Comment by tancolo** [comment]
hello @hierynomus ,
From the debug log of my project,  I could not see the logs about sshj,  just see that error as above. 
If you want the full level log about your sshj lib,   how to open the log switcher on your sshj lib? 

BTW,  did you use the SLF4J in your sshj?  From my debug log, it shows some System.error, like this:
```
W/System.err( 8782): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err( 8782): SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err( 8782): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Thank you.

**Comment by hierynomus** [comment]
Yes, sshj uses slf4j as a logging api. Try to add logback as a logging impl to the classpath. Dont forget to add an logback xml file to enable trace logging.

**Comment by tancolo** [comment]
hello @hierynomus,
I got the logs,  the log file is a bit large size. so I send it to you email. (jeroen@hierynomus.com) 
The title is [PROTOCOL_ERROR] Received data for nonexistent channel 1. #440
any question, let me know!

**Comment by hierynomus** [comment]
Got it!

**Comment by tancolo** [comment]
From sshj trace log, I found the channel number changed every time. And it will occur String close exception. And then sshj shutdown.
```
E/n.s.s.c.StreamCopier( 5093): [soc2chan            ] In pipe from java.net.SocketInputStream@ff7be55 to < ChannelOutputStream for Channel #0 >net.schmizz.sshj.connection.ConnectionException: Stream closed
... ...
E/n.s.s.c.StreamCopier( 5093): [soc2chan            ] In pipe from java.net.SocketInputStream@942ead1 to < ChannelOutputStream for Channel #2 >net.schmizz.sshj.connection.ConnectionException: Stream closed

... ...
 E/n.s.s.c.StreamCopier( 5093): [soc2chan            ] In pipe from java.net.SocketInputStream@fd2a9a4 to < ChannelOutputStream for Channel #3 >net.schmizz.sshj.connection.ConnectionException: Stream closed
... ...

08-01 18:28:18.163 V/n.s.s.t.TransportImpl( 5093): [reader              ] Received packet DISCONNECT
08-01 18:28:18.165 I/n.s.s.t.TransportImpl( 5093): [reader              ] Received SSH_MSG_DISCONNECT (reason=PROTOCOL_ERROR, msg=Received data for nonexistent channel 2.)
08-01 18:28:18.172 E/n.s.s.t.TransportImpl( 5093): [reader              ] Dying because - Received data for nonexistent channel 2.net.schmizz.sshj.transport.TransportException: Received data for nonexistent channel 2.
08-01 18:28:18.172 E/n.s.s.t.TransportImpl( 5093): 	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:548) ~[na:0.0]
08-01 18:28:18.172 E/n.s.s.t.TransportImpl( 5093): 	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:508) ~[na:0.0]
08-01 18:28:18.172 E/n.s.s.t.TransportImpl( 5093): 	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102) ~[na:0.0]
08-01 18:28:18.172 E/n.s.s.t.TransportImpl( 5093): 	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170) ~[na:0.0]
08-01 18:28:18.172 E/n.s.s.t.TransportImpl( 5093): 	at net.schmizz.sshj.transport.Reader.run(Reader.java:59) ~[na:0.0]
```
So, the DISCONNECT was occur by sshj Client, or from the Server? 

```
08-01 18:28:02.172 I/n.s.s.t.TransportImpl( 5093): [Thread-48           ] Client identity string: SSH-2.0-SSHJ_0.26.0
08-01 18:28:02.487 I/n.s.s.t.TransportImpl( 5093): [Thread-48           ] Server identity string: SSH-2.0-OpenSSH_6.6.1
```

**Comment by tancolo** [comment]
@hierynomus 
"using the integration test docker container? "  I don't understand your mean. 
You want me to create a test case for this issue? hmm,  this may be a bit difficult. I used the sshj library in our project. Our business logic is more complicated. I don't know how to use the test case to reproduce the problem.

**Comment by hierynomus** [comment]
Yes, I'm asking you to create a simple reproduction case. The issue is not very straightforward to troubleshoot. That means I need more information into what steps you're actually doing. The easiest way is to create the smallest case that reproduces the issue using the integration test framework that is already present in SSHJ.

**Comment by tancolo** [comment]
Hello @hierynomus,
About your suggestion (using the integration test docker container). 
Sorry, I don't know how to use the tools you said. But I can use another way to reproduce.
For detail, please check the email I sent.

Any question, please let me know.
Thank you!

**Comment by tancolo** [comment]
hello @hierynomus,
Do you have anything to update?

**Comment by hierynomus** [comment]
I do not... Can you get me a minimal reproducible scenario in code? Without the need for Android phones etc.

**Comment by tancolo** [comment]
Hi @hierynomus,
I think I can't provide the code you need for the time being. sshj is integrated in our code. The business logic of this issue is complicated. You need to log in to our account, open our app special service, and then it is possible to start SSH tunnel to reproduce the problem. 
hmm... If you want to reproduce this issue easily without an Android phone, I don't know how to deal with it...

**Comment by tancolo** [comment]
Hi @hierynomus,
I build a simple demo, it can reproduce the "xxx noexist channel 1" ERROR. 
I send you an email that contains the details of this demo.
So you can read and try to reproduced on your local PC. It works on my Linux Env.

In sshj demo, I use 
```
client.authPublickey(System.getProperty("user.name"));
```
you maybe execute 
```
ssh -R 9999:localhost:8080 localhost
``` 
and accepte yes,  then logout ssh connection, and then use sshj demo to test.
Any question, please let me know.

**Comment by tancolo** [comment]
Hello @hierynomus,
I create a simple sshj demo on our Docker container,  please check you email, follow some steps, you can login and reproduce that error.

Looking forward to your reply.
Thank you!

**Comment by tancolo** [comment]
@hierynomus 
Waiting for your reply
I recommend you try running the simple demo on our Docker to check the results.

Thank you.

**Comment by tancolo** [comment]
hello @hierynomus 
I created a Docker Container for this issue, please check you google email (jeroen@hierynomus.com). 
Title: A Docker Container for issue #440 

It's easy to reproduce it.
Any question, please let me know. 

Thank you so much.
