### ISSUE TITLE
Use SSHJ as SSH proxy for xterm.js

### ISSUE THREAD

**Issue by Kamil-Cumulocity** [hierynomus/sshj#441]
Hi! Is it possible to use SSHJ as SSH proxy? I mean to return stream unchanged with prompt like _[remoteaccess@ip-10-21-135-119 ~]$_ and colors info like in WebSSH2 ?

**Comment by hierynomus** [comment]
What have you tried? Have you taken a look at for instance `Session.startShell()`?

**Comment by Kamil-Cumulocity** [comment]
Yes, we use it, our solution is quite complex, so I do not want to paste whole code here. 
```
    private Callable<Session.Shell> prepareShellCallable(final RemoteAccess configuration, final InputStream socketIn, final OutputStream socketOut) {
        return new Callable<Session.Shell>() {
            @Override
            public Session.Shell call() throws Exception {
                sshClient.initNewSession(configuration.getHostname(), configuration.getPort(), socketIn, socketOut);
                doAuthentication();
                return sshClient.startSession().startShell();
            }
        };
    }
```

The actual issue is that we receive only clear text, without _helping_  characters, like info about colors. Sample (expected) output from node transmit:
`[01;34mcentos[0m     [01;34mdprimm[0m     [01;34mjakub[0m   [01;34mlpia[0m        [01;34mpawryn[0m     [01;34msoufiene[0m      [01;34myashwanth[0m` 
Every word is sorrounded with additional special characters. Is there any _switch_ or parameter to enable it in SSHJ? So it will proxy unchanged stream without special characters removal?

**Comment by hierynomus** [comment]
sshj does not do anything with the streams as you can see from the code. Most applications actually detect whether or not a (colors enabled) tty is attached. You might want to play with that by exporting some env variables before starting the program.

**Comment by Kamil-Cumulocity** [comment]
Do you mean `session.setEnvVar("SSH_PTY", "/dev/pts/9")` ? I can see `allocatePTY` method but can't find any example usage of it.

**Comment by hierynomus** [comment]
Have you tried simulating your problem using a regular SSH command?

**Comment by Kamil-Cumulocity** [comment]
With something like `ssh remoteaccess@dev-a 'ls -al'` ? Or there is better approach?

**Comment by hierynomus** [comment]
Yes, I would think so.

**Comment by Kamil-Cumulocity** [comment]
Many thanks, I'll give it a try.

**Comment by Kamil-Cumulocity** [comment]
Allocating "xterm-256color" Pty make it works.
