### ISSUE TITLE
Endless 'while' loop when making a non existing directory.  

### ISSUE THREAD

**Issue by alekseifedorov** [hierynomus/sshj#442]
The following snippet results in hanging my application:
SFTPClient sftp = sshClient.newSFTPClient();
sftp.mkdirs("/non_existent_dir/another_dir");

Everything works if the path starts with an existing directory.

The cause seems to be in SFTPClient.statExistence(current.getPath())
which returns always 'null' for the case mentioned above.

**Comment by hierynomus** [comment]
Can you check whether the fix from https://github.com/hierynomus/sshj/pull/415 makes a difference?

**Comment by alekseifedorov** [comment]
Thanks, the fix works!  It would be very nice to merge it in the master.

**Comment by alekseifedorov** [comment]
Could you recommend a workaround at the moment?

**Comment by hierynomus** [comment]
The best workaround would be to build sshj manually with the fix and use that for the time being. It's currently merged so the next release it will be fixed. But before releasing that I want to fix a few other issues.

**Comment by hierynomus** [comment]
Closing this issue as it is solved with latest master.
