### ISSUE TITLE
what's the license of this project

### ISSUE THREAD

**Issue by IamFive** [hierynomus/sshj#444]
I want to use sshj in our project, but i found no license is specified.

**Comment by IamFive** [comment]
This project is unlicensed now, No one was concerned with this?

**Comment by AaliMohammed** [comment]
It is Apache 2.0, https://mvnrepository.com/artifact/com.hierynomus/sshj/0.26.0.

**Comment by IamFive** [comment]
Thanks, my mistake, i find you do include license in the project. 
I don't know why github did not show license on the header banner like other projects (maybe due to the licence filename?)
