### ISSUE TITLE
Building SSHJ Error on Ubuntu 18

### ISSUE THREAD

**Issue by tancolo** [hierynomus/sshj#445]
Hello Jeroen,
I want to use your sshj source code into my Android app. So I followed your steps **Building SSHJ**:
```
1. Clone the SSHJ repository.
2. Ensure you have Java6 installed with the Unlimited strength Java Cryptography Extensions (JCE).
3. Run the command ./gradlew clean build.
```
yes, I cloned SSHJ reporitory by https. And I also changed my java env from jdk1.8 to jdk 1.6.

**SSHJ version: master latest code**
**OS ENV: Ubuntu 18**

java jdk env to $PATH,  add some info to .bashrc
```
export JAVA_HOME=$HOME/Android/jdk6/jdk1.6.0_45
export PATH=$JAVA_HOME/bin:$PATH
```
do cmd: **java -version**
```
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
```
execute **./gradlew clean build**, it will show gradle error.
```
FAILURE: Build failed with an exception.
* What went wrong:
Gradle 4.3 requires Java 7 or later to run. You are currently using Java 6.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
```

it means, the gradlew version of your source code is 4.3, but it doesn't support java 6.

So, I changed jdk to 1.8.  But when I executed the commond **./gradlew clean build**
it shows some many failed. like these:
```
... ...
180 tests completed, 110 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///xxxx/apps/code/sshj/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
15 actionable tasks: 14 executed, 1 up-to-date
```
How do I compile the available sshj.jar(current version is 0.26) package?

[reports.zip](https://github.com/hierynomus/sshj/files/2268998/reports.zip)

**Comment by tancolo** [comment]
It's ok for java 8.  I think the **Building SSHJ** should be changed.
```
1. Clone the SSHJ repository. (MUST)
2. Ensure you have Java6+ installed
3. Run the command ./gradlew clean build.
```
if you run the command ./gradlew clean build first time, it will spent more then 30 minutes, because there are 180 test cased should be executed. 
I recommend  run this command firstly, and then you change some code, you just only execute this command: **./gradlew clean build -x test**, this command will ignore test cases.

**Comment by hierynomus** [comment]
@tancolo I'll update the instructions to make it Java8. There is no need to build the library yourself, as it is included in Maven central. Only if you wish to make a PR would you need to be able to build the code.
Furthermore the tests should not take more than a minute to run (49s on my laptop).
