### ISSUE TITLE
请问 sshj  支持安卓吗？

### ISSUE THREAD

**Issue by zhangxianweihebei** [hierynomus/sshj#447]

**Comment by hierynomus** [comment]
Sorry, please ask your question in english...

**Comment by zhangxianweihebei** [comment]
Does sshj support Android?

@hierynomus

**Comment by tancolo** [comment]
Of cause, sshj also works for Android.
Please see the sshj README.md **Depending on SSHJ**

And if you want to know how to use the sshj lib for you Android project, I think you need read the sample folder in these library. Also need check the document 
http://www.javadoc.io/doc/com.hierynomus/sshj/0.26.0

Here is a refer document: **OReilly - SSH,,The Secure Shell - The Definitive Guide.pdf**
You can find the Chinese language. 

I think this issue can be closed.

**Comment by hierynomus** [comment]
Yes, there are multiple android apps that include SSHJ.

**Comment by zhangxianweihebei** [comment]
Well, thank you
