### ISSUE TITLE
sftp upload - target file name is surrounded by single ticks ' '

### ISSUE THREAD

**Issue by Sciss** [hierynomus/sshj#449]
This is with sshj v0.26.0:

```scala
val c = ssh.newSCPFileTransfer()
c.upload(new FileSystemFile("/data/temp/foo.aif"), "bar.aif")
```

This results in a file `'bar.aif'` instead of `bar.aif` on the remote. Only if I use

```scala
val c = ssh.newSCPFileTransfer()
c.upload(new FileSystemFile("/data/temp/foo.aif"), "")
```

The remote file becomes `foo.aif` and not `'foo.aif'`.

**Comment by Sciss** [comment]
Sees that using `ScpCommandLine.EscapeMode.SingleQuote` is wrong here.

**Comment by hierynomus** [comment]
When I introduced the `EscapeMode`, it was to make this behaviour configurable. Some OS's and/or ssh clients behave differently. Before it was hardcoded to do `'` escaping and surrounding. See commit d520585.

Which target OS/client are you using?

**Comment by Sciss** [comment]
The server runs "SunOS vilis 5.11 11.3 i86pc i386 i86pc Solaris" (that's the web space from my provider).

I guess a workaround would be instead of

```scala
c.upload(new FileSystemFile("/data/temp/foo.aif"), "bar.aif")
```
to write

```scala
val up = c.newSCPUploadClient()
up.copy(localFile, remotePath, ScpCommandLine.EscapeMode.NoEscape);
```

**Comment by hierynomus** [comment]
Indeed. For regular cases the `'` escape works perfect. But I can imagine that 'SunOS' does not run a standard OpenSSH or interprets paths differently, which is the actual problem with SCP.

**Comment by hierynomus** [comment]
I assume we can close this ticket?

**Comment by Sciss** [comment]
Sure
