### ISSUE TITLE
Particular Switch based on mina has a request issue

### ISSUE THREAD

**Issue by sandkumaCode** [hierynomus/sshj#457]
@Test
    public void testSshjPtyNoShell() throws Exception{
        String hostname = "XXX";
        String username = "XX";
        String password = "XXX";
        int port = 20002;
        String pcmd = "XXXX";

        final SSHClient ssh = new SSHClient();
        ssh.addHostKeyVerifier(new PromiscuousVerifier());
        ssh.setConnectTimeout(90000);

        try {
            ssh.getConnection().setWindowSize(4096);
            ssh.connect(hostname, port);
            ssh.authPassword(username, password);
            final Session session = ssh.startSession();
            try {

                session.allocateDefaultPTY();
                final Session.Command cmd = session.exec(pcmd);
                String response = (IOUtils.readFully(cmd.getInputStream()).toString());
                System.out.println("Response is == " + response);
                ssh.getConnection().join();

            } finally {
                session.close();
            }

        } finally {
            ssh.disconnect();
        }
    }

log attached
[ssj_log.log](https://github.com/hierynomus/sshj/files/2475553/ssj_log.log)

Same works with ssh client on mac/linux

Tried to make it work with shell and it worked as follows:
       
       SSHClient ssh = new SSHClient();
        ssh.addHostKeyVerifier(new PromiscuousVerifier());
        ssh.setConnectTimeout(90000);
        ssh.getConnection().setWindowSize(4096);
        ssh.connect(hostname, port);
        ssh.authPassword(username, password);
        final Session session = ssh.startSession();
        StringBuilder sb = new StringBuilder();
        try {

            session.allocateDefaultPTY();
            InputStream inputstream = session.getInputStream();
            OutputStream outputstream = session.getOutputStream();
            session.startShell();

            new Thread() {
                public synchronized void run() {
                    try {
                        int read;
                        while ((read = inputstream.read()) > -1) {
                            char[] chars = Character.toChars(read);
                            String s = new String(chars);
                            sb.append(s);
                           
                      }
                    } catch (Exception e) {
                        e.getMessage();
                    }
                }
            }.start();
            try {
                outputstream.write((pcmd + "\n").getBytes());
                outputstream.flush();
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                System.out.println("##### Final String ##### "+sb.toString());
            } finally {
                session.close();
            }
        } finally {
            ssh.disconnect();
        }

we cannot get out of the read because of this:

"Thread-2" #13 prio=5 os_prio=31 tid=0x00007ffe88ab6800 nid=0x1307 in Object.wait() [0x0000700008389000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at net.schmizz.sshj.connection.channel.ChannelInputStream.read(ChannelInputStream.java:106)
	- locked <0x000000076cb11d20> (a net.schmizz.sshj.common.Buffer$PlainBuffer)
	at net.schmizz.sshj.connection.channel.ChannelInputStream.read(ChannelInputStream.java:86)
	- locked <0x000000076cb11a78> (a [B)
	at com.ciena.TestSshj$2.run(TestSshj.java:190)
	- locked <0x000000076cbb4a90> (a TestSshj$2)

can we make the session.exec work as well?

**Comment by hierynomus** [comment]
Can you be a bit more specific as to what you're attempting, what is the expected outcome, and what doesn't work? I'm lost here....

**Comment by sandkumaCode** [comment]
The issue here was we were not getting a terminating message from ssh once we got we have the read working hence closing it
