### ISSUE TITLE
Which encoding to use for handling the input and output stream of the shell?

### ISSUE THREAD

**Issue by leolux** [hierynomus/sshj#463]
I like to write a String to the shell using this code:

```
///writer = shell.getOutputStream();
 for (byte byteToBeWritten : myCommandString.getBytes(StandardCharsets.UTF_16)) {
          writer.write(byteToBeWritten);
        }
 writer.flush();
```

But this results in unusable output from the inputStream which returns always the first two bytes -2 and -1 followed by more bytes representing the string "myCommandString". I am missing the result of the SSH command from the inputStream.

In the code above I set the encoding for the outputStream to UTF-16, but I am not sure if that is the correct way. Which encoding should be used when writing a string to the outputStream of the shell?

**Comment by leolux** [comment]
Has anyone tried to write a string to the outputStream of the shell?

**Comment by hierynomus** [comment]
Yes, there are multiple examples out there. Probably you need to use UTF-8.

Op do 8 nov. 2018 om 10:44 schreef leolux <notifications@github.com>:
