### ISSUE TITLE
Android Studio - establish simple ssh connection

### ISSUE THREAD

**Issue by FalcoSuessgott** [hierynomus/sshj#465]
Im trying to get sshj to work. Im using sshj in an android studio application.

I implemented a first testing example like this:

```
class ServerInstance
....
final SSHClient ssh = new SSHClient();

...

public void connection() throws IOException {
       ssh.addHostKeyVerifier(new PromiscuousVerifier());
        ssh.connect(this.host);
        Session session = null;
        try {
            ssh.authPublickey(this.user);
            session = ssh.startSession();
        } finally {
            try {
                if (session != null){
                    session.close();
                }
            } catch (IOException e){

            }
            ssh.disconnect();
        }
    }
```
and calling this method with

`server.connection();`

Im using `new PromiscuousVerifier()` because someone seems to head a similar problem and suggest it ([https://stackoverflow.com/questions/3630101/could-not-load-known-hosts-exception-using-sshj](https://stackoverflow.com/questions/3630101/could-not-load-known-hosts-exception-using-sshj)) 
There is no log in incomming on the remote server. 
I think I have to generate a real KeyPair and calling it with `loadKnownHosts()`. Can someone give me an example how to do that in an android studio project ? Thanks in advance

**Comment by hierynomus** [comment]
If you don't see any logging on the server I would suggest you check whether it is reachable from the client, or whether you're using the right address.

`PromiscuousVerifier` purely tells the client to trust any server key, so it obviates the need to call `loadKnownHosts`, or pre-load your app with keys from trusted servers. 

I would suggest turning the debug logging up and seeing whether there is any connection at all, I don't think so. Before it checks the server keys it should have already transmitted the client and server identification banners.
