### ISSUE TITLE
Could not verify `ecdsa-sha2-nistp256` and use the pom.xml how can i do?

### ISSUE THREAD

**Issue by a250152** [hierynomus/sshj#490]
`21:20:38.670 [main] INFO net.schmizz.sshj.transport.random.BouncyCastleRandom - Generating random seed from SecureRandom.
21:20:38.679 [main] DEBUG net.schmizz.sshj.transport.random.BouncyCastleRandom - Creating random seed took 7 ms
21:20:38.947 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.947 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.947 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.947 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.949 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.955 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.955 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.956 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.956 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.963 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.963 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.963 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.964 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.964 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
21:20:38.966 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size or default parameters
21:20:38.966 [main] WARN net.schmizz.sshj.DefaultConfig - Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
21:20:38.966 [main] DEBUG net.schmizz.sshj.DefaultConfig - Available cipher factories: [aes128-cbc, aes128-ctr, blowfish-cbc, cast128-cbc, cast128-ctr, idea-cbc, idea-ctr, serpent128-cbc, serpent128-ctr, 3des-cbc, 3des-ctr, twofish128-cbc, twofish128-ctr, arcfour, arcfour128]
21:20:38.986 [main] INFO net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.27.0
21:20:38.995 [main] INFO net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
21:20:38.995 [main] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `null`
21:20:38.996 [main] DEBUG net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_KEXINIT
21:20:39.002 [main] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `SOME`
21:20:39.003 [main] DEBUG net.schmizz.concurrent.Promise - Awaiting <<kex done>>
21:20:39.004 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
21:20:39.005 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=curve25519-sha256@libssh.org; sig=ecdsa-sha2-nistp256; c2sCipher=aes128-ctr; s2cCipher=aes128-ctr; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
21:20:39.063 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
21:20:39.076 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
21:20:39.076 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Received SSH_MSG_KEXDH_REPLY
21:20:39.077 [reader] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-120, 28, 58, -40, -34, 20, -57, 72, -37, -59, -44, 100, 46, -117, -88, -14, -76, 15, 55, -101, 33, 49, 72, -6, 52, 7, -37, -41, 50, 100, 102, -27]
y: [-44, 73, 121, 105, -71, -104, 64, -117, 62, 117, -52, 106, -115, -122, 127, 33, 27, 65, -91, -111, 111, -89, -126, -114, -64, -4, -36, -114, 70, 39, 10, -61]
21:20:39.194 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with OpenSSHKnownHosts{khFile='C:\Users\Administrator\.ssh\known_hosts'}
21:20:39.195 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with OpenSSHKnownHosts{khFile='C:\Users\Administrator\.ssh\known_hosts2'}
21:20:39.196 [reader] ERROR net.schmizz.sshj.transport.KeyExchanger - Disconnecting because none of the configured Host key verifiers ([OpenSSHKnownHosts{khFile='C:\Users\Administrator\.ssh\known_hosts'}, OpenSSHKnownHosts{khFile='C:\Users\Administrator\.ssh\known_hosts2'}]) could verify 'ecdsa-sha2-nistp256' host key with fingerprint eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d for 192.168.1.142:22
21:20:39.198 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
net.schmizz.sshj.transport.TransportException: Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:211)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:365)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decodeMte(Decoder.java:159)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:79)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:231)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
21:20:39.198 [reader] INFO net.schmizz.sshj.transport.TransportImpl - Disconnected - HOST_KEY_NOT_VERIFIABLE
21:20:39.198 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Got notified of net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
21:20:39.199 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl$NullService - Notified of net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
21:20:39.199 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Setting active service to null-service
21:20:39.199 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Sending SSH_MSG_DISCONNECT: reason=[HOST_KEY_NOT_VERIFIABLE], msg=[Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22]
21:20:39.199 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<transport close>> to `SOME`
21:20:39.199 [reader] DEBUG net.schmizz.sshj.transport.Reader - Stopping
21:20:39.204 [main] ERROR net.schmizz.concurrent.Promise - <<kex done>> woke to: net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:211)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:365)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decodeMte(Decoder.java:159)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:79)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:231)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
`

**Comment by a250152** [comment]
the code 
`SSHClient ssh = new SSHClient();
            ssh.loadKnownHosts();
            ssh.connect("192.168.1.142");
            ssh.authPassword("root", "root");`

**Comment by hierynomus** [comment]
Quick guess, you have not enabled high strength crypto extensions for java.

**Comment by a250152** [comment]
like 'Security.addProvider(new BouncyCastleProvider());'?

**Comment by hierynomus** [comment]
No, not just that. The providers can only provide the crypto strength allowed by the JVM. Also see: https://stackoverflow.com/questions/42159690/why-are-the-jce-unlimited-strength-not-included-by-default

**Comment by a250152** [comment]
i have to update jdk1.8.0-60 to jdk  jdk1.8.0_201 and open the crypto strength
`23:56:37.097 [main] INFO net.schmizz.sshj.transport.random.BouncyCastleRandom - Generating random seed from SecureRandom.
23:56:37.107 [main] DEBUG net.schmizz.sshj.transport.random.BouncyCastleRandom - Creating random seed took 7 ms
23:56:37.165 [main] DEBUG net.schmizz.sshj.DefaultConfig - Available cipher factories: [aes128-cbc, aes128-ctr, aes192-cbc, aes192-ctr, aes256-cbc, aes256-ctr, blowfish-cbc, blowfish-ctr, cast128-cbc, cast128-ctr, idea-cbc, idea-ctr, serpent128-cbc, serpent128-ctr, serpent192-cbc, serpent192-ctr, serpent256-cbc, serpent256-ctr, 3des-cbc, 3des-ctr, twofish128-cbc, twofish128-ctr, twofish192-cbc, twofish192-ctr, twofish256-cbc, twofish256-ctr, twofish-cbc, arcfour, arcfour128, arcfour256]
23:56:39.012 [main] INFO net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.27.0
23:56:39.025 [main] INFO net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
23:56:39.026 [main] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `null`
23:56:39.026 [main] DEBUG net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_KEXINIT
23:56:39.054 [main] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `SOME`
23:56:39.055 [main] DEBUG net.schmizz.concurrent.Promise - Awaiting <<kex done>>
23:56:39.056 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
23:56:39.056 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=curve25519-sha256@libssh.org; sig=ecdsa-sha2-nistp256; c2sCipher=aes128-ctr; s2cCipher=aes128-ctr; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
23:56:39.121 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
23:56:39.135 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
23:56:39.135 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Received SSH_MSG_KEXDH_REPLY
23:56:39.136 [reader] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-120, 28, 58, -40, -34, 20, -57, 72, -37, -59, -44, 100, 46, -117, -88, -14, -76, 15, 55, -101, 33, 49, 72, -6, 52, 7, -37, -41, 50, 100, 102, -27]
y: [-44, 73, 121, 105, -71, -104, 64, -117, 62, 117, -52, 106, -115, -122, 127, 33, 27, 65, -91, -111, 111, -89, -126, -114, -64, -4, -36, -114, 70, 39, 10, -61]
23:56:39.256 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with OpenSSHKnownHosts{khFile='C:\Users\Administrator\.ssh\known_hosts'}
23:56:39.256 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with OpenSSHKnownHosts{khFile='C:\Users\Administrator\.ssh\known_hosts2'}
23:56:39.257 [reader] ERROR net.schmizz.sshj.transport.KeyExchanger - Disconnecting because none of the configured Host key verifiers ([OpenSSHKnownHosts{khFile='C:\Users\Administrator\.ssh\known_hosts'}, OpenSSHKnownHosts{khFile='C:\Users\Administrator\.ssh\known_hosts2'}]) could verify 'ecdsa-sha2-nistp256' host key with fingerprint eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d for 192.168.1.142:22
23:56:39.260 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
net.schmizz.sshj.transport.TransportException: Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:211)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:365)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decodeMte(Decoder.java:159)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:79)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:231)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
23:56:39.260 [reader] INFO net.schmizz.sshj.transport.TransportImpl - Disconnected - HOST_KEY_NOT_VERIFIABLE
23:56:39.260 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Got notified of net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
23:56:39.260 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl$NullService - Notified of net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
23:56:39.260 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Setting active service to null-service
23:56:39.260 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Sending SSH_MSG_DISCONNECT: reason=[HOST_KEY_NOT_VERIFIABLE], msg=[Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22]
23:56:39.261 [main] ERROR net.schmizz.concurrent.Promise - <<kex done>> woke to: net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
23:56:39.261 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<transport close>> to `SOME`
23:56:39.263 [reader] DEBUG net.schmizz.sshj.transport.Reader - Stopping
net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `eb:c9:6f:5e:6d:a7:06:c2:51:b7:d3:e9:47:79:73:7d` for `192.168.1.142` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:211)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:365)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decodeMte(Decoder.java:159)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:79)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:231)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
`

**Comment by a250152** [comment]
more then "aes256-cbc....."

**Comment by a250152** [comment]
@hierynomus 
`SSHClient ssh = new SSHClient();
            ssh.addHostKeyVerifier(new PromiscuousVerifier());
            ssh.connect("192.168.1.142");
            ssh.authPassword("root", "1q2w3e4r");`
I fogot to add this line: ssh.addHostKeyVerifier(new PromiscuousVerifier()); and now it works
