### ISSUE TITLE
Issue generating PublicKey using ECDSAVariationsAdapter

### ISSUE THREAD

**Issue by jonathanjt** [hierynomus/sshj#531]
When doing a simple hard-coded PublicKey generation like this:
```
byte[] key_bytes = new byte[ 0 ];
try {
	key_bytes = Base64.decode( <a valid key> );
}
catch ( IOException e ) {
	e.printStackTrace();  // TODO!
}
// this is the correct type for the key above
KeyType key_type = KeyType.fromString( "ecdsa-sha2-nistp256" );
try {
	PublicKey key = key_type.readPubKeyFromBuffer( new Buffer.PlainBuffer( key_bytes ) ) );
}
catch ( GeneralSecurityException e ) {
	System.out.println( "key fail" + " " + e.getMessage() );
}
```
prints out 
"java.security.GeneralSecurityException: Unknown curve ecdsa-sha2-nistp256"

Which is the failure from the the internal
_static PublicKey readPubKeyFromBuffer(Buffer<?> buf, String variation)_ 

```
if (!SUPPORTED_CURVES.values().contains(curveName)) {
    throw new GeneralSecurityException(String.format("Unknown curve %s", curveName));
}
```
Which is odd because the KeyType is clearly created, yet says unknown....

**Comment by jonathanjt** [comment]
I'll leave the issue up in case it actually turns out to be a bug, but I've worked around it by just using bouncycastle/java.security directly instead

**Comment by hierynomus** [comment]
The `curveName` field in your key contains `ecdsa-sha2-nistp256`, which is not the curvename but the key type name. The curve name should be `nistp256`. 

In the SSHJ code, the first field (key-type) is already read from the buffer before passing it into the `KeyType.readPubKeyFromBuffer`

So what you should be doing is:

```
Buffer.PlainBuffer buf = new Buffer.PlainBuffer(key_bytes);
String keyType = buf.readString();
PublicKey k = KeyType.fromString(keyType).readPubKeyFromBuffer(buf);
``` 

The other option is using:

```
Buffer.PlainBuffer buf = new Buffer.PlainBuffer(key_bytes);
PublicKey k = buf.readPublicKey();
```
```

**Comment by jonathanjt** [comment]
Ok so I was the idiot :) 
Thanks for clarifying that!
