### ISSUE TITLE
Add support to load private keys using InputStream/URL

### ISSUE THREAD

**Issue by breathermachine** [hierynomus/sshj#556]
I have a jar file that packages the encrypted private key file. Running the jar exploded works fine (on a tomcat container, for instance) because the key file is locatable using `new File()` but running it using `java -jar <jarfile>` fails.

**Comment by hierynomus** [comment]
There is a `FileKeyProvider.init(Reader reader)` method, which allows you to use a Reader for the public/private keypair. You could get a reader using `new InputstreamReader(Thread.currentThread().getContextClassLoader().getResourceAsStream(...))`

Does that answer the question?

**Comment by breathermachine** [comment]
Yup, I believe this will do! I was using an old version, 0.3.1. `FileKeyProvider` only had `void init(File location)` and `void init(File location, PasswordFinder pwdf)`
