### ISSUE TITLE
Cannot decode keytype ssh-dss in openssh-key-v1 files (yet).

### ISSUE THREAD

**Issue by georgiikharlampiiev-tw** [hierynomus/sshj#557]
I can see this error when I try to connect with a private key

`ssh = getSSHClient();`
`ssh.connect(myConfig.getHost(), myConfig.getPort());`
`ssh.authPublickey(myConfig.getUser(), ssh.loadKeys(myConfig.getPrivateKey(), null, null));`

And see this error `Cannot decode keytype ssh-dss in openssh-key-v1 files (yet).`

Do you have a plan to add this?

**Comment by hierynomus** [comment]
@georgiikharlampiiev-tw Though it's possible to add, these key types have been deprecated since 2015. See: https://www.archlinux.org/news/openssh-70p1-deprecates-ssh-dss-keys/

**Comment by hierynomus** [comment]
Closing this, as this keytype has been deprecated very long ago...
