### ISSUE TITLE
SFTP Rename with flags (atomic)

### ISSUE THREAD

**Issue by ahweis** [hierynomus/sshj#563]
The default SSH rename command do not sent any flags for how to handle the rename. In the SSH spec it is possible to send the three flags:

SSH_FXF_RENAME_OVERWRITE  0x00000001
SSH_FXF_RENAME_ATOMIC     0x00000002
SSH_FXF_RENAME_NATIVE     0x00000004

At the last uint32 part of the rename command. Will it be possible to extend the rename function to support a list of flags to include (default to 0) or create an overloaded function that supports this.

**Comment by lucamilanesio** [comment]
@ahweis what happened to this issue? I provided a possible solution with the associated PR, can you have a look if that makes sense?
