### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by uglywizkid** [hierynomus/sshj#568]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/app-1.0.0/lib/bcprov-jdk15on-1.60.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
I think this needs fix. Probably a Java 12 / 13 issue.

**Comment by hierynomus** [comment]
As you can see, this is a dependency for us, not our code. Please report this at BC.

**Comment by uglywizkid** [comment]
I do not exactly agree. It is your code and you are responsible for the dependencies you are using. So it is probably your job to report this at BC or find library that works.

**Comment by uglywizkid** [comment]
https://github.com/bcgit/bc-java/issues/669

**Comment by hierynomus** [comment]
@uglywizkid If there is a new version I'm more than happy to test it and see whether it fixes problem, and/or breaks other stuff.
However Just an "I think this needs a fix" message, is not something that makes me want to fix this asap.

You could for instance drop the latest release of bouncy castle in, and see if that fixes it. Also kindly give me a reproduction scenario.

**Comment by uglywizkid** [comment]
@hierynomus I agree with what you are saying. I'll be happy to support you.

**Comment by uglywizkid** [comment]
I did override the bouncycastle dependency version in our application with the following gradle directives:
```
configurations.all {
  resolutionStrategy {
    force("org.bouncycastle:bcprov-jdk15on:1.64")
    force("org.bouncycastle:bcpkix-jdk15on:1.64")
  }
}
```

With these versions the warnings seems to have disappeared. May I ask you to test the latest versions of bouncycastle? Or can I support you in anyway?

**Comment by hierynomus** [comment]
Upgraded to BC 1.65. This should fix this.
