### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [hierynomus/sshj#572]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

Why Spongy Castle yet? For the dead project?
- https://github.com/hierynomus/sshj/search?q=spongy&unscoped_q=spongy

**Comment by Neustradamus** [comment]
@hierynomus: Thanks but can you remove Sponcy Castle from the code?
- https://github.com/hierynomus/sshj/search?q=spongy&unscoped_q=spongy

**Comment by hierynomus** [comment]
@Neustradamus Why is that necessary? There are Android developers depending on Spongy Castle with SSHJ, or does BC nowadays work on Android?

**Comment by Neustradamus** [comment]
@hierynomus: Thanks for your comment!
Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by Neustradamus** [comment]
@hierynomus: Thanks for your comment!
Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by hierynomus** [comment]
Yes, I would prefer to tackle this in another issue, and first release with the SC code still in there. There are many changes in the current master, and I don't know which (if any) consumers of SSHJ still depend on SC.

**Comment by hierynomus** [comment]
Please create a separate issue to track this.

**Comment by Neustradamus** [comment]
@hierynomus: Can you update Bouncy Castle to 1.69?
