### ISSUE TITLE
Release 0.28.0 (or 0.27.1)

### ISSUE THREAD

**Issue by werehuman** [hierynomus/sshj#573]
There have been fixed many bugs since one years old v0.27.0. It would be convenient for users of the library if all that fixes are available in maven central repository. Do you mind releasing a new version?

**Comment by hierynomus** [comment]
I will try to do that this week. Thanks for the reminder!

Op di 14 apr. 2020 om 05:49 schreef Vladimir Lagunov <
notifications@github.com>:

**Comment by pgp** [comment]
Hi, the version 0.28.0 is not yet available on maven central. Any plan to release it?

**Comment by hierynomus** [comment]
Yes, was working on it, but ran into some problem releasing to bintray. Need to fix that

**Comment by hierynomus** [comment]
@pgp @werehuman 0.29.0 is released.
