### ISSUE TITLE
Disable Known Host Checking

### ISSUE THREAD

**Issue by MaxMaeder** [hierynomus/sshj#582]
Is there a way to disable known host checking?

**Comment by dhubbard-ic** [comment]
You can use the PromiscuousVerifier as per [KeepAlive example](https://github.com/hierynomus/sshj/blob/master/examples/src/main/java/net/schmizz/sshj/examples/KeepAlive.java)

```
        final SSHClient ssh = new SSHClient(defaultConfig);
        try {
            ssh.addHostKeyVerifier(new PromiscuousVerifier());`
``

**Comment by MaxMaeder** [comment]
Many thanks!
