### ISSUE TITLE
Support for SHA-256/512 with ssh-rsa keys

### ISSUE THREAD

**Issue by FabianHenneke** [hierynomus/sshj#588]
It would be great if support for the modern [`rsa-sha2-256` and `rsa-sha2-512` signature types](https://tools.ietf.org/html/rfc8332) could be added. Currently, RSA keys are limited to SHA1.

I would work on this myself, but I do not know how to implement this cleanly. The current design seems to be based on the assumption that there is a 1-to-1 mapping between key types and signature types. If you can provide me with a rough sketch of how this could be fit into the code, I would execute the plan when I have time.

**Comment by hierynomus** [comment]
Definitely a good idea, I'll have a look. Would you prefer a release before this?

**Comment by FabianHenneke** [comment]
If it wouldn't require too much work on your part, I would. I'm currently working on Android Keystore-backed SSH keys for [Password Store](https://github.com/android-password-store/Android-Password-Store) based on my PRs that have already been merged, whereas SHA-256/512 support is something that Password Store could use without any changes to our code.

**Comment by hierynomus** [comment]
@FabianHenneke I added these to #589.

**Comment by FabianHenneke** [comment]
Thanks for the quick implementation, that looks pretty good!
