### ISSUE TITLE
What does AuthKeyboardInteractive do?

### ISSUE THREAD

**Issue by MaxMaeder** [hierynomus/sshj#597]
Hi!
I'm seeing `AuthKeyboardInteractive` in a lot of code samples, but I can't seem to find any documentation on what it does or how it's different from `AuthPassword`. Any help would be appreciated.

Thanks!

**Comment by hierynomus** [comment]
I think the best explanation can be found on: https://superuser.com/questions/894608/ssh-o-preferredauthentications-whats-the-difference-between-password-and-k/894625
