### ISSUE TITLE
Caused by: java.io.IOException: Could not load known_hosts at net.schmizz.sshj.SSHClient.loadKnownHosts(SSHClient.java:636) at

### ISSUE THREAD

**Issue by saravanakumarvijayakumar** [hierynomus/sshj#604]
I am facing the below exception in my STG environment. 
Caused by: java.io.IOException: Could not load known_hosts at net.schmizz.sshj.SSHClient.loadKnownHosts(SSHClient.java:636) at

But from my local, It is not reporducible. , I am using the same host and port, username and password. I am using the below code. Could you please let me know How this issue to be fixed?

```
        sshClient = new SSHClient();
        sshClient.setTimeout(timeout);
        sshClient.loadKnownHosts();
        sshClient.addHostKeyVerifier(new PromiscuousVerifier());
        sshClient.connect(hostName, port);
        sshClient.authPassword(username, password);
        sftpClient = sshClient.newSFTPClient();
```

**Comment by hierynomus** [comment]
The `known_hosts` file is on your local(client) machine and contains the hosts the machine knows and can verify the fingerprints from. If that file does not exist, the `loadKnownHosts` call throws this exception. You can use either `loadKnownHosts` or add the `PromiscuousVerifier`, doing both is not the right way.

**Comment by hannah23280** [comment]
> sshClient.addHostKeyVerifier(new PromiscuousVerifier());

@hierynomus ,  you mention "doing both is not the right way".   possible to share  what is the correct way?

**Comment by hierynomus** [comment]
It depends on what you want... i.e. the `PromiscuousVerifier` will accept any host key, regardless of whether the key has changed or it's in you `known_hosts` file. So if you set that as a HostKeyVerifier, it will always accept all host keys.
