### ISSUE TITLE
Error while running `InMemoryKnownHosts`: an enclosing instance that contains `OpenSSHKnownHosts.EntryFactory` is required

### ISSUE THREAD

**Issue by oakkitten** [hierynomus/sshj#626]
I'm trying to load known hosts from memory. This code from the example produces `error: an enclosing instance that contains OpenSSHKnownHosts.EntryFactory is required`.

https://github.com/hierynomus/sshj/blob/0e0d730bbff7eaf911fe8ef0faf072cca0f02211/examples/src/main/java/net/schmizz/sshj/examples/InMemoryKnownHosts.java#L36

The reason is that `EntryFactory` is not a static class. 

https://github.com/hierynomus/sshj/blob/0e0d730bbff7eaf911fe8ef0faf072cca0f02211/src/main/java/net/schmizz/sshj/transport/verification/OpenSSHKnownHosts.java#L193

I'm not familiar with the codebase but perhaps it would simplify things if `OpenSSHKnownHosts` accepted streams as well as `File`s?

**Comment by hierynomus** [comment]
I've added a constructor to `OpenSSHKnownHosts` which takes a `java.io.Reader`. This should solve your issue.
