### ISSUE TITLE
authenticate using RSA certificates

### ISSUE THREAD

**Issue by lemont80** [hierynomus/sshj#634]
Hello @hierynomus , thank you very much for this library. Interested to use this. This may not be an issue but I would like to ask thoug, do you have an example on how to use user authentication using RSA certificates?

**Comment by dkocher** [comment]
Not sure if this is resolved with #702.

**Comment by vladimirlagunov** [comment]
Since #702 was merged to master, you need only to specify a path to a _private_ key in `SSHClient.loadKeys`. If "{keyname}-cert.pub" file exists and it is in the same directory as "{keyname}", it should work.

**Comment by hierynomus** [comment]
Closing this due to merge of #702
