### ISSUE TITLE
Need to get/set Key Exchange algorithm for SSHClient

### ISSUE THREAD

**Issue by zlgonzalez** [hierynomus/sshj#640]
It doesn't look like there is a way to set/get the Key Exchange algorithm in sshj like we can for jsch like as follows:

java.util.Properties config = new java.util.Properties();
config.put("key", "some value");

JSch jsch = new JSch();
Session session = jsch.getSession(user, host, port);
session.setConfig(config);

**Comment by hierynomus** [comment]
SSHJ uses a different API than Jsch, but it is certainly possible to configure it to use a specific Key Exchange Algorithm. FOr instance:

```
Config c = new DefaultConfig();
c.setKeyExchangeFactories(new ECDHNistP.Factory521());
SSHClient client = new SSHClient(c);
```

**Comment by zlgonzalez** [comment]
Thanks for clarifying. Seems like lack of knowledge on my part so closing this ticket.
