### ISSUE TITLE
Is RFC 8332 supported?

### ISSUE THREAD

**Issue by mpet** [hierynomus/sshj#646]
Hi,

Is this supported in this client?

https://tools.ietf.org/html/rfc8332

//mike

**Comment by hierynomus** [comment]
Hi Mike,

Yes, both `ssh-rsa2-256`, and `ssh-rsa2-512` are supported as signature/key algorithms.

**Comment by hierynomus** [comment]
Do you have enough information? If so, can you close your issue?
