### ISSUE TITLE
Parameter cannot be used as HashMap key (missing #hashCode, #equals, #toString)

### ISSUE THREAD

**Issue by ghostcity** [hierynomus/sshj#653]
I'd like to use the local port forwarding's parameter type as a HashMap's key. Since the type (currently) does not contain the "Java boilerplate" #hashCode #equals, and #toString, it cannot be used as an according key.

The solution is quite simple -- I will offer such methods as a merge request.

**Comment by hierynomus** [comment]
Merged #653
