### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [hierynomus/sshj#657]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by hierynomus** [comment]
Fixed with c05c330

**Comment by Neustradamus** [comment]
@hierynomus: Thanks!

**Comment by Neustradamus** [comment]
@hierynomus: Can you update to 1.69?

**Comment by hierynomus** [comment]
I've upgraded it. Can you next time open up a new issue, instead of commenting on 2 closed ones? It makes it easier to keep track of it.
