### ISSUE TITLE
Start two new sshclient, and then open their shell. It is found that only one can execute, and the output stream of the other has no output! When closing one, the other can output

### ISSUE THREAD

**Issue by zhangfanv** [hierynomus/sshj#663]
SSHClient ssh = getNewClient(conn);
        Session session = ssh.startSession();
        session.allocateDefaultPTY();
        Session.Shell shell = session.startShell();

**Comment by hierynomus** [comment]
Can you be a bit more specific? What does `getNewClient` do? Can you give a reproducible testcase against our docker images?

**Comment by zhangfanv** [comment]
private SSHClient getNewClient(Connection conn) throws NullFieldException, IOException {
        Utils.validateNotNull(conn);
        SSHClient ssh = null;
        try {
            ssh = new SSHClient(DEFAULT_CONFIG);
            ssh.addHostKeyVerifier(new PromiscuousVerifier());
            ssh.connect(conn.getHost(), conn.getPort());
            ssh.getConnection().getKeepAlive().setKeepAliveInterval(5);
            if (conn.getAuthType() == AuthType.PWD) {
                ssh.authPassword(conn.getUserName(), conn.getPassword());
            } else {
                if (conn.getPrivateKeyPath() == null) {
                    throw new NullFieldException("Private key file must not empty");
                }
                if (!new File(conn.getPrivateKeyPath()).exists()) {
                    throw new IOException("Private key file path is invalid");
                }
                BaseFileKeyProvider keyFile;
                if (this.getPrivateKeyType(conn) == PrivateKeyType.OPENSSH) {
                    keyFile = new OpenSSHKeyFile();
                } else {
                    keyFile = new PuTTYKeyFile();
                }
                if (conn.getPrivateKeyPassphrase() != null) {
                    PasswordFinder finder = PasswordUtils.createOneOff(conn.getPrivateKeyPassphrase().toCharArray());
                    keyFile.init(new File(conn.getPrivateKeyPath()), finder);
                } else {
                    keyFile.init(new File(conn.getPrivateKeyPath()));
                }
                ssh.authPublickey(conn.getUserName(), keyFile);
            }
        } catch (IOException e) {
            ssh.disconnect();
            LOGGER.error(e.getMessage());
            throw e;
        }
        return ssh;
    }

**Comment by zhangfanv** [comment]
sorry，this is not issue, reason is my threadpool full，task enter queue
