### ISSUE TITLE
Does this support des-cbc? 

### ISSUE THREAD

**Issue by bobsag** [hierynomus/sshj#666]
@hierynomus  I know it supports 3des-cbc but does it support des-cbc?

**Comment by hierynomus** [comment]
Currently it does not, do you know which server/appliance supports that?

Adding it shouldn't be too hard if you require it.

Op do 11 feb. 2021 08:48 schreef bobsag <notifications@github.com>:

**Comment by bobsag** [comment]
Thanks for your response.

I found that Jsch supports it.
But on hindsight, I think I can do without it, it's outdated anyways.

Thanks!
