### ISSUE TITLE
Any way to test if ssh user can execute program?

### ISSUE THREAD

**Issue by SuperPat45** [hierynomus/sshj#668]
I need to evaluate if an SSH user has enough right to execute a particular program without trying to execute it.

Are the any way to do such test?

Currently, I can only test if the program exists:  
`try (SFTPClient sftp = ssh.newSFTPClient())`  
`{`  
 `if (sftp.statExistence(programToTest) == null) // If program not exists?`  
 `// ...`  
`}`

**Comment by hierynomus** [comment]
With the returned `FileAttributes` from this call, you can inspect whether the `x` bit is set to see whether it is executable and by whom. You can find the UID that is the owner. The only thing you need to find out is your own UID, which you could do using a call to `id -u` for instance.

**Comment by SuperPat45** [comment]
Thanks
