### ISSUE TITLE
The examples don't compile!

### ISSUE THREAD

**Issue by mmoser18** [hierynomus/sshj#673]
I am looking for an SSH library for Java and wanted to take a look at SSHJ. 
Unfortunately the provided examples don't even compile, which doesn't exactly make for a very encouraging impression when deciding whether to use this library or not.

Are the examples not maintained anymore? Their dependency was still at v0.24.0, while the library is at v0.31.0 now. As an attempt I adapted the version number in the examples' pom.xml which eliminated one error, but three more remain.

2 errors in net.schmizz.sshj.examples.LocalPF refer to LocalPortForwarder.Parameters which doesn't seem to exist anymore.

The last error is in class net.schmizz.sshj.examples.InMemoryKnownHosts - line 36:
The compiler doesn't like the "new OpenSSHKnownHosts.EntryFactory();" here and mumbles:
"No enclosing instance of type OpenSSHKnownHosts is accessible. Must qualify the allocation with an enclosing instance of type OpenSSHKnownHosts (e.g. x.new A() where x is an instance of OpenSSHKnownHosts)."
That's because OpenSSHKnownHosts.EntryFactory is not a static class but a local class of OpenSSHKnownHosts. Hence no object can be instantiated outside of class OpenSSHKnownHosts.

So - it seems - the library evolved but the examples were not adapted.

**Comment by hierynomus** [comment]
Hi mmoser18,

I've just fixed the examples. Thanks for notifying me. If you want more
examples, I would recommend having a look at the integration tests also.

Best regards,
jeroen

Op za 27 mrt. 2021 om 22:09 schreef mmoser18 ***@***.***>:
