### ISSUE TITLE
Invalid module name: asn-one is not a Java identifier

### ISSUE THREAD

**Issue by avarsava** [hierynomus/sshj#678]
Hello,

I am using sshj in a Java 14 application and I faced an issue getting my code to run.

```
java.lang.module.FindException: Unable to derive module descriptor for <project>/target/dependency/asn-one-0.5.0.jar
Caused by: java.lang.module.FindException: Automatic-Module-Name: com.hierynomus.asn-one: Invalid module name: 'asn-one' is not a Java identifier
```

I had to unpack the dependency jar, edit 'META-INF/MANIFEST.MF' to remove the '-' from the name, and repackage the jar to clear the error.

Thought you should know, and would appreciate any tips about working around this for future builds.

**Comment by robertgates55** [comment]
Just hit the same thing!
