### ISSUE TITLE
Can SSHJ create any OpenSSH keys?

### ISSUE THREAD

**Issue by mwarning** [hierynomus/sshj#684]
Hi,

I am happy that SSHJ can read OpenSSH keys. But is it possible to generate (ed25519 or other)  keys as well?
Any pointer to how this can be achieved on Android programmatically would also be much appreciated.

**Comment by hierynomus** [comment]
@mwarning No, currently SSHJ doesn't do that.

**Comment by mwarning** [comment]
ok, thank you.
