### ISSUE TITLE
Multiplexing via ssh_config

### ISSUE THREAD

**Issue by nickcaballero** [hierynomus/sshj#689]
In my .ssh/config file I have set Control(Master,Path,Persist) properties to skip MFA on subsequent connections. When a ControlPath is established from CLI via ssh, does sshj make use of the existing connection to multiplex?

This article explains it pretty well: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing

**Comment by hierynomus** [comment]
@nickcaballero As long as you use the same `SSHClient`, you can multiplex multiple sessions over the connection that is established. Once you close (or dispose of) the `SSHClient`, the connection is no longer there, so a new connection needs to be established.

**Comment by hierynomus** [comment]
@nickcaballero Does this answer your question?

**Comment by hierynomus** [comment]
Going to close this issue due to lack of response. If there's anything else, feel free to reopen the ticket.
