### ISSUE TITLE
all file types not exposed in RemoteResourceInfo

### ISSUE THREAD

**Issue by dlaflamme** [hierynomus/sshj#693]
SFTPClient.ls() returns a list of RemoteResourceInfo objects. RemoteResourceInfo exposes isDirectory and isFile, but includes no accessors for the other types defined in FileMode. Is there any reason for this? Would you be opposed to exposing them all in RemoteResourceInfo?

**Comment by hierynomus** [comment]
The `isRegularFile` and `isDirectory` are just shortcut methods for the most commonly used things you want to know about a `RemoteResource`. 

For all other inquiries on the `Type`, you can do `RemoteResourceInfo.getAttributes().getType()` or if you want to get the detailed `FileMode`, you can do `RemoteResourceInfo.getAttributes().getMode()`. 

So in short, I see no reason to add more shortcut methods, as all the info is already exposed. 

Does that answer your question?

**Comment by dlaflamme** [comment]
Yes, it answers my question, thank you. I discovered RemoteResourceInfo.getAttributes().getType() after I posted the original question and agree that it exposes what I am looking for.
