### ISSUE TITLE
Is there a way to keep alive SFTPClient session

### ISSUE THREAD

**Issue by intr** [hierynomus/sshj#694]
Hi, I am required to keep sftp session alive, but I get java.net.SocketException: Connection reset and net.schmizz.sshj.TransportException: Socket closed when I open my SFTP session for more than a few minutes.
Is there a way to keep alive SFTPClient session?

**Comment by hierynomus** [comment]
Yes, you can use `config.setKeepAliveProvider(KeepAliveProvider.KEEP_ALIVE);`

**Comment by intr** [comment]
Thank you, @hierynomus !

**Comment by hierynomus** [comment]
Can you close the issue if this has solved your question?
