### ISSUE TITLE
Fix High Security Vulnerabilities Related to Java.Security package

### ISSUE THREAD

**Issue by iamgollum** [hierynomus/sshj#697]
Observation:

```
java.security.MessageDigest.getInstance(java.lang.String;java.lang.String):java.security.MessageDigest
```

Locations:

```
--> net.schmizz.sshj.common.SecurityUtils.getMessageDigest(String):MessageDigest:222
--> net.schmizz.sshj.common.SecurityUtils.registerSecurityProvider(String):boolean:93
--> net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.verify(String):void:287
--> net.schmizz.sshj.common.SecurityUtils.registerSecurityProvider(String):boolean:93
```

These vulnerabilities were mostly publicly filed on June 21st, 2021.

Action:

Update `java.security` to resolve security vulnerability.

**Comment by hierynomus** [comment]
Can you explain the vulnerability and which cve is attached to it?

**Comment by iamgollum** [comment]
@hierynomus the core of the issue is the algorithm is insecure. 

net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.toKey(String):byte[]:257
-> java.security.MessageDigest.getInstance(String):MessageDigest
--> getInstance("SHA-1")

Here is another one:

-> net.schmizz.sshj.common.SecurityUtils.registerSecurityProvider(String):boolean:93
---> java.security.MessageDigest.getInstance(String;Provider):MessageDigest
-------> getInstance("MD5", provider)

SHA-256 and their variations are the new standard.

**Comment by iamgollum** [comment]
On another related note there also seems to validation issues:



net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile.readKeyPair():KeyPair | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile.readKeyPair():KeyPair
-- | --
net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile.readKeyPair():KeyPair
net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141decode(sb.toString()) |   |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141decode(sb.toString())
  |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141decode(sb.toString())
net.schmizz.sshj.common.Base64:1225decode(s, 0) |   |   |   | net.schmizz.sshj.common.Base64:1225decode(s, 0)
  |   |   | net.schmizz.sshj.common.Base64:1225decode(s, 0)
net.schmizz.sshj.common.Base64:1277length = gzis.read(buffer) |   |   |   |   | net.schmizz.sshj.common.Base64:1277length = gzis.read(buffer)
  |   |   |   | net.schmizz.sshj.common.Base64:1277length = gzis.read(buffer)
net.schmizz.sshj.common.Base64:1278baos.write(buffer, 0, length) |   |   |   |   | net.schmizz.sshj.common.Base64:1278baos.write(buffer, 0, length)
  |   |   |   | net.schmizz.sshj.common.Base64:1278baos.write(buffer, 0, length)
net.schmizz.sshj.common.Base64:1282bytes = baos.toByteArray() |   |   |   |   | net.schmizz.sshj.common.Base64:1282bytes = baos.toByteArray()
  |   |   |   | net.schmizz.sshj.common.Base64:1282bytes = baos.toByteArray()
net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141this.decrypt(decode(sb.toString()), cipher, iv) |   |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141this.decrypt(decode(sb.toString()), cipher, iv)
  |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141this.decrypt(decode(sb.toString()), cipher, iv)
net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141asn = new PKCS5KeyFile$ASN1Data(this, decrypt(decode(sb.toString()), cipher, iv)) |   |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141asn = new PKCS5KeyFile$ASN1Data(this, decrypt(decode(sb.toString()), cipher, iv))
  |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:141asn = new PKCS5KeyFile$ASN1Data(this, decrypt(decode(sb.toString()), cipher, iv))
net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:146modulus = asn.readNext() |   |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:146modulus = asn.readNext()
  |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:146modulus = asn.readNext()
net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:150new RSAPrivateKeySpec(modulus, prvExp) |   |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:150new RSAPrivateKeySpec(modulus, prvExp)
  |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:150new RSAPrivateKeySpec(modulus, prvExp)
net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:150prvKey = factory.generatePrivate(new RSAPrivateKeySpec()) |   |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:150prvKey = factory.generatePrivate(new RSAPrivateKeySpec())
  |   | net.schmizz.sshj.userauth.keyprovider.PKCS5KeyFile:150prvKey = factory.generatePrivate(new RSAPrivateKeySpec())

**Comment by iamgollum** [comment]
@hierynomus I accidentally closed this issue.

**Comment by hierynomus** [comment]
Hi @iamgollum,

Thanks for the explanatory comment. This is exactly why "just" running a static checker over a codebase does not work, or at least leads to false positives.

If you look in the source code for `PuttyKeyFile` there is an explanatory comment why `SHA-1` is used:

```
    /**
     * Converts a passphrase into a key, by following the convention that PuTTY uses.
     * <p/>
     * <p/>
     * This is used to decrypt the private key when it's encrypted.
     */
    private byte[] toKey(final String passphrase) throws IOException {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-1");

            // The encryption key is derived from the passphrase by means of a succession of SHA-1 hashes.
```

and

```
            // The key to the MAC is itself a SHA-1 hash of:
            MessageDigest digest = MessageDigest.getInstance("SHA-1");
            digest.update("putty-private-key-file-mac-key".getBytes());
```

Yes, I'm well aware of the SHA-ttered attack, and the fact that MD-5 can lead to false duplicates. But in libraries such as SSHJ and SMBJ (one of my other side projects), these algorithms are needed because systems you interface with can still use this. 

As for the "validation issue" you quote, what do you mean there?

**Comment by iamgollum** [comment]
@hierynomus I appreciate the the thorough reply and I am going to let my team know that we missed the comments. The backwards compatibility with other systems make sense and its clear that our use of SSHJ does not use these systems based on the call stack anyway so I think I am good there.

Our static analyzer was complaint about:

`net.schmizz.sshj.common.Base64:1277length = gzis.read(buffer)`

has not validation on the bugger before its read. Thats all. 
I think this is also overkill because its just a gzip byte stream which is a generic container.
