### ISSUE TITLE
Encrypted RSA key in OpenSSHKey format results- error in libcrypto

### ISSUE THREAD

**Issue by arpoch** [hierynomus/sshj#705]
I am using sshj library to decrypt an encrypted RSA private key using the code below

```
        OpenSSHKeyV1KeyFile o = new OpenSSHKeyV1KeyFile();
        o.init(ENCRYPTED_RSA, "", new Pass(arr));
        PrivateKey p = o.getPrivate();
        byte[] c = p.getEncoded();
```
The above code works great and results in a decrypted private but to use it for git SSH authentication purpose through command line using `GIT_SSH_COMMAND` environment variable, I am converting the generated PKCS8(from getformat) byte encoded key to PEM and writing it in a temp file using the code below

```
      PemObject po = new PemObject("PRIVATE KEY", c);
      PemWriter pw = new PemWriter(new OutputStreamWriter(new FileOutputStream(tempFile)));
      pw.writeObject(po);
      pw.flush();
      pw.close();
```

But I am getting this error message every time I try to perform any git operation which requires authentication `sign_and_send_pubkey: signing failed: error in libcrypto` only for Encrypted RSA OpenSSH formatted key, I have test over ecdas19 and it works fine.

As I am currently working with
OS- Windows 10
OpenSSH- OpenSSH_for_Windows_8.1p1

**Comment by hierynomus** [comment]
@arpoch How is this an SSHJ issue?

**Comment by arpoch** [comment]
The fingerprint generated of the decrypted private key(SSHJ library to decrypt the key) doesn't match with the actual private key(encrypted) fingerprint. So I believe there is an issue while decrypting an encrypted private key in OpenSSH format using SSHJ.

**Comment by arpoch** [comment]
Forgot to add that the issue is encountered for RSA encrypted openssh formated keys, I have tested with ECDSA and it's working as expected.

**Comment by hierynomus** [comment]
Can you add a test case in a PR? Then we can have a look.

**Comment by arpoch** [comment]
Sure, will try my best.

**Comment by exceptionfactory** [comment]
@arpoch and @hierynomus I traced the issue down to RSA Private Key parsing in `OpenSSHKeyV1KeyFile` and submitted PR #726.

**Comment by hierynomus** [comment]
The mentioned PR #726 has been merged. I'm closing this issue.
