### ISSUE TITLE
Feature request: add abort method to StreamCopier class

### ISSUE THREAD

**Issue by pditommaso** [hierynomus/sshj#71]
There are use cases in which would be useful to abort the copy operation (and the underlying thread).

I would suggest to add StreamCopier # abort() template method that can be overridden providing the required logic to abort the copy operation. For example 

```
new StreamCopier ( source, target ) {
  public boolean abort() {
    return ! session.isOpen();
  }
}.spawn("copier")
```

**Comment by hierynomus** [comment]
Closing this ancient issue, if this is still relevant, please open a fresh one.
