### ISSUE TITLE
For FIPS Enabled machine RSA key is not working 

### ISSUE THREAD

**Issue by Devasish-kundu-sp** [hierynomus/sshj#710]
Hi,

For RHEL 8.0 I had  FIPS mode enabled machine,however RSA key does not work.
If i am creating RSA key in FIPS disabled mode then it works, were as the same RSA key does not work if FIPS enable mode.

Whether RSA key works in FIPS enabled mode for os RHEL 8.0 onward.

Thanks
Devasish

**Comment by Devasish-kundu-sp** [comment]
Just sharing that as per release note of RHEL 8.3 https://linux.web.cern.ch/rhel/releasenotes/Red_Hat_Enterprise_Linux-8-8.3_Release_Notes-en-US.pdf, it is specifying that **ssh-keyscan cannot retrieve RSA keys of servers in FIPS mode.
To work around this problem, use ECDSA keys instead**

**Comment by exceptionfactory** [comment]
Thanks for providing that link @Devasish-kundu-sp. As indicated in the RHEL 8.3 documentation, the *SHA-1* algorithm is disabled in FIPS mode, which would also explain why it won't work with SSHJ.

**Comment by Devasish-kundu-sp** [comment]
thanks closing this
