### ISSUE TITLE
Release 0.32?

### ISSUE THREAD

**Issue by vladimirlagunov** [hierynomus/sshj#720]
Half a year has passed since 0.32. ChaCha20 and certificates were implemented since the latest release.

**Comment by hierynomus** [comment]
Yes, good point! Time flies when you're hard at work 😉 . I'll have a look at the outstanding PRs and push a release.

**Comment by C4J** [comment]
Does this comment mean there is already a 0.32 release available somewhere as I'm using 0.31 and have a problem which I cannot fathom and would like to try an update in case that helps

Thanks

Dave

**Comment by hierynomus** [comment]
@C4J Not yet, hope to get the last testcase for #687 to prove that works, then I'll merge that one in before pushing out a release.

**Comment by hierynomus** [comment]
It's released ;)
