### ISSUE TITLE
Is Java 11 supported with 0.31

### ISSUE THREAD

**Issue by C4J** [hierynomus/sshj#723]
Just wanted to check if it's ok to use Java 11. When building there are some reflection api warnings but they should still work if I understand correctly ?

**Comment by vladimirlagunov** [comment]
Unit tests are verified with Java 12 on every commit. https://github.com/hierynomus/sshj/runs/3686592596?check_suite_focus=true Also, we've been succesfully using sshj in our project on Java 11.

**Comment by C4J** [comment]
Many thanks for that,

Dave

**Comment by hierynomus** [comment]
Closing this as it is answered.
