### ISSUE TITLE
h

### ISSUE THREAD

**Issue by C4J** [hierynomus/sshj#725]

**Comment by C4J** [comment]
I have a java application using 0.31 of your library which performs a "ls" of a remote sftp directory and it works when I run on my MacOS. However when I run on a Windows Machine the "ls" returns no files. I have turned the log up to trace and can provide these but I'm not sure the contents of the hex output which might contain credentials etc.

**Comment by C4J** [comment]
I think I know the problem which comes down to formatting the paths using \ or / which leads me to ask - is it possible to determine the path separators on a remote sftp server ?

**Comment by vladimirlagunov** [comment]
SFTP is a quite messy protocol which has never been released. Both SSHJ and [OpenSSH](https://github.com/openssh/openssh-portable/blob/dc1b45841fb97e3d7f655ddbcfef3839735cae5f/sftp.c#L136) stuck on the ancient [draft 2](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02). The draft even doesn't define a way to get current user and group id, forcing you to use dirty hacks when getting and setting file permissions. And the protocol does not define a way to get the operating system, or the path separator, etc. You have to execute auxiliary commands using exec channels.

**Comment by hierynomus** [comment]
@C4J Did vladimir's answer answer your question?

**Comment by C4J** [comment]
> @C4J Did vladimir's answer answer your question?

Yes thank you
