### ISSUE TITLE
Upload Using InputStream

### ISSUE THREAD

**Issue by allenvpn312** [hierynomus/sshj#734]
Hi, I am relatively new to using sshj and this may be a relatively easy question to answer. 

I have an InputStream and want to create an upload from it.   I only see two put methods.

put(LocalSourceFile file, String destination)
put(String source, String destination)

Is there a way to utilize the InputStream?

Thank you in advance!

**Comment by vladimirlagunov** [comment]
There is also `net.schmizz.sshj.sftp.SFTPClient#open`, and RemoteFile has an output stream. Try something like that:

```java
var remoteFile = sftpClient.open("remote_name.txt", EnumSet.of(CREAT, WRITE));
try (var os = file.RemoteFileOutputStream(0, 10)) {
  IOUtils.copy(inputStream, os);
}
```

**Comment by allenvpn312** [comment]
Here's a simple class to upload/download files using sshj.  If you see areas of improvements, I would love to hear them.

`
public class SFtpClient {

	private String host;

	private String user;
	private String password;

	private SSHClient ssh;
	private SFTPClient sftp;

	public SFtpClient(String host, String user, String password) {
		super();

		this.host = host;
		this.user = user;
		this.password = password;
	}

	public void open() throws IOException {
		ssh = new SSHClient();
		ssh.addHostKeyVerifier(new PromiscuousVerifier());

		ssh.connect(host);
		ssh.authPassword(user, password);

		if (ssh.isAuthenticated()) {
			System.out.println("Authenticated, initializing ftp transmission");

			sftp = ssh.newSFTPClient();
		} else {
			// Close connection and throw authentication error
			ssh.disconnect();
			ssh.close();

			throw new IOException("Authentication failed");
		}
	}

	public void close() throws IOException {
		if (sftp != null)
			sftp.close();
		// Disconnect ssh session
		ssh.disconnect();
		ssh.close();
	}

	public List<RemoteResourceInfo> listFiles(String path) throws IOException {
		var resources = sftp.ls(path);

		return resources;
	}

	public void uploadFile(String destination, InputStream is) throws IOException {
		RemoteFile file = sftp.getSFTPEngine().open(destination, EnumSet.of(OpenMode.CREAT, OpenMode.WRITE));
		OutputStream os = file.new RemoteFileOutputStream(0, 10) {
	
			@Override
			public void close() throws IOException {
				try {
					super.close();
				} finally {
					file.close();
				}
			}
		};
		
		IOUtils.copy(is, os);
	}

	public ByteArrayOutputStream downloadFile(String source) throws IOException {
		ByteArrayOutputStream os = new ByteArrayOutputStream();
		RemoteFile file = sftp.getSFTPEngine().open(source, EnumSet.of(OpenMode.READ));

		InputStream is = file.new RemoteFileInputStream() {

			@Override
			public void close() throws IOException {
				try {
					super.close();
				} finally {
					file.close();
				}
			}
		};

		is.transferTo(os);

		return os;
	}
}
`

@vladimirlagunov, thank you for your input.

**Comment by hierynomus** [comment]
I'll close this issue, as it is solved.

**Comment by ericwgithub** [comment]
The "solution" source code to use IOUtils.copy(is, os) did not work for me.    It did not compile.   I am using sshj-0.38.0.jar.   I was able to upload from a string instead of a file by implementing a class of interface LocalSourceFile and using the put command, using the object of that class as the first parameter.
Here is the class: 
public class StringFakeSourceLocalFile implements LocalSourceFile {

	final String fakeFileName = "fakeFileName"; 
	
	final String stringToFtp;
	
	
	public StringFakeSourceLocalFile(String stringToFtp) {
		
		Validate.isTrue(MyStringUtils.isNotEmpty(stringToFtp), "stringToFtp is empty");
		this.stringToFtp = stringToFtp;
	}
	
	
	
	@Override
	public Iterable<? extends LocalSourceFile> getChildren(LocalFileFilter arg0) throws IOException {
		
		return Collections.emptyList();
	}

	
	
	@Override
	public InputStream getInputStream() throws IOException {
		
		InputStream stringAsStream = new ByteArrayInputStream(this.stringToFtp.getBytes());
		return stringAsStream;
	}

	
	
	@Override
	public long getLastAccessTime() throws IOException {
		
		return new java.util.Date().getTime();
	}

	
	
	@Override
	public long getLastModifiedTime() throws IOException {
		
		return new java.util.Date().getTime();
	}

	
	
	@Override
	public long getLength() {
		
		return this.stringToFtp.length();
	}

	
	
	@Override
	public String getName() {

		return fakeFileName;
	}

	
	
	@Override
	public int getPermissions() throws IOException {
		
		int allPermissions =  0777;
		return allPermissions;
	}

	
	
	@Override
	public boolean isDirectory() {
		
		return false;
	}

	
	
	@Override
	public boolean isFile() {
		
		return true;
	}

	
	
	@Override
	public boolean providesAtimeMtime() {

		return false;
	}
	
	

}
