### ISSUE TITLE
Naming the reader thread

### ISSUE THREAD

**Issue by kz282** [hierynomus/sshj#738]
I would like to ask for a cosmetic change: please allow naming the net.schmizz.sshj.transport.Reader thread.

I am facing some issues during ssh connections and it is hard to find out the internals of the connection as the internal logs contain no specific id of the connection. It would be easier to filter logs based on thread names if the connected device ip address and some other ids could be put into the reader thread name. It could be stored in the net.schmizz.sshj.Config implementations. A Config.getReaderThreadName() and setReaderThreadName(String name) would be nice.

21.11.03 09:35:10.520 INFO  TransportImpl   [reader]: Received SSH_MSG_DISCONNECT (reason=PROTOCOL_ERROR, msg=Too many authentication failures for testuser)
21.11.03 09:35:10.520 ERROR TransportImpl   [reader]: Dying because - Too many authentication failures for testuser
net.schmizz.sshj.transport.TransportException: Too many authentication failures for testuser
        at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:565) ~[sshj-0.31.0.jar:0.31.0]
        at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:521) ~[sshj-0.31.0.jar:0.31.0]
        at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113) ~[sshj-0.31.0.jar:0.31.0]
        at net.schmizz.sshj.transport.Decoder.received(Decoder.java:203) ~[sshj-0.31.0.jar:0.31.0]
        at net.schmizz.sshj.transport.Reader.run(Reader.java:60) ~[sshj-0.31.0.jar:0.31.0]
21.11.03 09:35:10.520 INFO  TransportImpl   [reader]: Disconnected - PROTOCOL_ERROR
21.11.03 09:35:10.520 DEBUG KeyExchanger    [reader]: Got notified of net.schmizz.sshj.transport.TransportException: [PROTOCOL_ERROR] Too many authentication failures for testuser
21.11.03 09:35:10.520 DEBUG UserAuthImpl    [reader]: Notified of net.schmizz.sshj.transport.TransportException: [PROTOCOL_ERROR] Too many authentication failures for testuser
21.11.03 09:35:10.520 DEBUG TransportImpl   [reader]: Setting active service to null-service
21.11.03 09:35:10.521 DEBUG Promise         [reader]: Setting <<transport close>> to `SOME`
21.11.03 09:35:10.521 DEBUG Reader          [reader]: Stopping

**Comment by jkosternl** [comment]
@kz282, can you please close this request, since it was merged already in the past? Otherwise state what is still missing/wrong.

**Comment by hierynomus** [comment]
Closing indeed... Should be checking the git commit messages better for the wording so that the issues get closed automatically ;)

**Comment by kz282** [comment]
Testing with 0.26.0:
2022-10-27 23:38:37.606 TRACE transport.TransportImpl(497) [reader]: Received packet KEXDH_31

Testing with 0.34.0
2022-11-04 10:02:43.461 TRACE transport.TransportImpl(480) [sshj-Reader-/10.1.2.3:22]: Received packet KEXDH_31

Thank you very much!
