### ISSUE TITLE
[ChachaPolyCipher.java][Veracode][CVSS=5.1]Use of a Broken or Risky Cryptographic Algorithm (CWE ID 327)

### ISSUE THREAD

**Issue by zwscn2014** [hierynomus/sshj#744]
Hi, 

There is a new flaw reported by Veracode Scan since I recently upgraded sshj from 0.26.0 to 0.32.0 in my project.

Details of this flaw is as followed:
```
Use of a Broken or Risky Cryptographic Algorithm (CWE ID 327)
Description
The use of a broken or risky cryptographic algorithm is an unnecessary risk that may result in the disclosure of
sensitive information.
Effort to Fix: 1 - Trivial implementation error. Fix is up to 5 lines of code. One hour or less to fix.
Instances found via Static Scan

Path 1: setSequenceNumber, line 64 (1 step)
--
com/hierynomus/sshj/transport/cipher/ChachaPolyCipher.java
```

Some references about this flaws:
https://cwe.mitre.org/data/definitions/327.html
https://github.com/OWASP/www-project-web-security-testing-guide/blob/master/v42/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/04-Testing_for_Weak_Encryption.md Search for IvParameterSpec
https://docs.ostorlab.co/kb/#use-non-random-initialization-vector-iv

May you provide some help on this flaw? 
Also can you please help to justify whether it's a false positive or not? If yes, from my side I can contact Veracode to see if it can be marked as false positive.

**Comment by hierynomus** [comment]
In this case it is a false alert, as for ChaCha20-Poly1305 for SSH you need to set the IV to the packet sequence number.

> The AEAD is constructed as follows: for each packet, generate a Poly1305 key by taking the first 256 bits of ChaCha20 stream output generated using K_2, an IV consisting of the packet sequence number encoded as an uint64 under the SSH wire encoding rules and a ChaCha20 block counter of zero. The K_2 ChaCha20 block counter is then set to the little-endian encoding of 1 (i.e. {1, 0, 0, 0, 0, 0, 0, 0}) and this instance is used for encryption of the packet payload. 

(source: https://tools.ietf.org/id/draft-josefsson-ssh-chacha20-poly1305-openssh-00.html)

In general, yes you would need to set the IV to a sufficiently random number of bytes.

**Comment by zwscn2014** [comment]
> In this case it is a false alert, as for ChaCha20-Poly1305 for SSH you need to set the IV to the packet sequence number.
> 
> > The AEAD is constructed as follows: for each packet, generate a Poly1305 key by taking the first 256 bits of ChaCha20 stream output generated using K_2, an IV consisting of the packet sequence number encoded as an uint64 under the SSH wire encoding rules and a ChaCha20 block counter of zero. The K_2 ChaCha20 block counter is then set to the little-endian encoding of 1 (i.e. {1, 0, 0, 0, 0, 0, 0, 0}) and this instance is used for encryption of the packet payload.
> 
> (source: https://tools.ietf.org/id/draft-josefsson-ssh-chacha20-poly1305-openssh-00.html)
> 
> In general, yes you would need to set the IV to a sufficiently random number of bytes.

@hierynomus Thanks for the answer! I will contact the Veracode Scan team to get rid of this false alert.
