### ISSUE TITLE
Got UnknownHostException even if I use the PromiscuousVerifier

### ISSUE THREAD

**Issue by rsoika** [hierynomus/sshj#747]
I have a strange behaviour using sshj version 0.31.0

I try to connect to a sftp server with a code like this:

```
...
 SSHClient ssh = new SSHClient();
 ssh.addHostKeyVerifier(new PromiscuousVerifier());
 ssh.connect(ftpServer, Integer.parseInt(ftpPort));  // Breaks!
 ssh.authPassword(ftpUser, ftpPassword);
 SFTPClient sftpClient = ssh.newSFTPClient();
 ...
```

This code works well on my local machine (where I have a `known_hosts` file)

Running the code in a Payara Docker image I always got a  `UnknownHostException` exception.
On the payara server there is no `known_hosts` file - can this be the reason?

I thought setting:

     ssh.addHostKeyVerifier(new PromiscuousVerifier());

will accept all server connections? But it did not work inside the docker container. I can not see how to solve this issue....

**Comment by vladimirlagunov** [comment]
Hi! Ensure that it's not a connectivity problem, and that OpenSSH (or psftp.exe from PuTTY) can connect to the server.
Invoke in that Docker image: `sftp -p ftpPort ftpUser@ftpServer`, and try some simple commands like `ls`. Does it work?

**Comment by rsoika** [comment]
On the Payara Docker image there is no ssh or sftp lib available. Does this mean that I can't use the sshj library?

**Comment by vladimirlagunov** [comment]
```
$ docker run --entrypoint= payara/micro:5.2021.1 cat /etc/issue
Welcome to Alpine Linux 3.12
Kernel \r on an \m (\l)
```

It's based on the plain old Alpine Linux. You can install OpenSSH in that containers.

**Comment by vladimirlagunov** [comment]
> Does this mean that I can't use the sshj library?

It doesn't. You can use SSHJ without OpenSSH. I'm just advising how to troubleshoot problems with SSHJ.

**Comment by vladimirlagunov** [comment]
Also, if you can't get into Docker containers, you can try to create a plain old java.net.Socket, connect to ftpHost:ftpPort, and check if the raw socket throws that error.

**Comment by hierynomus** [comment]
Basically `UnknownHostException` means that the networking layer wasn't able to find the host (let alone establish a connection to it)

**Comment by vladimirlagunov** [comment]
And, a bit more clarifications:

> Running the code in a Payara Docker image I always got a UnknownHostException exception.

If it is `java.net.UnknownHostException`, it indicates that DNS fails to look up for ftpHost. I don't remember any class with that name in SSHJ.

> On the payara server there is no known_hosts file - can this be the reason?

No. `known_hosts` is for checking that the server has a known public key, it's for preventing MiTM attacks. Reading of `known_hosts` is involved after instantiating a TCP connection, which seems to not happen in your containers.

**Comment by rsoika** [comment]
ok, I tried it out. But in my case I can't install SSH on my payara image as it is a custom image (build by BMW) which supports no way to install additional libs. And ssh is not part of the container. Does it mean that I can't go ahead with SSHJ ?

**Comment by hierynomus** [comment]
@rsoika No, it means that the SSH host that you're trying to access from the Docker image is not reachable/resolvable. i.e. you should check the networking from the docker image.

SSHJ does not rely on system libraries/applications such as SSH, the only requirement is a Java Runtime

You can try to do a regular `ping <host>` from the Docker container, does that work?

**Comment by rsoika** [comment]
OK - I am now very sorry for my stupid question. 
it was of course a network problem. Everything is working perfect with SSHJ libary. 

This happens when you dig into a problem for hours and no longer see the forest in front of noisy trees....... I am very sorry for taking your time
