### ISSUE TITLE
sftp transfer speed is different scp speed

### ISSUE THREAD

**Issue by melihbirim** [hierynomus/sshj#76]
Hello,

I am using your library version 0.8 for file transfer over sftp. However upload speed over sftp using sshj library does not match normal sftp file transfer.

if I transfer a file 
with ftp speed is 1Mb/s
with sftp using sshj speed is 1Mb/s
with sftp speed is 10Mb/s
with scp speed is 10Mb/s
with scp using sshj speed is 10Mb/s

What migth be the reason for differences?
Thanks

**Comment by mironabr** [comment]
This merge does not exists in the latest  mvn release 0.35.0.
Currently the upload speed using RemoteFileOutputStream is VERY slow!
