### ISSUE TITLE
Setup continuous or more frequent release process

### ISSUE THREAD

**Issue by dkocher** [hierynomus/sshj#776]
It would be great to have more frequent release builds pushed.

**Comment by exceptionfactory** [comment]
GitHub supports publishing [packages](https://docs.github.com/en/packages), which might be a helpful way to provide snapshot builds.

There have also been a number of improvements since 0.32, what do you think about a timeline for a new release @hierynomus?

**Comment by hierynomus** [comment]
Just released 0.34.0 ;)

The release process itself is automated, as long as I push a new tag...
