### ISSUE TITLE
Exec Docker command, Result is null

### ISSUE THREAD

**Issue by rainbowechoes** [hierynomus/sshj#783]
I hava a machine, I want to connect to it to exec some docker command from my app service by ssh.

but when I writed a demo, I found when I use docker command, the command result is null. Like this:

![image](https://user-images.githubusercontent.com/38370475/166471493-b6e44c63-f912-4b27-b996-1d70db2daa66.png)

![image](https://user-images.githubusercontent.com/38370475/166471559-a1dc8b9e-91d8-4157-ac98-906be90f15db.png)

when I exec same command in machine, it will return:

![image](https://user-images.githubusercontent.com/38370475/166471780-dac12c5e-fe94-4023-b5da-2f7664314556.png)

Can I implement same result when I use sshj like use machine?

**Comment by vladimirlagunov** [comment]
[The program from the screenshots reads only stdout, while error messages are usually written to stderr](https://en.wikipedia.org/wiki/Standard_streams). See `net.schmizz.sshj.connection.channel.direct.Session.Command#getErrorStream` and other methods of `Session.Command`. Data from stderr may give a clue why the command doesn't work as expected.

**Comment by rainbowechoes** [comment]
> [The program from the screenshots reads only stdout, while error messages are usually written to stderr](https://en.wikipedia.org/wiki/Standard_streams). See `net.schmizz.sshj.connection.channel.direct.Session.Command#getErrorStream` and other methods of `Session.Command`. Data from stderr may give a clue why the command doesn't work as expected.

thanks for your reply.

I tried add get error stream code, then I get a result like this:

![image](https://user-images.githubusercontent.com/38370475/166632396-0d765df1-ac42-4017-9381-bd99e67a7c30.png)

then I google this error message, found a stackoverflow post: https://stackoverflow.com/questions/47025758/docker-run-it-over-ssh-the-input-device-is-not-a-tty

Is this the right way to proceed? If so, how should I change the configuration of sshj?

**Comment by vladimirlagunov** [comment]
You may add PTY (aka pseudo-TTY, usually called as TTY since you can barely find a physical TTY nowadays) via `net.schmizz.sshj.connection.channel.direct.SessionChannel.allocateDefaultPTY`. However, If I was you, I'd check [if I really need PTY](https://en.wikipedia.org/wiki/Pseudoterminal#Applications). You explicitly told Docker [to use PTY](https://docs.docker.com/engine/reference/commandline/exec/#options), but what for?

**Comment by rainbowechoes** [comment]
> You may add PTY (aka pseudo-TTY, usually called as TTY since you can barely find a physical TTY nowadays) via `net.schmizz.sshj.connection.channel.direct.SessionChannel.allocateDefaultPTY`. However, If I was you, I'd check [if I really need PTY](https://en.wikipedia.org/wiki/Pseudoterminal#Applications). You explicitly told Docker [to use PTY](https://docs.docker.com/engine/reference/commandline/exec/#options), but what for?

In my app, I need to remotely connect to the host to operate the docker container or to access the container to execute commands. 

In my origin code, I use `docker exec -it ...`, but actually just use `docker exec -t ...`. And use `allocateDefaultPTY` method is also worked.

Thanks again for your reply
