### ISSUE TITLE
KeepAlive example incorrect

### ISSUE THREAD

**Issue by zman0900** [hierynomus/sshj#784]
It seems #752 was a breaking change for how KeepAlive must be enabled.  Previously, KeepAlive::setKeepAliveInterval would actually start the KeepAlive thread, so it could be (or had to be?) called after calling SSHClient::connect.  Now, it appears the thread is only started from SSHClient::onConnect, which is called during SSHClient::connect.  So if the keep alive interval is not pre-set before calling connect, the thread never starts.  

The `net.schmizz.sshj.examples.KeepAlive` class should be changed to show setting the interval before connecting.

**Comment by jkosternl** [comment]
@zman0900 , please close this issue, as the PR is merged, which fixes the issue. Thanks!
