### ISSUE TITLE
Azure Blob Storage SFTP / SSH_MSG_UNIMPLEMENTED

### ISSUE THREAD

**Issue by j0kkeri** [hierynomus/sshj#794]
I'm testing the Azure Blob Storage SFTP and when I use the keep-alive runner, the session will die after receiving "Unexpected: SSH_MSG_UNIMPLEMENTED" error.

Using version 0.33.0.
Setting keep-alive like this:
```
...
sshClient.getConnection().getKeepAlive().setKeepAliveInterval(10);
...
sshClient.connect(...);
```

Error occures right after 10 seconds (the keep-alive interval)...

Some log:

> kesäkuuta 20, 2022 3:13:16 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: KeepAliveRunner Started with interval [10 seconds]
> kesäkuuta 20, 2022 3:13:16 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: KeepAliveRunner Sending after interval [10 seconds]
> 
> ...
> ..
> .
> 
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: KeepAliveRunner Sending after interval [10 seconds]
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Making global request for `keepalive@openssh.com`
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Consuming by 18921 down to 1045904
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Received NAME packet
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Setting <<sftp / 86>> to `Buffer [rpos=5, wpos=18917, size=18917]`
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Sending Request{87;READDIR}
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Consuming by 49 down to 4294962777
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Awaiting <<sftp / 87>>
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Received SSH_MSG_UNIMPLEMENTED #94
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter error
> SEVERE: Dying because - Unexpected: SSH_MSG_UNIMPLEMENTED
> net.schmizz.sshj.common.SSHException: [PROTOCOL_ERROR] Unexpected: SSH_MSG_UNIMPLEMENTED
> 	at net.schmizz.sshj.AbstractService.notifyUnimplemented(AbstractService.java:63)
> 	at net.schmizz.sshj.transport.TransportImpl.gotUnimplemented(TransportImpl.java:566)
> 	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:495)
> 	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
> 	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200)
> 	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
> 
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter info
> INFO: Disconnected - PROTOCOL_ERROR
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Got notified of net.schmizz.sshj.common.SSHException: [PROTOCOL_ERROR] Unexpected: SSH_MSG_UNIMPLEMENTED
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Notified of net.schmizz.sshj.common.SSHException: [PROTOCOL_ERROR] Unexpected: SSH_MSG_UNIMPLEMENTED
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Channel #0 got notified of net.schmizz.sshj.common.SSHException: [PROTOCOL_ERROR] Unexpected: SSH_MSG_UNIMPLEMENTED
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Forgetting `session` channel (#0)
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Setting <<chan#0 / close>> to `SOME`
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Setting active service to null-service
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Sending SSH_MSG_DISCONNECT: reason=[PROTOCOL_ERROR], msg=[Unexpected: SSH_MSG_UNIMPLEMENTED]
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Setting <<transport close>> to `SOME`
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter error
> SEVERE: <<sftp / 87>> woke to: net.schmizz.sshj.sftp.SFTPException: Unexpected: SSH_MSG_UNIMPLEMENTED
> kesäkuuta 20, 2022 3:13:26 IP. org.slf4j.impl.JCLLoggerAdapter debug
> FINE: Stopping

Is it because of Azure or is it a bug in SSHJ lib? I realize that Azure is in preview-mode and may not even support the keep-alive function... In that case it might be beneficial to not kill the whole session and just end keep-alive runner?

**Comment by hierynomus** [comment]
Those two are two different implementations for the same thing. The HeartBeat is the first implementation that was built and that sends plain SSH_MSG_IGNORE packets. Those are safe to ignore by the server side, but for a lot of servers they work to reset their triggers for keep alive intervals.

The KeepAlive implementation does send actual keep alive messages which the server should respond to, thus also informing the client when the server has gone away. This is the preferred algorithm, but might not always work if the server does not support that (probably so in the case of Azure).

The bug here is definitely not in the library but with Azure, as that sends back an SSH_MSG_UNIMPLEMENTED, i.e. they have not implemented that message, thus you should either configure the Heartbeater or disable keep alive.

**Comment by j0kkeri** [comment]
> The bug here is definitely not in the library but with Azure, as that sends back an SSH_MSG_UNIMPLEMENTED, i.e. they have not implemented that message, thus you should either configure the Heartbeater or disable keep alive.

Ok, that was also my first impression but the Azure's documentation lacks to tell this though there are known limitations and eg. this is stated:
> Unsupported extensions include but aren't limited to: fsync@openssh.com, limits@openssh.com, lsetstat@openssh.com, statvfs@openssh.com

I will close this issue.

**Comment by j0kkeri** [comment]
Closed, problem within Azure
