### ISSUE TITLE
Error while creating SFTP Session, with ecdsa-sha2-nistp384, ecdsa-sha2-nistp384-cert-v01@openssh.com, ecdsa-sha2-nistp521 and ecdsa-sha2-nistp521-cert-v01@openssh.com algorithm

### ISSUE THREAD

**Issue by maheshsk28211** [hierynomus/sshj#803]
Error while creating SFTP Session

Unable to reach a settlement of HostKeyAlgorithms: [ssh-ed25519-cert-v01@openssh.com, ssh-ed25519, ecdsa-sha2-nistp521-cert-v01@openssh.com, ecdsa-sha2-nistp521, ecdsa-sha2-nistp384-cert-v01@openssh.com, ecdsa-sha2-nistp384, ecdsa-sha2-nistp256-cert-v01@openssh.com, ecdsa-sha2-nistp256, rsa-sha2-512, rsa-sha2-256, ssh-rsa-cert-v01@openssh.com, ssh-dss-cert-v01@openssh.com, ssh-rsa, ssh-dss] and []

**Comment by maheshsk28211** [comment]
The machine that has been connected over SFTP supports the above algorithm (ecdsa-sha2-nistp384, ecdsa-sha2-nistp384-cert-v01@openssh.com, ecdsa-sha2-nistp521 and ecdsa-sha2-nistp521-cert-v01@openssh.com) and has strict security

**Comment by hierynomus** [comment]
It seems that the server does not advertise its algorihtms, you're receiving an empty list from the server side. What kind of server is it? Might have something to do with the strict security?

**Comment by maheshsk28211** [comment]
Strict security means it supports only following HostKeyAlgorithm  

- ecdsa-sha2-nistp384
- ecdsa-sha2-nistp384-cert-v01@openssh.com
- ecdsa-sha2-nistp521
- ecdsa-sha2-nistp521-cert-v01@openssh.com

Previously we were using jcraft lib, but due to strict mode, we switch to your lib.
any specific steps needed for addHostKeyVerifier

**Comment by hierynomus** [comment]
Can you get a full debug log for a connection attempt?

**Comment by maheshsk28211** [comment]
12.Aug.2022 09:39:31.267 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error message: Connection refused (Connection refused)
12.Aug.2022 09:39:31.270 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[0]: java.net.PlainSocketImpl.socketConnect(Native Method)
12.Aug.2022 09:39:31.270 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[1]: java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
12.Aug.2022 09:39:31.271 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[2]: java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
12.Aug.2022 09:39:31.271 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[3]: java.net.AbstractPlainSocketImpl.connect(Unknown Source)
12.Aug.2022 09:39:31.271 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[4]: java.net.SocksSocketImpl.connect(Unknown Source)
12.Aug.2022 09:39:31.272 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[5]: java.net.Socket.connect(Unknown Source)
12.Aug.2022 09:39:31.272 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[6]: net.schmizz.sshj.SocketClient.connect(SocketClient.java:138)
12.Aug.2022 09:39:31.273 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[7]: com.xxx.yyy.connectors.cim.util.SftpSession.setupSshj(SftpSession.java:158)
12.Aug.2022 09:39:31.273 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[8]: com.xxx.yyy.connectors.cim.util.SftpSession.setDestination(SftpSession.java:174)
12.Aug.2022 09:39:31.274 EDT, [pool-56-thread-5],  ERROR, com.xxx.yyy.connectors.cim.util.SftpSession:error The error stack[9]: com.xxx.yyy.connectors.cim.util.SftpSession.<init>(SftpSession.java:87)

**Comment by hierynomus** [comment]
No, I really meant the debug logging output of the sshj lib, not just the stacktrace

**Comment by maheshsk28211** [comment]
That's only the output I have for sshj lib

	private SSHClient setupSshj(String remoteHost, int port, String username, String password) throws IOException {
		SSHClient client = new SSHClient();
		client.addHostKeyVerifier(new PromiscuousVerifier());
		client.connect(remoteHost, port);
		client.authPassword(username, password);
		return client;	
}
This is first method call, and it hit exception, previously this was working.

**Comment by maheshsk28211** [comment]
13.Aug.2022 01:14:32.725 EDT, [pool-57-thread-8],   INFO, net.schmizz.sshj.transport.random.JCERandom:<init> Creating new SecureRandom.
13.Aug.2022 01:14:32.727 EDT, [pool-57-thread-8],  DEBUG, net.schmizz.sshj.transport.random.JCERandom:<init> Random creation took 0 ms
13.Aug.2022 01:14:33.032 EDT, [pool-57-thread-8],  DEBUG, net.schmizz.sshj.DefaultConfig:initCipherFactories Available cipher factories: [chacha20-poly1305@openssh.com, aes128-cbc, aes128-ctr, aes192-cbc, aes192-ctr, aes256-cbc, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com, blowfish-cbc, blowfish-ctr, cast128-cbc, cast128-ctr, idea-cbc, idea-ctr, serpent128-cbc, serpent128-ctr, serpent192-cbc, serpent192-ctr, serpent256-cbc, serpent256-ctr, 3des-cbc, 3des-ctr, twofish128-cbc, twofish128-ctr, twofish192-cbc, twofish192-ctr, twofish256-cbc, twofish256-ctr, twofish-cbc, arcfour, arcfour128, arcfour256]
13.Aug.2022 01:14:32.725 EDT, [pool-57-thread-8],   INFO, net.schmizz.sshj.transport.random.JCERandom:<init> Creating new SecureRandom.
13.Aug.2022 01:14:33.350 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error message: Connection refused (Connection refused)
13.Aug.2022 01:14:33.350 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[0]: java.net.PlainSocketImpl.socketConnect(Native Method)
13.Aug.2022 01:14:33.351 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[1]: java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
13.Aug.2022 01:14:33.351 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[2]: java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
13.Aug.2022 01:14:33.351 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[3]: java.net.AbstractPlainSocketImpl.connect(Unknown Source)
13.Aug.2022 01:14:33.351 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[4]: java.net.SocksSocketImpl.connect(Unknown Source)
13.Aug.2022 01:14:33.351 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[5]: java.net.Socket.connect(Unknown Source)
13.Aug.2022 01:14:33.351 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[6]: net.schmizz.sshj.SocketClient.connect(SocketClient.java:138)
13.Aug.2022 01:14:33.351 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[7]: com.xxx.xxx.connectors.cim.util.SftpSession.setupSshj(SftpSession.java:181)
13.Aug.2022 01:14:33.352 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[8]: com.xxx.xxx.connectors.cim.util.SftpSession.setDestination(SftpSession.java:197)
13.Aug.2022 01:14:33.354 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[9]: com.xxx.xxx.connectors.cim.util.SftpSession.<init>(SftpSession.java:90)
13.Aug.2022 01:14:33.354 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[10]: com.xxx.xxx.plugins.xxx.nodes.BMUService.performRDOC(BMUService.java:195)
13.Aug.2022 01:14:33.355 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[11]: com.xxx.xxx.plugins.xxx.connectors.connectorImpl.xxxConnectorImpl.performRDOC(xxxConnectorImpl.java:2817
13.Aug.2022 01:14:33.355 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[12]: sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13.Aug.2022 01:14:33.355 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[13]: sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
13.Aug.2022 01:14:33.356 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[14]: sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
13.Aug.2022 01:14:33.357 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[15]: java.lang.reflect.Method.invoke(Unknown Source)
13.Aug.2022 01:14:33.357 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[16]: com.xxx.xxx.plugins.xxx.connectors.connectorImpl.FailoverCapableImplWrapper.invoke(FailoverCapableImplWrapper.java:109)
13.Aug.2022 01:14:33.358 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[17]: com.sun.proxy.$Proxy315.performRDOC(Unknown Source)
13.Aug.2022 01:14:33.358 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[18]: com.xxx.xxx.plugins.cirm.handlers.BMUTransactionHandler.handle(BMUTransactionHandler.java:204)
13.Aug.2022 01:14:33.359 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[19]: com.xxx.ebg.transaction.PriorityTransactionEngine$PollingWorker.handleTransaction(PriorityTransactionEngine.java:418)
13.Aug.2022 01:14:33.359 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[20]: com.xxx.ebg.transaction.PriorityTransactionEngine$PollingWorker.run(PriorityTransactionEngine.java:377)
13.Aug.2022 01:14:33.359 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[21]: java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
13.Aug.2022 01:14:33.360 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[22]: java.util.concurrent.FutureTask.run(Unknown Source)
13.Aug.2022 01:14:33.360 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[23]: java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
13.Aug.2022 01:14:33.361 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[24]: java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
13.Aug.2022 01:14:33.361 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:error The error stack[25]: java.lang.Thread.run(Unknown Source)
13.Aug.2022 01:14:33.362 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:fail CIM-SFTP: Unable to create SFTP Session to 10.241.136.187
13.Aug.2022 01:14:33.363 EDT, [pool-57-thread-8],  ERROR, com.xxx.xxx.connectors.cim.util.SftpSession:fail CIM-SFTP: ... Connection refused (Connection refused)

**Comment by hierynomus** [comment]
Connection refused means that the server isn't reachable (or nog listening on port 22)

**Comment by maheshsk28211** [comment]
It was user error, and it did block port after new algorithm was included. 
Thanks for your time.
