### ISSUE TITLE
How to set transfer mode (binary or ascii)

### ISSUE THREAD

**Issue by hanct** [hierynomus/sshj#808]
Hi,
   I am using this sshj library to do SFTP transfer of file, and would like to know if there is any document related to how to set file transfer mode (binary or ascii).

I search online for "sshj transfer mode", but no get any relevant result

**Comment by hierynomus** [comment]
https://www.ibm.com/support/pages/does-sftp-have-ascii-and-binary-modes-ftp

There is no such thing for SFTP. This is only in plain FTP, not the secured variant.

**Comment by hannah23280** [comment]
Hi,
Thanks for the reply.
Strange, cos But further searching online, there seem to be such mode for SFTP.
E.g https://doc.componentpro.com/ComponentPro-Sftp/ascii-and-binary-transfer-modes

**Comment by hierynomus** [comment]
Not sure why this is important, binary mode is what you always should want anyway, and what is only supported. The magic conversion that potentially happens with text mode in plain FTP, is more often than not problematic.

**Comment by hannah23280** [comment]
> 
Long time back, i use a utility that act as SFTP client, and I recall the transfer has issue when sending binary file in text mode, but no issue when set in binary mode, so i thought that the mode need to be set correctly.

Btw, do u mean that sshj library already implicitly set to binary mode?

**Comment by vladimirlagunov** [comment]
@hannah23280 Could you show the RFC that describes the text mode in SFTP?

**Comment by hannah23280** [comment]
> @hannah23280 Could you show the RFC that describes the text mode in SFTP?

Oops..sorry, typo not text mode. Should be ascii mode.  

In RFC https://datatracker.ietf.org/doc/rfc913/  , there is indeed a section that talks about 3 different modes - Ascii | Binary | Continuous.   This is my first time heard of Continuous mode.

**Comment by hierynomus** [comment]
Ahhh but now you're confusing SFTP with SFTP 🤣 ... There's Simple File Transfer Protocol and Secure File Transfer Protocol.

SSHJ implements the Secure one, not the simple one

**Comment by hannah23280** [comment]
> SFTP with SFTP

Oooh...haha.....wau..i never even notice the difference. Thanks for highlighting this!!
