### ISSUE TITLE
Support for "password change request" operation

### ISSUE THREAD

**Issue by aledsage** [hierynomus/sshj#81]
Feature request: I'd like to be able to change an expired password using sshj.

A new VM (running in vcloud, provisioned with jclouds) has a one-type-use password, so needs to be changed immediately.
 
When I connect with sshj, I get the following errors:

    2012-06-22 17:08:16,258 ERROR  <<<authenticated>> woke to: net.schmizz.sshj.userauth.UserAuthException: Password change request received; unsupported operation>
    2012-06-22 17:08:16,282 ERROR  <<<authenticated>> woke to: net.schmizz.sshj.userauth.UserAuthException: keyboard-interactive auth failed>

When I ssh at the command like, I get...

    $ ssh Administrator@123.123.123.123
    
    Administrator@123.123.123.123's password: 
    The password for this account has expired and must be changed.
    Enter Administrator@123.123.123.123's old password: 
    Enter Administrator@123.123.123.123's new password: 
    Retype Administrator@123.123.123.123's new password:

**Comment by dkocher** [comment]
Duplicate for #193. Fix in eb8b7b51ca4667c3651b7afe21f98ece1e503666.

**Comment by hierynomus** [comment]
Indeed, thanks David! Closing this one as it is now fixed :)
