### ISSUE TITLE
Paramiko server responds to stat() with FAILURE rather than NO_SUCH_FILE

### ISSUE THREAD

**Issue by ghherlin** [hierynomus/sshj#817]
I have a Kotlin/Java application that interacts with several SFTP and FTP servers. SFTP is provided by SSH-2.0-SSHJ_0.34.0.
One of these servers is based on: SSH-2.0-paramiko_1.16.0.
This server offers only: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1

Searching for an existing resolution, I found issue [https://github.com/hierynomus/sshj/issues/670](url), which gave me a plausible reason for this problem...
After some searching around, and failing to get the application's logger to output SSHJ's SLF4J output, I reached the point at which the original BufferException is thrown:
```
ensureAvailable:137, Buffer (net.schmizz.sshj.common)
readUInt32:302, Buffer (net.schmizz.sshj.common)
readUInt32AsInt:297, Buffer (net.schmizz.sshj.common)
readStatusCode:107, Response (net.schmizz.sshj.sftp)
ensurePacketTypeIs:117, Response (net.schmizz.sshj.sftp)
stat:283, SFTPEngine (net.schmizz.sshj.sftp)
stat:227, SFTPEngine (net.schmizz.sshj.sftp)
prepareFile:340, SFTPFileTransfer$Uploader (net.schmizz.sshj.sftp)
uploadFile:256, SFTPFileTransfer$Uploader (net.schmizz.sshj.sftp)
upload:209, SFTPFileTransfer$Uploader (net.schmizz.sshj.sftp)
access$100:192, SFTPFileTransfer$Uploader (net.schmizz.sshj.sftp)
upload:81, SFTPFileTransfer (net.schmizz.sshj.sftp)
upload:76, SFTPFileTransfer (net.schmizz.sshj.sftp)
put:263, SFTPClient (net.schmizz.sshj.sftp)
```
The value of the target is:
```
this = Buffer [rpos=21, wpos=24, size=24]
this.data = [101, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 7, 70, 97, 105, 108, 117, 114, 101, 0, 0, 0, 0]
this.type = PacketType.STATUS
this.protocolVersion = 3
this.available() = **3 (yes, not 4!)**
```
When targeting a test server (SSH-2.0-OpenSSH_9.0, ), everything works perfectly.
When using the (debian) sftp CLI application, the upload succeeds.
As a result, like @jmatias-assia and yourself, I suspect that there is a problem introduced by the use of diffie-hellman-group1-sha1.

The fault is persistent, and happens on every attempt to put().

Regrettably, the server is not open to the public, so I can't give you access to it, but I can either do your bidding, or, alternatively, can clone the project and try to find a resolution myself.

Which would you prefer? Be advised that I have no background in cryptography.

**Comment by vladimirlagunov** [comment]
Such kind of errors usually happen when an attempt to read from/write to an already terminated SSH connections is made. It's still better to make the application logger work with debugging logs of SSHJ and look what happens before the error.

**Comment by ghherlin** [comment]
Success. With the logs, that is :-( .
Attached, 3 log files, showing one transaction each, one successful (meaning the put() succeeded), and two clarifying what is above.

The files have been extracted from the general log. All lines not relating to these transactions have been removed. 

[sshj log when success eg file exists in remote.log](https://github.com/hierynomus/sshj/files/9625625/sshj.log.when.success.eg.file.exists.in.remote.log)
[sshj log when failure nonexistent remote file type b issue #817.log](https://github.com/hierynomus/sshj/files/9625790/sshj.log.when.failure.nonexistent.remote.file.type.b.issue.817.log)
[sshj log when failure nonexistent remote file type a issue #817.log](https://github.com/hierynomus/sshj/files/9625792/sshj.log.when.failure.nonexistent.remote.file.type.a.issue.817.log)

In attempting to obtain the logs, the following became apparent:
1. The problem appears only when the uploaded file **DOES NOT EXIST** in the remote directory
2. Whenever the upload target file exists in the remote directory, the upload succeeds
3. There are 2 types of fault, types a and b
4. Fault type a occurs once only after application restart
5. Fault type b occurs every time after
6. The above stack trace is common to both types, could this be due to differences in the form of error recovery?

I remain at your disposal

**Comment by vladimirlagunov** [comment]
So, it turned out, that the problem is not in key exchange or authentication, but in the SFTP. I doubt that it's due to diffie-hellman-group1-sha1.

```
TRACE: IN #0: 00 00 00 18 65 00 00 00 03 00 00 00 04 00 00 00 07 46 61 69 6c 75 72 65 00 00 00 00
```
00 00 00 18 -- length
65 -- packet type (STATUS)
00 00 00 03 -- request id

Looks like a valid packet, but SSHJ fails to parse it.

```
net.schmizz.sshj.common.Buffer$BufferException: Underflow
 net.schmizz.sshj.sftp.Response.readStatusCode(Response.java:109)
 net.schmizz.sshj.sftp.Response.ensurePacketTypeIs(Response.java:117)
 net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:283)
 net.schmizz.sshj.sftp.SFTPEngine.stat(SFTPEngine.java:227)
 net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.prepareFile(SFTPFileTransfer.java:340)
 net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.uploadFile(SFTPFileTransfer.java:256)
 net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.upload(SFTPFileTransfer.java:209)
 net.schmizz.sshj.sftp.SFTPFileTransfer$Uploader.access$100(SFTPFileTransfer.java:192)
```

It can be easier to debug if you prepared a Dockerfile with the problematic server and a simple app on Java or Kotlin that reproduces the problem. Or, let's wait someone experienced in this code.

**Comment by ghherlin** [comment]
I agree. But I cannot duplicate the "problematic" server, since it is a "homebrew" application made by the vendor of the services it renders (hence the use of the paramiko library).

So I'll clone the repo and fix it myself, then make a pull request. The SFTP part of it is (relatively) easy to read. I'll keep this issue posted with my observations on the way.

Thanks for your help.

**Comment by ghherlin** [comment]
So far, I have discovered 2 problems:

Root cause:
When receiving an SSH_FXP_STAT request for a file that does not exist, this non-compliant server always responds with SSH_FX_FAILURE, instead of SSH_FX_NO_SUCH_FILE. When the file exists, it responds correctly with a SSH_FXP_ATTRS packet containing the required data.

This breaks the upload code, which does a stat() to eliminate the case when the remote file path is in fact a directory.

For the root cause, I am seeking a response from the owner of the server.

There is, however, another problem:
In attempting to recover from this error, the client attempts to read the error/status code field of the received SSH_FXP_STATUS. This fails, because the rpos index has been moved from its position to close to the end of the byte[], and trying to read 4 bytes from 3 available bytes fails.
The value of rpos in this case is wrong.

I have (pro tem.) hardwired a fix, but I'm hoping to find out why and where in  the code the rpos is moved too far.

When I find out what happens, I'll propose a durable fix for this latter problem.

**Comment by vladimirlagunov** [comment]
> this non-compliant server always responds with SSH_FX_FAILURE

Also, for example, OpenSSH SFTP returns this code if you try to create an already existing directory, despite that it'd expect FILE_ALREADY_EXISTS in this case. So, one's application should be ready to handle FAILURE even when it's not expected. And, if SSHJ doesn't handle it correctly, it would be great to have it fixed.

> In attempting to recover from this error, the client attempts to read the error/status code field of the received SSH_FXP_STATUS.

Ironically, the error happens inside the error handler. As far as I remember, there are no tests on that case, and it would be difficult to write them.

**Comment by ghherlin** [comment]
Hmmm...

What you tell me makes me think that a rather general solution is needed, rather than a quick fix.
Do you agree?

**Comment by ghherlin** [comment]
One night's musings later, I think that we are facing a "trident" of issues:
1) how to deal best with the vagaries and errors in the plethora of servers faced by SSH4J
2) how to fix the error-reporting issue identified above
3) How to reduce the time wasted in the diagnostic of these issues.

I have created 2 new issues, in order that the wanderings at the beginning do not deter the reader from continuing.

Thanks to @vladimirlagunov for his aid in reaching this point.
