### ISSUE TITLE
sshj appears to periodically send bad connection attempts with user=username

### ISSUE THREAD

**Issue by Bennett-Lynch** [hierynomus/sshj#854]
I'm currently investigating an issue where the sshj library appears to periodically send bad connection attempts with user=username. These bad connection attempts are logged on the server-side as follows:

```
ftp sshd: Failed password for invalid user username from [...] port [...] ssh2
```

The client-side is configured with correct credentials and never experiences an authentication failure on the request-path. It seems that these connection attempts are submitted asynchronously and with timestamps that don't strictly correlate to the client-side usage. The client also does not have keep-alive enabled.

Apologies if the above details are sparse, but is there any behavior in the sshj library that could explain this?

Version used: [0.33.0](https://mvnrepository.com/artifact/com.hierynomus/sshj/0.33.0)

**Comment by hierynomus** [comment]
👍
