### ISSUE TITLE
sshj Specifies whether to upload the character conversion file stream to the host directory

### ISSUE THREAD

**Issue by wzd-hash** [hierynomus/sshj#866]
sshj Specifies whether to upload the character conversion file stream to the host directory

**Comment by hierynomus** [comment]
Can you ask a question that involves more than a single sentence with random words?

**Comment by wzd-hash** [comment]
I want to convert the character content of the code directly into a file stream and upload it directly to a remote host, instead of creating a file on the local machine and then uploading the file to the host

**Comment by hierynomus** [comment]
Ok, so what have you tried? Both SCP and SFTP support an interface called `LocalSourceFile`. This interface is implemented by `InMemorySourceFile` (which could be named better)... You can make an anonymous instance of that one that just implements `getInputStream`

from the top of my head:

```java
client.upload(new InMemorySourceFile() { public InputStream getInputStream() { return myInputStream; } });
```

**Comment by wzd-hash** [comment]
I've tried this, but I don't know if it's right. It says, "No such file."

sftp.getSFTPEngine().open(filePath).write(0,bytes,0,bytes.length);

**Comment by wzd-hash** [comment]
Thank you. I've made it
