### ISSUE TITLE
SLF4J 1.7 compatibility

### ISSUE THREAD

**Issue by rhuddleston** [hierynomus/sshj#882]
I see you upgraded slf4j to 2.0, does it require 2.0 or can I still override with 1.7 and it will continue to work? 

I ask as it's being included with a larger application that isn't yet ready to move to 2.x

thanks!

**Comment by exceptionfactory** [comment]
SLF4J usage in SSHJ still uses the same interfaces from SLF4J 1.7 and does not make use of the new fluent API in SLF4J 2.0. 

With that background, as long as you are on Java 8 or higher, it should be possible to override the SLF4J version to 1.7 in your project dependency management configuration. This may not be true for future versions, but it should work for now.

**Comment by rhuddleston** [comment]
Great, thanks for the confirmation!
