### ISSUE TITLE
UploadFile writes OpenModes into wrong place in packet

### ISSUE THREAD

**Issue by nd** [hierynomus/sshj#888]
Hi! I think I found a problem with the OPEN packet serialization.

[SFTPEngine.open](https://github.com/hierynomus/sshj/blob/30691384824b3f2ac1fa7e41982ae47ee1a4bdc5/src/main/java/net/schmizz/sshj/sftp/SFTPEngine.java#L152) writes OpenModes mask right after the file path. 

According to [the spec](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13#section-8.1.1) filename is followed by [ace-mask](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13#section-7.8), so `OpenMode.TRUNC(0x00000010)` is interpreted as `ACE4_WRITE_NAMED_ATTRS = 0x00000010`, and `OpenMode.EXCL(0x00000020)` is interpreted as `ACE4_EXECUTE = 0x00000020`.

As a result an attempt to open a file with OpenModes WRITE | CREATE | TRUNC fails when the file already exists.

**Comment by hierynomus** [comment]
That is not entirely correct. Indeed the spec you mention has the `desiredAccess` and then the `flags`. However this relates to version 6 of the sftp protocol. OpenSSH and SSHJ both implement version 3 of the protocol which is documented in revision 4 of the ietf draft spec.

Also see: https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol

Versions 4, 5 and 6 indeed serialize the new format.

**Comment by nd** [comment]
Oh, I didn't realize that, thanks for clarifying. I should also have checked server logs before reporting: they actually contain the right flags. The uploaded file is executable and during an attempted updated it was loaded by GDB. Somehow it makes open with `WRITE | CREAT | TRUNC` flags to fail.

**Comment by hierynomus** [comment]
Can this ticket be closed?

**Comment by nd** [comment]
Yes, I was wrong, please close the issue. Thank you for support!

**Comment by hierynomus** [comment]
DOne1
