### ISSUE TITLE
StatefulSFTPClient can't recover from a wrong change of working directory

### ISSUE THREAD

**Issue by plepropre** [hierynomus/sshj#90]
Hello there,

This bug has been noticed on the 0.8.1 version of sshj.  Let's consider the following code snippet:

``` java
StatefulSFTPClient sftp = new StatefulSFTPClient(engine);
...
...
try {
  sftp.cd("/somewrong/directory/");
}
catch (SFTPException e) {
  logger.warn("Wrong change of working directory.", e);
}
System.out.println(sftp.pwd()); //SFTPException raised because of "no such file"
```

The issue comes directly from the code of the StatefulSFTPClient#cd(String) command which do not backup the former (and really working) directory. 
So what happens is that when the wrong cd command is issued, the internal state of StatefulSFTPClient is modified in any case, which makes it then believe, after the try/catch block, that its current working directory is "/somewrong/directory".

Here is the current workaround I use, which should be directly implemented in the cd() method's code:

``` java
StatefulSFTPClient sftp = new StatefulSFTPClient(engine);
...
...
String oldWorkingDirectory = sftp.pwd();
try {
  sftp.cd("/somewrong/directory/");
}
catch (SFTPException e) {
  logger.warn("Wrong change of working directory.", e);
  sftp.cd(oldWorkingDirectory) // Manual RECOVERY
}
System.out.println(sftp.pwd()); //will NOT raise an SFTPException anymore
```

I'm not used to GitHub but if you want me to do the patch myself, please ask and I'll do it.

Cheers,

Pierre.

**Comment by samueldandu** [comment]
I am getting ---  error: cannot find symbol errors,,

1)symbol:   method pwd()
location: variable sftp of type SFTPClient

2)symbol:   method cd(String)
  location: variable sftp of type SFTPClient
