### ISSUE TITLE
SFTP RSA negotiation vulnerability

### ISSUE THREAD

**Issue by el020** [hierynomus/sshj#914]
The very new RSA vulnerability explained in this paper https://eprint.iacr.org/2023/1711.pdf has been patched by one of our vendors Crash SFTP and they are denying connections because SSHJ is susceptible to this vulnerability. 

net.schmizz.sshj.transport.TransportException: [KEY_EXCHANGE_FAILED] KeyExchange signature verification failed

Please let me know if you need more info.

**Comment by exceptionfactory** [comment]
> The very new RSA vulnerability explained in this paper https://eprint.iacr.org/2023/1711.pdf has been patched by one of our vendors Crash SFTP and they are denying connections because SSHJ is susceptible to this vulnerability.
> 
> net.schmizz.sshj.transport.TransportException: [KEY_EXCHANGE_FAILED] KeyExchange signature verification failed
> 
> Please let me know if you need more info.

Thanks for highlighting the research on this vulnerability related to RSA signature faults @el020.

There are a number of news reports summarizing the research, most of which highlight server-side mitigations in OpenSSH and OpenSSL, which may not be present in proprietary SSH server software.

The error message from SSHJ does not provide enough information to evaluate the problem with the particular SFTP connection, so it would be helpful to provide a full log of debug output showing the SSH algorithm negotiation process.

The research focuses primarily on SSH servers and computation of RSA signatures, applicable to both the legacy `ssh-rsa` algorithm and the newer SHA-2 RSA signing algorithms. SSHJ is capable of negotiating signatures based on elliptic curve algorithms, but that negotiation depends on the algorithms that a particular SSH server supports.

If there are other adjustments necessary to the RSA signature generation in SSHJ itself, providing additional debug logging for the failure might help highlight what should be evaluated.

**Comment by spinkb** [comment]
The SSH library being hit is "sshtools"...JAdaptive, latest.  This is the server side log trace from that issue.  JAdaptive does its own calculation to mitigate the connection issue.  Maybe this info helps?

`SSH_SERVER|11/29/2023 15:09:58.409|Verifying signature output to mitigate passive SSH key compromise vulnerability
SSH_SERVER|11/29/2023 15:09:58.409|Encoded Signature: 303C021C41773229D4305DCB7CF6951C8EF93756D8B1A0B47ACFCBA2C0BB40AF021C49E6CFAD910651DF71A060E63770EB70E7B15A835D5601BC018FC4EF
SSH_SERVER|11/29/2023 15:09:58.409|R: 41773229D4305DCB7CF6951C8EF93756D8B1A0B47ACFCBA2C0BB40AF len=28 numSize=28
SSH_SERVER|11/29/2023 15:09:58.409|S: 49E6CFAD910651DF71A060E63770EB70E7B15A835D5601BC018FC4EF len=28 numSize=28
SSH_SERVER|11/29/2023 15:09:58.409|Posting message com.maverick.sshd.components.jce.server.DiffieHellmanGroupExchangeSha1JCE$4 to queue
SSH_SERVER|11/29/2023 15:09:58.409|Posting message com.maverick.sshd.TransportProtocol$6 to queue
SSH_SERVER|11/29/2023 15:09:58.409|Processing APPLICATION WRITE event
SSH_SERVER|11/29/2023 15:09:58.409|Sent SSH_MSG_KEY_DH_GEX_REPLY
SSH_SERVER|11/29/2023 15:09:58.409|Processing APPLICATION WRITE event
SSH_SERVER|11/29/2023 15:09:58.409|Sent SSH_MSG_NEWKEYS
SSH_SERVER|11/29/2023 15:09:58.442|Processing APPLICATION READ data
SSH_SERVER|11/29/2023 15:09:58.442|Processing SSH_MSG_DISCONNECT
SSH_SERVER|11/29/2023 15:09:58.442|Remote client disconnected from /[127.0.0.1:57882](http://127.0.0.1:57882/) reason=KeyExchange signature verification failed`
