### ISSUE TITLE
Suggestions on Improving the Security Algorithm for Calculating Fingerprints

### ISSUE THREAD

**Issue by Leopold0801** [hierynomus/sshj#923]
I found that the MD5 algorithm is used to calculate the fingerprint. Why not consider the SHA-256 algorithm? SHA-256 is known to be more secure than MD5.
![截图](https://github.com/hierynomus/sshj/assets/49242543/b69c0733-0f9c-4287-905d-98d52eb0bbe0)

**Comment by hierynomus** [comment]
It's MD5 as it's in the standard SSH format.
