### ISSUE TITLE
I have tried to disconnect the sshclient in my java code, but the operating system did not disconnect port 22?

### ISSUE THREAD

**Issue by graybird7** [hierynomus/sshj#927]
![image](https://github.com/hierynomus/sshj/assets/158164740/454e7862-6b43-4243-aff0-2208a97b859e)

![image](https://github.com/hierynomus/sshj/assets/158164740/9b664ad4-d550-4192-891f-9037bad90c90)

**Comment by jhammelm** [comment]
Maybe try to avoid closing connections / sessions etc. at finally! close() calls interrupt(), which doesn't close threads anymore at finally. If you use Java 11, please upgrade - there is a bug in Java 11.

**Comment by graybird7** [comment]
I'm using java8. Tried not using finally, and closing the session and disconnecting at the code block end, but it didn't work. Also tried not closing the session and connection, but that didn't work either。
