### ISSUE TITLE
RemoteFile#write(long,byte[],int,int): deadlocks are very likely to happen.

### ISSUE THREAD

**Issue by plepropre** [hierynomus/sshj#93]
Hello,

SFTPClient is only offering put methods where a local file is involved as an input. As it wasn't convenient for my usage, I used an other approach with the RemoteFile#write() method.

Here is a snippet of the work involved:

``` java
private static final int BUFFER_SIZE = 1024 * 1024; //1MB
...
  public boolean someMethod(String remoteDestFile, InputStream localSrcStream) throws IOException {
    RemoteFile file = openRemoteFile(remoteDestFile, EnumSet.of(OpenMode.WRITE, OpenMode.CREAT, OpenMode.TRUNC));

    byte[] readingBuffer = new byte[BUFFER_SIZE];
    int off = 0;
    while (true) {
      int count = localSrcStream.read(readingBuffer);
      if (count == -1) {
        break;
      }
      file.write(off, readingBuffer, 0, count);
      off += count;
    }
    file.close();
    ...
  }
```

Being under the assumption that everything was being dealt by the underlying write method, I didn't pay much attention. That was wrong, really wrong, as one call to write() is equivalent to sending one big SFTP packet.

Most servers will reject a 1MB long packet and answers that it's too big (or they won't). My application went to deadlock in that situation. 

When we take a look at SFTPFileTransfer.Uploader#uploadFile(), we can see the following:

``` java
 new StreamCopier(fis, rf.getOutputStream())
                            .bufSize(engine.getSubsystem().getRemoteMaxPacketSize() - rf.getOutgoingPacketOverhead())
                            .keepFlushing(false)
                            .listener(listener)
                            .copy();
```

This is what I was missing:

``` java
engine.getSubsystem().getRemoteMaxPacketSize() - rf.getOutgoingPacketOverhead()
```

There should be a way to warn people or force their hand about this whole packet size issue...

Cheers,

Pierre.

**Comment by yantom** [comment]
File is still named InMemorySourceFile, which is fine for me, however it would be great if you could point this information about no need for actual getLength() somewhere in doc. Javadoc was one of reasons why I moved from jsch to sshj.
