### ISSUE TITLE
SCPUpload#upload does not work with ~/... as remotePath

### ISSUE THREAD

**Issue by foosel** [hierynomus/sshj#94]
Quoting the remotePath in single quotes for the scp upload command seems to cause the remote side not expanding the remote path correctly which leads to a "file not found" error. 

OpenSSH sends the path without single quotes.

**Comment by craftmaster2190** [comment]
My workaround:
new SSHClient().newSCPFileTransfer().newSCPUploadClient().copy(local, remote, SCPCommandLine.EscapeMode.NoEscape)

**Comment by hierynomus** [comment]
Yes, correct, the EscapeMode was introduced to fix this. Just forgot this issue.
