### ISSUE TITLE
When to expect the new v0.39.0 version?

### ISSUE THREAD

**Issue by matzuk** [hierynomus/sshj#953]
Hey folks!

Could you please share an approximate timeline for releasing the new version? The master branch contains many useful updates that have not yet been released. For example, users of the [Marathon Test Runner](https://github.com/MarathonLabs/marathon) encounter the following problem when trying to establish a connection with macOS machines:
```
192.168.18.131:22-1714052810088] <TransportImpl> Dying because - strict KEX violation: KEXINIT was not the first packet
net.schmizz.sshj.transport.TransportException: strict KEX violation: KEXINIT was not the first packet
```

This problem is becoming increasingly critical. The master branch includes [PR #934](https://github.com/hierynomus/sshj/pull/934), which fixes this issue.

**Comment by 2211898719** [comment]
I agree that I need #933

**Comment by 2211898719** [comment]
Has anyone compiled and generated one themselves

**Comment by 2211898719** [comment]
It seems that a special JDK is needed, and the download is too slow

**Comment by hierynomus** [comment]
Should be released now

**Comment by hpoettker** [comment]
@hierynomus Thanks!

Thank you so much for maintaining this project! It's really appreciated.
